apply plugin: 'com.android.tools.java-library'
apply plugin: 'com.android.tools.kotlin'
apply plugin: 'com.android.tools.publish'

dependencies {
    implementation project(':analytics-library:protos')
    implementation project(':analytics-library:shared')
    implementation project(':analytics-library:tracker')
    implementation libs.com.android.tools.annotations
    implementation libs.com.android.tools.common
    implementation project(':base:testutils')
    implementation libs.guava
    implementation libs.gson

    testImplementation libs.junit
    testImplementation libs.truth
}

group = 'com.android.tools.analytics-library'
archivesBaseName = 'testing'
version = rootProject.ext.baseVersion

project.ext.pomName = 'Android Tools Analytics Testing Library'
project.ext.pomDesc = 'Library for tracking usage analytics.'
