apply plugin: 'com.android.tools.java-library'
apply plugin: 'com.android.tools.publish'
apply plugin: 'idea'
apply plugin: 'com.google.protobuf'
apply plugin: 'sdk-java-lib'

protobuf {
    protoc {
        artifact = libs.proto_compiler
    }
}

idea.module {
    generatedSourceDirs += new File(protobuf.generatedFilesBaseDir)
}

dependencies {
    compile libs.protobuf
}

group = 'com.android.tools.analytics-library'
archivesBaseName = 'protos'
version = rootProject.ext.baseVersion

project.ext.pomName = 'Android Tools Analytics Protobufs'
project.ext.pomDesc = 'Library containing protobufs for usage analytics.'
