apply plugin: 'java'
apply plugin: 'com.google.protobuf'

protobuf {
    protoc {
        artifact = libs.proto_compiler
    }
}

dependencies {
    compile libs.protobuf
}

group = 'com.android.tools.analytics-library'
archivesBaseName = 'protos'
version = rootProject.ext.baseVersion

project.ext.pomName = 'Android Tools Analytics Protobufs'
project.ext.pomDesc = 'Library containing protobufs for usage analytics.'

apply from: "$rootDir/buildSrc/base/publish.gradle"
apply from: "$rootDir/buildSrc/base/javadoc.gradle"

// There are now two versions of the generated java files for the analytics proto,
//
// -- Studio (adt/idea):          Proto 2.5: Generated as part of the export step
//                                           and checked in to src/main/java.
// -- Gradle plugin (tools/base): Proto 3.0: Generated during the gradle build.
//
// Therefore don't include the proto 2.5 generated sources, they are consumed by studio only.
sourceSets.main.java.srcDirs = []
