// This file (analytics_enums.proto) should be directly
// edited in Android Git (platform/tools/analytics-library)
//
//
// This file is separate from the main studio_stats.proto to
// allow tasks or project options to be added without having
// to go through the usual analytics change process to record
// them in the analytics.
//
// The uploaded GradleBuildProfile (see studio_stats.proto)
// will just contain the integer value, which means that
// values must be consistent and never reused.
//
// For example, ANDROID_JAVA_COMPILE will be encoded as '3'
// in the GradleTaskExecution message. To find out what the
// task class name was, this file should be consulted.
//
// Take care when cherry-picking changes that you preserve the
// numeric value across branches, even if that means leaving
// gaps.
//
// Unlike the main analytics, it is OK to rename an enum entry
// e.g. when BundleFeatureClasses was renamed to
// BundleAllClasses the enum constant was also renamed.

syntax = "proto3";
option java_package = "com.android.tools.build.gradle.internal.profile";
option java_multiple_files = true;

enum GradleTransformExecutionType {
    UNKNOWN_TRANSFORM_TYPE = 0;
    DEX = 1;
    EXTRACT_JARS_TRANSFORM = 2;
    INSTANT_RUN_DEX = 3;
    INSTANT_RUN_SLICER = 4;
    INSTANT_RUN_TRANSFORM = 5;
    INSTANT_RUN_VERIFER_TRANSFORM = 6;
    JACK_PRE_DEX = 7;
    JACK = 8;
    DEPRECATED_JACOCO = 9 [deprecated=true];
    JAR_MERGING = 10;
    LIBRARY_JAR = 11;
    LIBRARY_JNI_LIBS_TRANSFORM = 12 [deprecated=true];
    MERGE_JAVA_RESOURCES_TRANSFORM = 13;
    MULTI_DEX = 14;
    BUILT_IN_SHRINKER = 15;
    NO_CHANGES_VERIFIER_TRANSFORM = 16;
    PRO_GUARD_TRANSFORM = 17;
    SHRINK_RESOURCES_TRANSFORM = 18;
    DATA_BINDING_MERGE_ARTIFACTS = 19 [deprecated=true];
    INSTANT_RUN_VERIFIER_TRANSFORM = 20;
    STRIP_DEBUG_SYMBOL_TRANSFORM = 21 [deprecated=true];
    LIBRARY_API = 22;
    INSTANT_RUN_DEPENDENCIES_APK_BUILDER = 23;
    INSTANT_RUN_SLICE_SPLIT_APK_BUILDER = 24;
    PRE_DEX = 25;
    JACK_COMPILE = 26;
    JACK_GENERATE_DEX = 27;
    CUSTOM_CLASS_TRANSFORM = 28;
    DEX_ARCHIVE_BUILDER_TRANSFORM = 29;
    DEX_MERGER_TRANSFORM = 30;
    MAIN_DEX_LIST = 31;
    DESUGAR_TRANSFORM = 32 [deprecated=true];
    FIX_STACK_FRAMES = 33 [deprecated=true];
    EXTERNAL_LIBS_MERGER_TRANSFORM = 34;
    D8_MAIN_DEX_LIST_TRANSFORM = 35 [deprecated=true];
    DATA_BINDING_MERGE_GEN_CLASS_LOG = 36 [deprecated=true];
    R8_TRANSFORM = 37 [deprecated=true];
    DEX_SPLITTER_TRANSFORM = 38;
    MERGE_CLASSES_TRANSFORM = 39 [deprecated=true];
    LIBRARY_AAR_JARS_TRANSFORM = 40;
    LIBRARY_INTERMEDIATE_JARS = 41 [deprecated=true];
    TEST_TRANSFORM = 42 [deprecated=true];
    FIREBASE_TRANSFORM = 43;

    // Next IDs are for Artifact Transforms.
    DEX_ARTIFACT_TRANSFORM = 1000;
    EXTRACT_AAR_ARTIFACT_TRANSFORM = 1001;
    PLATFORM_ATTR_ARTIFACT_TRANSFORM = 1002;
    FILTER_SHRINKER_RULES_ARTIFACT_TRANSFORM = 1003;
    DEXING_OUTPUT_SPLIT_ARTIFACT_TRANSFORM = 1004;
    ASM_CLASSES_ARTIFACT_TRANSFORM = 1005;
    EXTRACT_JNI_ARTIFACT_TRANSFORM = 1006;
}

enum GradleTaskExecutionType {
    UNKNOWN_TASK_TYPE = 0;
    AIDL_COMPILE = 1;
    ANDROID_JAR = 2;
    ANDROID_JAVA_COMPILE = 3;
    ANDROID_REPORT = 4;
    ANDROID_UNIT_TEST = 5;
    BUILD_EMULATOR = 6;
    BUILD_INFO_LOADER = 7;
    CHECK_MANIFEST = 8;
    COMPATIBLE_SCREENS_MANIFEST = 9;
    CREATE_MANIFEST_KEEP_LIST = 10;
    DATA_BINDING_TRIGGER = 11;
    DATA_BINDING_PROCESS_LAYOUTS = 12;
    DEPENDENCY_REPORT = 13;
    DEVICE_PROVIDER_INSTRUMENT_TEST = 14;
    EXTERNAL_BUILD_ANCHOR = 15;
    EXTERNAL_NATIVE_BUILD_JSON = 16;
    EXTERNAL_NATIVE_BUILD = 17;
    EXTRACT_ANNOTATIONS = 18;
    EXTRACT_JAVA_RESOURCES = 19;
    EXTRACT_PROGUARD_FILES = 20;
    FAST_DEPLOY_RUNTIME_EXTRACTOR = 21;
    FILTERED_JAR_COPY = 22;
    GENERATE_APK_DATA = 23;
    GENERATE_BUILD_CONFIG = 24;
    GENERATE_INSTANT_RUN_APP_INFO = 25;
    GENERATE_RES_VALUES = 26;
    GENERATE_SPLIT_ABI_RES = 27;
    GOOGLE_SERVICES = 28;
    INCREMENTAL_SAFEGUARD = 29;
    INSTALL_VARIANT = 30;
    INSTANT_RUN_SPLIT_APK_BUILDER = 31;
    INSTANT_RUN_WRAPPER = 32;
    INVOKE_MANIFEST_MERGER = 33;
    JACK_JACOCO_REPORT = 34;
    JACOCO_REPORT = 35;
    LINT = 36;
    LINT_COMPILE = 37;
    MERGE_FILE = 38;
    PROCESS_APPLICATION_MANIFEST = 39;
    MERGE_RESOURCES = 40;
    MERGE_SOURCE_SET_FOLDERS = 41;
    MOCKABLE_ANDROID_JAR = 42;
    NDK_COMPILE = 43;
    NDK = 44;
    PACKAGE_APPLICATION = 45;
    PACKAGE_SPLIT_ABI = 46;
    PACKAGE_SPLIT_RES = 47;
    PRE_COLD_SWAP = 48;
    PREPARE_DEPENDENCIES = 49;
    PREPARE_LIBRARY = 50;
    PROCESS_ANDROID_RESOURCES = 51 [deprecated = true];
    PROCESS_LIBRARY_MANIFEST = 52;
    PROCESS_TEST_MANIFEST = 53;
    RENDERSCRIPT_COMPILE = 54;
    SHADER_COMPILE = 55;
    SIGNING_REPORT = 56;
    SINGLE_FILE_COPY = 57;
    SOURCE_SETS = 58;
    SPLIT_ZIP_ALIGN = 59;
    STREAM_BASED = 60;
    STRIP_DEBUG_SYMBOL__DEPRECATED = 61;
    STRIP_DEPENDENCIES = 62;
    TEST_MODULE_PRO_GUARD = 63;
    TEST_SERVER = 64;
    TRANSFORM = 65;
    UNINSTALL = 66;
    VALIDATE_SIGNING = 67;
    ZIP_ALIGN = 68;
    JAVA_COMPILE = 69;
    BUILD_INFO_WRITER = 70;
    BUNDLE_ATOM = 71;
    CHECK_MANIFEST_IN_INSTANT_RUN_MODE = 72;
    EXTERNAL_NATIVE_CLEAN = 73;
    GENERATE_ATOM_METADATA = 74;
    GENERATE_INSTANT_APP_METADATA = 75;
    JAVA_PRE_COMPILE = 76;
    MERGE_DEX_ATOM_RES_CLASS = 77;
    PACKAGE_ATOM = 78;
    PACKAGE_INSTANT_APP = 79;
    PREPARE_ATOM = 80;
    PROCESS_INSTANT_APP_RESOURCES = 81;
    CLEAN_BUILD_CACHE = 82 [deprecated = true];
    RESOLVE_DEPENDENCIES = 83;
    JAVA_COMPILE_ATOM_RES_CLASS = 84;
    PROCESS_ATOMS_RESOURCES = 85;
    EXTERNAL_NATIVE_PREPARE = 86;
    SPLITS_DISCOVERY = 87;
    ATOM_CONFIG = 88;
    BUNDLE_INSTANT_APP = 89;
    GENERATE_TEST_CONFIG = 90;
    COPY_OUTPUTS = 91;
    APP_PRE_BUILD = 92;
    TEST_PRE_BUILD = 93;
    COMPILE_ANDROID_RESOURCES = 94;
    LINK_ANDROID_RESOURCES = 95;
    GENERATE_R_CLASS = 96;
    FEATURE_SPLIT_DECLARATION_WRITER = 97;
    FEATURE_SPLIT_PACKAGE_IDS_WRITER = 98;
    EXTRACT_JAVA8_LANG_SUPPORT_JAR = 99;
    FEATURE_SPLIT_APPLICATION_ID_WRITER = 100;
    EXTRACT_TRY_WITH_RESOURCES_SUPPORT_JAR = 101;
    MODULE_METADATA_WRITER = 102;
    INSTANT_RUN_RESOURCES_APK_BUILDER = 103;
    DELETE = 104;
    CHECK_PROGUARD_FILES = 105;
    VERIFY_LIBRARY_RESOURCES = 106;
    CHECK_TESTED_APP_OBFUSCATION = 107;
    INSTANT_APP_PROVISION = 108;
    PLATFORM_ATTR_EXTRACTOR = 109;
    INSTANT_APP_SIDE_LOAD = 110;
    COMPILE_R_CLASS = 111;
    LINK_LIBRARY_ANDROID_RESOURCES = 112;
    PROCESS_ANDROID_APP_RESOURCES = 113;
    BUNDLE_ALL_CLASSES = 114;
    JAR_R_CLASS = 115;
    KOTLIN_COMPILE = 116;
    LINT_GLOBAL = 117;
    LINT_PER_VARIANT = 118;
    PREPARE_LINT_JAR = 119;
    LINT_STANDALONE = 120;
    LINK_APPLICATION_ANDROID_RESOURCES = 121;
    GENERATE_LIBRARY_R_FILE = 122;
    INSTANT_RUN_MAIN_APK_RESOURCES_BUILDER = 123;
    DATA_BINDING_GEN_BASE_CLASSES = 124;
    GENERATE_NAMESPACED_LIBRARY_R_FILES = 125;
    COMPILE_SOURCE_SET_RESOURCES = 126;
    MAIN_APK_LIST_PERSISTENCE = 127;
    BUILD_ARTIFACT_REPORT = 128;
    CHECK_INSTANT_APP_LIBRARIES = 129 [deprecated = true];
    STATIC_LIBRARY_MANIFEST = 130;
    DATA_BINDING_EXPORT_FEATURE_NAMESPACES = 131;
    DATA_BINDING_EXPORT_FEATURE_INFO = 132;
    AUTO_NAMESPACE_DEPENDENCIES = 133;
    PACKAGE_BUNDLE = 134;
    PER_MODULE_BUNDLE = 135;
    FEATURE_SET_METADATA_WRITER = 136;
    BUNDLE_TO_APK = 137;
    EXTRACT_APKS = 138;
    PREPARE_LINT_JAR_FOR_PUBLISH = 139;
    COMBINE_MODULE_INFO = 140;
    GATHER_ANDROID_MODULE_INFO = 141;
    GATHER_JAVA_MODULE_INFO = 142;
    LINT_FIX = 143;
    INSTALL_VARIANT_VIA_BUNDLE = 144;
    PACKAGE_FOR_UNIT_TEST = 145;
    KAPT = 146;
    KAPT_GENERATE_STUBS = 147;
    CHECK_MULTI_APK_LIBRARIES = 148;
    INSTANT_RUN_SPLIT_APK_RESOURCES_BUILDER = 149;
    ANDROID_ZIP = 150;
    PACKAGED_DEPENDENCIES_WRITER = 151;
    LINK_ANDROID_RES_FOR_BUNDLE = 152;
    ZIP_MERGING = 153;
    DATA_BINDING_MERGE_DEPENDENCY_ARTIFACTS = 154;
    BUNDLE_AAR = 155;
    APP_CLASSPATH_CHECK = 156;
    GATHER_MODULE_INFO = 157;
    APPLICATION_ID_WRITER = 158;
    KAPT_WITH_KOTLINC = 159;
    KAPT_WITHOUT_KOTLINC = 160;
    JACOCO = 161;
    BUNDLE_TO_STANDALONE_APK = 162;
    LEGACY_SHRINK_BUNDLE_MODULE_RESOURCES = 163;
    DEX_MERGING = 164;
    PACKAGE_RENDERSCRIPT = 165;
    PROCESS_JAVA_RES = 166;
    MERGE_CONSUMER_PROGUARD_FILES = 167;
    PROCESS_ANNOTATIONS = 168;
    SIGNING_CONFIG_WRITER = 169;
    LIBRARY_DEXING = 170;
    DATA_BINDING_MERGE_BASE_CLASS_LOG = 171;
    BUNDLE_LIBRARY_CLASSES = 172 [deprecated = true];
    BUNDLE_LIBRARY_JAVA_RES = 173;
    RECALCULATE_STACK_FRAMES = 174;
    FINALIZE_BUNDLE = 175;
    BUNDLE_REPORT_DEPENDENCIES = 176;
    PER_MODULE_REPORT_DEPENDENCIES = 177;
    CHECK_DUPLICATE_CLASSES = 178;
    CREATE_NON_NAMESPACED_LIBRARY_MANIFEST = 179;
    MERGE_JAVA_RESOURCE = 180;
    MERGE_NATIVE_LIBS = 181;
    PARSE_LIBRARY_RESOURCES = 182;
    GENERATE_LIBRARY_PROGUARD_RULES = 183;
    DEX_FILE_DEPENDENCIES = 184;
    D8_MAIN_DEX_LIST = 185;
    STRIP_DEBUG_SYMBOLS = 186;
    MERGE_CLASSES = 187;
    LIBRARY_JNI_LIBS = 188;
    EXTRACT_DEEP_LINKS = 189;
    ANALYZE_DEPENDENCIES = 190;
    ANDROID_VARIANT = 191;
    CLASSPATH_COMPARISON = 192;
    DEX_SPLITTER = 193;
    INCREMENTAL = 194;
    LIBRARY_AAR_JARS = 195;
    LINT_BASE = 196;
    MANIFEST_PROCESSOR = 197;
    NEW_INCREMENTAL = 198;
    NON_INCREMENTAL = 199;
    PACKAGE_ANDROID_ARTIFACT = 200;
    RESOURCE_AWARE = 201;
    SHRINK_RESOURCES_OLD_SHRINKER = 202;
    DEX_ARCHIVE_BUILDER = 203;
    DESUGAR = 204;
    PROGUARD_CONFIGURABLE = 205;
    COMPILE_LIBRARY_RESOURCES = 206;
    EXPORT_CONSUMER_PROGUARD_FILES = 207;
    APK_ZIP_PACKAGING = 208;
    R8 = 209;
    PARSE_INTEGRITY_CONFIG = 210;
    PROGUARD = 211;
    FEATURE_NAME_WRITER = 212;
    L8_DEX_DESUGAR_LIB = 213;
    PREPARE_KOTLIN_COMPILE = 214;
    ASSET_PACK_MANIFEST_GENERATION = 215;
    PROCESS_ASSET_PACK_MANIFEST = 216;
    LINK_MANIFEST_FOR_ASSET_PACK = 217;
    ASSET_PACK_PRE_BUNDLE = 218;
    SDK_DEPENDENCY_DATA_GENERATOR = 219;
    GENERATE_EMPTY_RESOURCE_FILES = 220;
    BUNDLE_LIBRARY_CLASSES_DIR = 221;
    BUNDLE_LIBRARY_CLASSES_JAR = 222;
    GENERATE_ML_MODEL_CLASS = 223;
    GENERATE_NAMESPACED_LIBRARY_SYMBOL_LIST_FILES = 224;
    OPTIMIZE_RESOURCES = 225;
    EXTRACT_NATIVE_DEBUG_METADATA = 226;
    MERGE_NATIVE_DEBUG_METADATA = 227;
    PROCESS_MANIFEST_FOR_BUNDLE = 228;
    PROCESS_MANIFEST_FOR_METADATA_FEATURE = 229;
    PROCESS_MANIFEST_FOR_INSTANT_APP = 230;
    UNSAFE_OUTPUTS = 231;
    PROCESS_PACKAGED_MANIFEST = 232;
    PROCESS_MULTI_APK_APPLICATION_MANIFEST = 233;
    ENUMERATE_CLASSES = 234 [deprecated = true];
    COMPRESS_ASSETS = 235;
    AAR_METADATA = 236;
    PREFAB_PACKAGE = 237;
    CHECK_AAR_METADATA = 238;
    GENERATE_MANIFEST_JAR = 239;
    SHRINK_APP_BUNDLE_RESOURCES = 240;
    BASE = 241;
    NON_INCREMENTAL_GLOBAL = 242;
    LINT_MODEL_DEPENDENCIES_WRITER = 243 [deprecated = true];
    LINT_MODEL_WRITER = 244;
    GENERATE_API_PUBLIC_TXT = 245;
    SHRINK_RESOURCES_NEW_SHRINKER = 246;
    EXTRACT_PROFILER_NATIVE_DEPENDENCIES = 247;
    TRANSFORM_CLASSES_WITH_ASM = 248;
    MANAGED_DEVICE_SETUP = 249;
    ANALYTICS_RECORDING = 250;
    APP_METADATA = 251;
    MANAGED_DEVICE_CLEAN = 252;
    SIGNING_CONFIG_VERSIONS_WRITER = 253;
    ANDROID_LINT = 254;
    ANDROID_LINT_GLOBAL = 255;
    BUNDLE_IDE_MODEL_PRODUCER = 256;
    MAP_SOURCE_SET_PATHS = 257;
    MANAGED_DEVICE_INSTRUMENTATION_TEST = 258;
    JACOCO_PROPERTIES = 259;
    ANDROID_LINT_COPY_REPORT = 260;
    DESUGAR_LIB_KEEP_RULES_MERGE = 261;
    D8_BUNDLE_MAIN_DEX_LIST = 262;
    FEATURE_DEX_MERGE = 263;
    ANDROID_LINT_ANALYSIS = 264;
    MERGE_R_FILES_FOR_DATA_BINDING = 265;
    DEVICE_SERIAL_TEST = 266;
    LINT_MODEL_METADATA = 267;
    MERGE_ART_PROFILE = 268;
    PROCESS_LIBRARY_ART_PROFILE = 269;
    COMPILE_ART_PROFILE = 270;
    ANDROID_LINT_TEXT_OUTPUT = 271;
    SOURCE_JAR = 272;
    MERGE_ASSETS_FOR_UNIT_TEST = 273;
    CHECK_JETIFIER = 274;
    JAVA_DOC_GENERATION = 275;
    JAVA_DOC_JAR = 276;
    LISTING_FILE_REDIRECT = 277;
    PREFAB_PACKAGE_CONFIGURATION = 278;
    APPLICATION_VARIANT_MODEL = 279;
    ABSTRACT_VARIANT_MODEL = 280;
    LIBRARY_VARIANT_MODEL = 281;
    DYNAMIC_FEATURE_VARIANT_MODEL = 282;
    ANDROID_TEST_VARIANT_MODEL = 283;
    TEST_VARIANT_MODEL = 284;
    UNIT_TEST_VARIANT_MODEL = 285;
    MODULE_VARIANT_MODEL = 286;
    TEST_MODULE_VARIANT_MODEL = 287;
}

enum BooleanOption {
    UNKNOWN_BOOLEAN_OPTION = 0;
    ENABLE_AAPT2 = 1;
    ENABLE_IN_PROCESS_AAPT2 = 2;
    ENABLE_DAEMON_MODE_AAPT2 = 3;
    ENABLE_BUILD_CACHE = 4 [deprecated=true];
    ENABLE_PROFILE_JSON = 5;
    ENABLE_SDK_DOWNLOAD = 6;
    ENABLE_TEST_SHARDING = 7;
    ENABLE_DEX_ARCHIVE = 8;
    ENABLE_NEW_RESOURCE_PROCESSING = 9;
    ENABLE_IMPROVED_DEPENDENCY_RESOLUTION = 10;
    ENABLE_INTERMEDIATE_ARTIFACTS_CACHE = 11;
    ENABLE_EXTRACT_ANNOTATIONS = 12;
    VERSION_CHECK_OVERRIDE_PROPERTY = 13;
    VERSION_CHECK_OVERRIDE_PROPERTY_OLD = 14;
    OVERRIDE_PATH_CHECK_PROPERTY = 15;
    OVERRIDE_PATH_CHECK_PROPERTY_OLD = 16;
    ENABLE_DESUGAR = 17;
    ENABLE_GRADLE_WORKERS = 18;
    DISABLE_RES_MERGE_IN_LIBRARY = 19;
    ENABLE_D8 = 20;
    ENABLE_DEPRECATED_NDK = 21;
    DISABLE_RESOURCE_VALIDATION = 22;
    BUILD_ONLY_TARGET_ABI = 23;
    KEEP_TIMESTAMPS_IN_APK = 24;
    IDE_INVOKED_FROM_IDE = 25;
    IDE_BUILD_MODEL_ONLY = 26;
    IDE_BUILD_MODEL_ONLY_ADVANCED = 27;
    IDE_BUILD_MODEL_FEATURE_FULL_DEPENDENCIES = 28;
    IDE_REFRESH_EXTERNAL_NATIVE_MODEL = 29;
    IDE_GENERATE_SOURCES_ONLY = 30;
    ENABLE_SEPARATE_APK_RESOURCES = 31;
    ENABLE_BUILDSCRIPT_CLASSPATH_CHECK = 32;
    ENABLE_EXPERIMENTAL_FEATURE_DATABINDING = 33;
    CONSUME_DEPENDENCIES_AS_SHARED_LIBRARIES = 34;
    ENABLE_NEW_DSL_AND_API = 35;
    ENABLE_D8_DESUGARING = 36;
    ENABLE_INCREMENTAL_DESUGARING = 37;
    ENABLE_SEPARATE_R_CLASS_COMPILATION = 38;
    ENABLE_D8_MAIN_DEX_LIST = 39;
    ENABLE_DATA_BINDING_V2 = 40;
    ENABLE_AAPT2_WORKER_ACTIONS = 41;
    ENABLE_CORE_LAMBDA_STUBS = 42;
    CONVERT_NON_NAMESPACED_DEPENDENCIES = 43;
    USE_AAPT2_FROM_MAVEN = 44;
    ENABLE_R8_DEPRECATED = 45 [deprecated=true];
    ENABLE_R8_DESUGARING = 46;
    ENABLE_DYNAMIC_APPS = 47;
    ENABLE_JETIFIER = 48;
    USE_ANDROID_X = 49;
    ENABLE_UNIT_TEST_BINARY_RESOURCES = 50;
    DISABLE_EARLY_MANIFEST_PARSING = 51;
    ENABLE_PARALLEL_NATIVE_JSON_GEN = 52;
    ENABLE_SIDE_BY_SIDE_CMAKE = 53;
    EXCLUDE_R_AND_MANIFEST_DOT_JAVA_FROM_GENERATED_SOURCES = 54;
    WARN_ABOUT_DEPENDENCY_RESOLUTION_AT_CONFIGURATION = 55;
    DISALLOW_DEPENDENCY_RESOLUTION_AT_CONFIGURATION = 56;
    DEPLOYMENT_USES_DIRECTORY = 57;
    DEPLOYMENT_PROVIDES_LIST_OF_CHANGES = 58;
    ENABLE_RESOURCE_NAMESPACING_DEFAULT = 59;
    ENABLE_PROGUARD_RULES_EXTRACTION = 60;
    INJECT_SDK_MAVEN_REPOS = 61;
    NAMESPACED_R_CLASS = 62 [deprecated=true];
    ENABLE_DEXING_ARTIFACT_TRANSFORM = 63;
    IDE_DEPLOY_AS_INSTANT_APP = 64;
    IDE_EXTRACT_INSTANT = 65;
    ENABLE_UNCOMPRESSED_NATIVE_LIBS_IN_BUNDLE = 66;
    USE_DEPENDENCY_CONSTRAINTS = 67;
    ENABLE_SEPARATE_ANNOTATION_PROCESSING = 68;
    DEBUG_OBSOLETE_API = 69;
    FULL_R8 = 70;
    ENABLE_NATIVE_COMPILER_SETTINGS_CACHE = 71;
    CONDITIONAL_KEEP_RULES = 72;
    ENABLE_R8_LIBRARIES = 73;
    ENABLE_DUPLICATE_CLASSES_CHECK = 74;
    ENFORCE_UNIQUE_PACKAGE_NAMES = 75;
    USE_RELATIVE_PATH_IN_TEST_CONFIG = 76;
    ENABLE_INCREMENTAL_DATA_BINDING = 77;
    ENABLE_STUDIO_VERSION_CHECK = 78;
    KEEP_SERVICES_BETWEEN_BUILDS = 79;
    USE_NON_FINAL_RES_IDS = 80;
    ENABLE_SIDE_BY_SIDE_NDK = 81;
    ENABLE_DEXING_DESUGARING_ARTIFACT_TRANSFORM = 82;
    PRECOMPILE_REMOTE_RESOURCES = 83 [deprecated = true];
    ENABLE_VIEW_BINDING = 84 [deprecated=true];
    GENERATE_R_JAVA = 85 [deprecated=true];
    ENABLE_CMAKE_BUILD_COHABITATION = 86;
    FORCE_JACOCO_OUT_OF_PROCESS = 87;
    USE_NEW_JAR_CREATOR = 88;
    USE_NEW_APK_CREATOR = 89;
    COMPILE_CLASSPATH_LIBRARY_R_CLASSES = 90;
    PRECOMPILE_LOCAL_RESOURCES = 91 [deprecated = true];
    ENABLE_ADDITIONAL_ANDROID_TEST_OUTPUT = 92;
    ENABLE_APP_COMPILE_TIME_R_CLASS = 93;
    MINIMAL_KEEP_RULES = 94;
    PRECOMPILE_DEPENDENCIES_RESOURCES = 95;
    EXCLUDE_RES_SOURCES_FOR_RELEASE_BUNDLES = 96;
    USE_SAFE_PROPERTIES = 97;
    BUILD_FEATURE_BUILDCONFIG = 98;
    BUILD_FEATURE_DATABINDING = 99;
    BUILD_FEATURE_VIEWBINDING = 100;
    BUILD_FEATURE_AIDL = 101;
    BUILD_FEATURE_RENDERSCRIPT = 102;
    BUILD_FEATURE_RESVALUES = 103;
    BUILD_FEATURE_SHADERS = 104;
    ENABLE_JVM_RESOURCE_COMPILER = 105;
    ENABLE_R_TXT_RESOURCE_SHRINKING = 106;
    ENABLE_PARTIAL_R_INCREMENTAL_BUILDS = 107;
    JETIFIER_SKIP_IF_POSSIBLE = 108;
    ENABLE_INCREMENTAL_DEXING_TASK_V2 = 109;
    ENABLE_PREFAB = 110;
    INCLUDE_DEPENDENCY_INFO_IN_APKS = 111;
    BUILD_FEATURE_ANDROID_RESOURCES = 112;
    ENABLE_DEXING_ARTIFACT_TRANSFORM_FOR_EXTERNAL_LIBS = 113;
    ENABLE_MLKIT = 114 [deprecated=true];
    DISABLE_MEMOIZATION = 115;
    ENABLE_RESOURCE_OPTIMIZATIONS = 116;
    BUILD_FEATURE_MLMODELBINDING = 117;
    NON_TRANSITIVE_R_CLASS = 118;
    ENABLE_LEGACY_API = 119;
    ANDROID_TEST_USES_UNIFIED_TEST_PLATFORM = 120;
    ENABLE_STABLE_IDS = 121;
    ENABLE_BUILD_CONFIG_AS_BYTECODE = 122;
    ANDROID_TEST_USES_RETENTION = 123 [deprecated=true];
    ENABLE_AAR_METADATA = 124;
    ENABLE_NEW_RESOURCE_SHRINKER = 125;
    NON_TRANSITIVE_APP_R_CLASS = 126;
    ENABLE_INCREMENTAL_DEXING_TRANSFORM = 127;
    GENERATE_MANIFEST_CLASS = 128;
    IDE_BUILD_MODEL_ONLY_V2 = 129;
    ENABLE_SYMBOL_TABLE_CACHING = 130;
    ENABLE_NEW_RESOURCE_SHRINKER_PRECISE = 131;
    USE_NEW_DSL_INTERFACES = 132;
    ENABLE_V2_NATIVE_MODEL = 133;
    PREFER_CMAKE_FILE_API = 134;
    USE_NEW_LINT_MODEL = 135;
    ENABLE_NATIVE_CONFIGURATION_FOLDING = 136;
    ENABLE_SOURCE_SET_PATHS_MAP = 137;
    ENABLE_LOCAL_TESTING = 138;
    ENABLE_DATABINDING_KTX = 139;
    RUN_LINT_IN_PROCESS = 140;
    USE_LINT_PARTIAL_ANALYSIS = 141;
    RELATIVE_COMPILE_LIB_RESOURCES = 142;
    R8_FAIL_ON_MISSING_CLASSES = 143;
    ENABLE_TEST_FIXTURES = 144;
    INCLUDE_REPOSITORIES_IN_DEPENDENCY_REPORT = 145;
    ENABLE_ART_PROFILES = 146;
    ENABLE_JACOCO_TRANSFORM_INSTRUMENTATION = 147;
    FORCE_DETERMINISTIC_APK = 148;
    DISABLE_MINSDKLIBRARY_CHECK = 149;
    UNINSTALL_INCOMPATIBLE_APKS = 150;
}

enum OptionalBooleanOption {
    UNKNOWN_OPTIONAL_BOOLEAN_OPTION = 0;
    SIGNING_V1_ENABLED = 1;
    SIGNING_V2_ENABLED = 2;
    IDE_TEST_ONLY = 3;
    SERIAL_AAPT2 = 4;
    ENABLE_R8 = 5;
    FIREBASE_PERF_PLUGIN_ENABLE_FLAG = 6;
    ENABLE_TEST_FAILURE_RETENTION_COMPRESS_SNAPSHOT = 7;
    INTERNAL_ONLY_ENABLE_R8 = 8;
    DISABLE_AUTOMATIC_COMPONENT_CREATION = 9;
}

enum IntegerOption {
    UNKNOWN_INTEGER_OPTION = 0;
    ANDROID_TEST_SHARD_COUNT = 1;
    ANDROID_SDK_CHANNEL = 2;
    THREAD_POOL_SIZE = 3;
    IDE_BUILD_MODEL_ONLY_VERSION = 4;
    IDE_TARGET_DEVICE_API = 5;
    IDE_VERSION_CODE_OVERRIDE = 6;
    DEXING_READ_BUFFER_SIZE = 7;
    DEXING_WRITE_BUFFER_SIZE = 8;
    DEXING_NUMBER_OF_BUCKETS = 9;
    PRE_O_MAX_NUMBER_OF_FEATURES = 10;
    AAPT2_THREAD_POOL_SIZE = 11;
    TEST_FAILURE_RETENTION = 12;
    MANAGED_DEVICE_SHARD_POOL_SIZE = 13;
}

enum LongOption {
    UNKNOWN_LONG_OPTION = 0;
    DEPRECATED_NDK_COMPILE_LEASE = 1;
}

enum StringOption {
    UNKNOWN_STRING_OPTION = 0;
    BUILD_CACHE_DIR = 1 [deprecated=true];
    IDE_BUILD_TARGET_DENSITY = 2;
    IDE_BUILD_TARGET_ABI = 3;
    IDE_RESTRICT_VARIANT_PROJECT = 4;
    IDE_RESTRICT_VARIANT_NAME = 5;
    IDE_SIGNING_STORE_TYPE = 6;
    IDE_SIGNING_STORE_FILE = 7;
    IDE_SIGNING_STORE_PASSWORD = 8;
    IDE_SIGNING_KEY_ALIAS = 9;
    IDE_SIGNING_KEY_PASSWORD = 10;
    IDE_APK_LOCATION = 11;
    IDE_OPTIONAL_COMPILATION_STEPS = 12;
    IDE_COLD_SWAP_MODE = 13;
    IDE_VERSION_NAME_OVERRIDE = 14;
    IDE_TARGET_DEVICE_CODENAME = 15;
    IDE_ANDROID_CUSTOM_CLASS_TRANSFORMS = 16;
    DEVICE_POOL_SERIAL = 17;
    PROFILE_OUTPUT_DIR = 18;
    BUILD_ARTIFACT_REPORT_FILE = 19;
    AAPT2_FROM_MAVEN_OVERRIDE = 20;
    IDE_APK_SELECT_CONFIG = 21;
    SUPPRESS_UNSUPPORTED_OPTION_WARNINGS = 22;
    IDE_ANDROID_STUDIO_VERSION = 23;
    JETIFIER_BLACKLIST = 24;
    IDE_ATTRIBUTION_FILE_LOCATION = 25;
    PREFAB_CLASSPATH = 26;
    PREFAB_VERSION = 27;
    IDE_INSTALL_DYNAMIC_MODULES_LIST = 28;
    JETIFIER_IGNORE_LIST = 29;
    NATIVE_BUILD_OUTPUT_LEVEL = 30;
    AAPT2_FROM_MAVEN_VERSION_OVERRIDE = 31;
    LINT_HEAP_SIZE = 32;
    SUPPRESS_UNSUPPORTED_COMPILE_SDK = 33;
    LINT_VERSION_OVERRIDE = 34;
    IDE_CHECK_JETIFIER_RESULT_FILE = 35;
    AAPT2_FROM_MAVEN_PLATFORM_OVERRIDE = 36;
    IDE_AGDE_VERSION = 37;
}

enum VariantApiArtifactType {
    CUSTOM_ARTIFACT_TYPE = 0;
    AAR = 1;
    APK = 2;
    BUNDLE = 3;
    LIBRARY_MANIFEST = 4;               // Deprecated
    MERGED_MANIFEST = 5;
    OBFUSCATION_MAPPING_FILE = 6;
    PUBLIC_ANDROID_RESOURCES_LIST = 7;
    ASSETS = 8;
}

enum VariantMethodType {
    UNKNOWN_METHOD_TYPE = 0;
    ENABLED = 1;
    MIN_SDK_VERSION_VALUE = 2;
    RENDERSCRIPT_TARGET_API = 3;
    MAX_SDK_VERSION_VALUE = 4;
    TARGET_SDK_VERSION_VALUE = 5;
    DEPENDENCIES_ACTION = 6;                        // deprecated
    REGISTER_EXTENSION = 7;
    UNIT_TEST_ENABLED = 8;
    ANDROID_TEST_ENABLED = 9;
    MIN_SDK_PREVIEW = 10;
    TARGET_SDK_PREVIEW = 11;
    VARIANT_BUILDER_DEPENDENCIES_INFO = 12;
    TEST_FIXTURES_ENABLED = 13;
}

enum VariantPropertiesMethodType {
    UNKNOWN_PROPERTIES_METHOD_TYPE = 0;
    ARTIFACTS = 1;
    ASM_TRANSFORM_CLASSES = 2;
    ASM_FRAMES_COMPUTATION_NODE = 3;
    BUILD_TYPE = 4;
    PRODUCT_FLAVORS = 5;
    FLAVOR_NAME = 6;
    READ_ONLY_APPLICATION_ID = 7;
    PACKAGE_NAME = 8 [deprecated=true];
    BUILD_CONFIG_FIELDS = 9;
    ADD_BUILD_CONFIG_FIELD = 10;                    // deprecated
    RES_VALUE = 11;
    ADD_RES_VALUE = 12;                             // deprecated
    MANIFEST_PLACEHOLDERS = 13;
    APPLICATION_ID = 14;
    AAPT_OPTIONS = 15;
    AAPT_OPTIONS_ACTION = 16;                       // deprecated
    TESTED_APPLICATION_ID = 17;
    INSTRUMENTATION_RUNNER = 18;
    HANDLE_PROFILING = 19;
    FUNCTIONAL_TEST = 20;
    TEST_LABEL = 21;
    GET_OUTPUTS = 22;
    DEPENDENCIES_INFO = 23;
    SIGNING_CONFIG = 24;
    SIGNING_CONFIG_ACTION = 25;                     // deprecated
    TESTED_VARIANT = 26;
    PACKAGING_OPTIONS = 27;
    PACKAGING_OPTIONS_ACTION = 28;                  // deprecated
    GET_BUILT_ARTIFACTS_LOADER = 29;
    GET_ARTIFACT = 30;
    GET_ALL_ARTIFACTS = 31;
    USE_TASK = 32;
    WIRED_WITH = 33;
    WIRED_WITH_FILES = 34;
    WIRED_WITH_LIST = 35;
    WIRED_WITH_DIRECTORIES = 36;
    TO_APPEND_TO = 37;
    TO_CREATE = 38;
    TO_TRANSFORM_FILE = 39;
    TO_TRANSFORM_COMBINE = 40;
    TO_TRANSFORM_DIRECTORY = 41;
    TO_TRANSFORM_MANY = 42;
    SUBMIT_TO_WORKERS = 43;
    JNI_LIBS_PACKAGING_OPTIONS = 44;
    JNI_LIBS_PACKAGING_OPTIONS_ACTION = 45;             // deprecated
    RESOURCES_PACKAGING_OPTIONS = 46;
    RESOURCES_PACKAGING_OPTIONS_ACTION = 47;            // deprecated
    DEX_PACKAGING_OPTIONS = 48;
    DEX_PACKAGING_OPTIONS_ACTION = 49;                  // deprecated
    CMAKE_NATIVE_OPTIONS = 50;
    CMAKE_OPTIONS_ABI_FILTERS = 51;
    CMAKE_OPTIONS_ARGUMENTS = 52;
    CMAKE_OPTIONS_C_FLAGS = 53;
    CMAKE_OPTIONS_CPP_FLAGS = 54;
    CMAKE_OPTIONS_TARGETS = 55;
    NDK_BUILD_NATIVE_OPTIONS = 56;
    NDK_BUILD_OPTIONS_ABI_FILTERS = 57;
    NDK_BUILD_OPTIONS_ARGUMENTS = 58;
    NDK_BUILD_OPTIONS_C_FLAGS = 59;
    NDK_BUILD_OPTIONS_CPP_FLAGS = 60;
    NDK_BUILD_OPTIONS_TARGETS = 61;
    NAMESPACE = 62;
    GET_EXTENSION = 63;
    DEXING = 64;
    DEXING_ACTION = 65;                                 // deprecated
    MULTI_DEX_KEEP_FILE = 66;
    MULTI_DEX_KEEP_PROGUARD = 67;
    RENDERSCRIPT = 68;
    RENDERSCRIPT_SUPPORT_MODE = 69;
    RENDERSCRIPT_SUPPORT_MODE_BLAS = 70;
    RENDERSCRIPT_NDK_MODE = 71;
    RENDERSCRIPT_OPTIMIZATION_LEVEL = 72;
    ANDROID_TEST = 73;
    VARIANT_AAR_METADATA = 74;
    VARIANT_AAR_METADATA_MIN_COMPILE_SDK = 75;
    SIGNING_CONFIG_ENABLE_V1 = 76;
    SIGNING_CONFIG_ENABLE_V2 = 77;
    SIGNING_CONFIG_ENABLE_V3 = 78;
    SIGNING_CONFIG_ENABLE_V4 = 79;
    VARIANT_PSEUDOLOCALES_ENABLED=80;
    PROGUARD_FILES = 81;
    MIN_SDK_VERSION = 82;
    MAX_SDK_VERSION = 83;
    TARGET_SDK_VERSION = 84;
    MAKE_RES_VALUE_KEY = 85;
    TEST_FIXTURES = 86;
    VARIANT_PROPERTIES = 87;
    SIGNING_CONFIG_SET_CONFIG = 88;
    GET_BUNDLE_CONFIG = 89;
    GET_CODE_TRANSPARENCY = 90;
    JAVA_COMPILATION_OPTIONS = 91;
    ANNOTATION_PROCESSOR = 92;
    ANNOTATION_PROCESSOR_CLASS_NAMES = 93;
    ANNOTATION_PROCESSOR_ARGUMENTS = 94;
    ANNOTATION_PROCESSOR_ARGUMENT_PROVIDERS = 95;
    NESTED_COMPONENTS = 96;
    VARIANT_AAR_METADATA_MIN_AGP_VERSION = 97;
}
