// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public final class AndroidStudioStats {
  private AndroidStudioStats() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_AndroidStudioEvent_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_AndroidStudioEvent_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_ProductDetails_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_ProductDetails_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_DeviceInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_DeviceInfo_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_StudioCrash_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_StudioCrash_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_EmulatorGuestGlInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_EmulatorGuestGlInfo_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_EmulatorGpuInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_EmulatorGpuInfo_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_EmulatorFeatures_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_EmulatorFeatures_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_EmulatorDetails_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_EmulatorDetails_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_EmulatorUiEvent_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_EmulatorUiEvent_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleBuildDetails_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleBuildDetails_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleLibrary_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleLibrary_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleModule_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleModule_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleAndroidModule_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleAndroidModule_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleNativeAndroidModule_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleNativeAndroidModule_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_InstantRun_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_InstantRun_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_MetaMetrics_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_MetaMetrics_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_TestRun_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_TestRun_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_TestLibraries_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_TestLibraries_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_Hypervisor_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_Hypervisor_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_EmulatorHost_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_EmulatorHost_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleBuildProfile_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleBuildProfile_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleBuildProject_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleBuildProject_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleBuildProjectMetrics_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleBuildProjectMetrics_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleBuildVariant_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleBuildVariant_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleBuildMemorySample_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleBuildMemorySample_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleBuildProfileSpan_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleBuildProfileSpan_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleTaskExecution_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleTaskExecution_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GradleTransformExecution_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GradleTransformExecution_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_InstantRunStatus_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_InstantRunStatus_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_InstantRunArtifact_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_InstantRunArtifact_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_LLDBFrontendDetails_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_LLDBFrontendDetails_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_FirebaseErrorDetails_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_FirebaseErrorDetails_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GfxTracingDetails_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GfxTracingDetails_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_TestRecorderDetails_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_TestRecorderDetails_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_UIActionStats_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_UIActionStats_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_MachineDetails_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_MachineDetails_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_DisplayDetails_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_DisplayDetails_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_JavaProcessStats_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_JavaProcessStats_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_GarbageCollectionStats_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_GarbageCollectionStats_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_JvmDetails_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_JvmDetails_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_StudioPerformanceStats_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_StudioPerformanceStats_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_PercentileBucket_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_PercentileBucket_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_PercentileEstimator_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_PercentileEstimator_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_LldbPercentileEstimator_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_LldbPercentileEstimator_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_LldbPerformanceStats_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_LldbPerformanceStats_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_studio_StudioProjectChange_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_studio_StudioProjectChange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022studio_stats.proto\022\016android_studio\"\365=\n" +
      "\022AndroidStudioEvent\022B\n\010category\030\001 \001(\01620." +
      "android_studio.AndroidStudioEvent.EventC" +
      "ategory\022:\n\004kind\030\002 \001(\0162,.android_studio.A" +
      "ndroidStudioEvent.EventKind\022\031\n\021studio_se" +
      "ssion_id\030\003 \001(\t\0227\n\017product_details\030\004 \001(\0132" +
      "\036.android_studio.ProductDetails\022D\n\014monit" +
      "or_type\030\005 \001(\0162..android_studio.AndroidSt" +
      "udioEvent.MonitorType\022\026\n\016monitor_paused\030" +
      "\006 \001(\010\022U\n\025profiler_capture_type\030\007 \001(\01626.a",
      "ndroid_studio.AndroidStudioEvent.Profile" +
      "rCaptureType\022#\n\033cloud_testing_error_mess" +
      "age\030\010 \001(\t\022.\n&cloud_testing_loaded_screen" +
      "shots_count\030\t \001(\005\022W\n\026run_configuration_t" +
      "ype\030\n \001(\01627.android_studio.AndroidStudio" +
      "Event.RunConfigurationType\022F\n\rdebugger_t" +
      "ype\030\013 \001(\0162/.android_studio.AndroidStudio" +
      "Event.DebuggerType\022/\n\013device_info\030\014 \001(\0132" +
      "\032.android_studio.DeviceInfo\022$\n\034lldb_sess" +
      "ion_failure_message\030\r \001(\t\022W\n\026developer_s",
      "ervice_kind\030\016 \001(\01627.android_studio.Andro" +
      "idStudioEvent.DeveloperServiceKind\022\026\n\016gr" +
      "adle_version\030\017 \001(\t\022Q\n\023gradle_sync_failur" +
      "e\030\020 \001(\01624.android_studio.AndroidStudioEv" +
      "ent.GradleSyncFailure\022 \n\030gradle_missing_" +
      "signature\030\021 \001(\t\022N\n\021template_renderer\030\022 \001" +
      "(\01623.android_studio.AndroidStudioEvent.T" +
      "emplateRenderer\0221\n\014studio_crash\030\023 \001(\0132\033." +
      "android_studio.StudioCrash\022@\n\024gradle_bui" +
      "ld_details\030\024 \001(\0132\".android_studio.Gradle",
      "BuildDetails\022/\n\013instant_run\030\025 \001(\0132\032.andr" +
      "oid_studio.InstantRun\0221\n\014meta_metrics\030\026 " +
      "\001(\0132\033.android_studio.MetaMetrics\0229\n\020emul" +
      "ator_details\030\027 \001(\0132\037.android_studio.Emul" +
      "atorDetails\022)\n\010test_run\030\030 \001(\0132\027.android_" +
      "studio.TestRun\022:\n\021emulator_ui_event\030\031 \001(" +
      "\0132\037.android_studio.EmulatorUiEvent\022.\n\nhy" +
      "pervisor\030\032 \001(\0132\032.android_studio.Hypervis" +
      "or\0223\n\remulator_host\030\033 \001(\0132\034.android_stud" +
      "io.EmulatorHost\022@\n\024gradle_build_profile\030",
      "\034 \001(\0132\".android_studio.GradleBuildProfil" +
      "e\022B\n\025lldb_frontend_details\030\035 \001(\0132#.andro" +
      "id_studio.LLDBFrontendDetails\022D\n\026firebas" +
      "e_error_details\030\036 \001(\0132$.android_studio.F" +
      "irebaseErrorDetails\022\022\n\nproject_id\030\037 \001(\t\022" +
      ">\n\023gfx_tracing_details\030  \001(\0132!.android_s" +
      "tudio.GfxTracingDetails\022B\n\025test_recorder" +
      "_details\030! \001(\0132#.android_studio.TestReco" +
      "rderDetails\0226\n\017ui_action_stats\030\" \001(\0132\035.a" +
      "ndroid_studio.UIActionStats\0227\n\017machine_d",
      "etails\030# \001(\0132\036.android_studio.MachineDet" +
      "ails\022/\n\013jvm_details\030$ \001(\0132\032.android_stud" +
      "io.JvmDetails\022<\n\022java_process_stats\030% \001(" +
      "\0132 .android_studio.JavaProcessStats\022H\n\030s" +
      "tudio_performance_stats\030& \001(\0132&.android_" +
      "studio.StudioPerformanceStats\022D\n\026lldb_pe" +
      "rformance_stats\030\' \001(\0132$.android_studio.L" +
      "ldbPerformanceStats\022B\n\025studio_project_ch" +
      "ange\030( \001(\0132#.android_studio.StudioProjec" +
      "tChange\"\237\003\n\rEventCategory\022\025\n\021NO_EVENT_CA",
      "TEGORY\020\000\022\016\n\nDEPLOYMENT\020\001\022\020\n\014STUDIO_BUILD" +
      "\020\002\022\026\n\022DEVELOPER_SERVICES\020\003\022\017\n\013GRADLE_SYN" +
      "C\020\004\022\r\n\tPROFILING\020\005\022\013\n\007MONITOR\020\006\022\017\n\013SDK_M" +
      "ANAGER\020\007\022\014\n\010TEMPLATE\020\010\022\020\n\014THEME_EDITOR\020\t" +
      "\022\020\n\014APP_INDEXING\020\n\022\010\n\004LLDB\020\013\022\021\n\rCLOUD_TE" +
      "STING\020\014\022\010\n\004PING\020\r\022\t\n\005TESTS\020\016\022\010\n\004META\020\017\022\017" +
      "\n\013EMULATOR_UI\020\020\022\n\n\006SYSTEM\020\021\022\034\n\030PROJECT_S" +
      "TRUCTURE_DIALOG\020\022\022\n\n\006GRADLE\020\023\022\026\n\022FIREBAS" +
      "E_ASSISTANT\020\024\022\020\n\014GPU_PROFILER\020\025\022\021\n\rTEST_" +
      "RECORDER\020\026\022\r\n\tSTUDIO_UI\020\027\"\367\030\n\tEventKind\022",
      "\026\n\022UNKNOWN_EVENT_KIND\020\000\022\022\n\016DEPLOYMENT_AP" +
      "K\020\001\022\032\n\026DEPLOYMENT_TO_EMULATOR\020\002\022 \n\034DEVEL" +
      "OPER_SERVICES_INSTALLED\020\003\022\036\n\032DEVELOPER_S" +
      "ERVICES_REMOVED\020\004\022\027\n\023GRADLE_SYNC_STARTED" +
      "\020\005\022\025\n\021GRADLE_SYNC_ENDED\020\006\022\027\n\023GRADLE_SYNC" +
      "_SKIPPED\020\007\022\027\n\023GRADLE_SYNC_FAILURE\020\010\022\035\n\031G" +
      "RADLE_CPP_SYNC_COMPLETED\020\t\022\025\n\021PROFILING_" +
      "CAPTURE\020\n\022\022\n\016PROFILING_OPEN\020\013\022\033\n\027PROFILI" +
      "NG_CONVERT_HPROF\020\014\022\032\n\026PROFILING_ANALYSIS" +
      "_RUN\020\r\022\025\n\021MONITOR_ACTIVATED\020\016\022\023\n\017MONITOR",
      "_RUNNING\020\017\022\037\n\033SDK_MANAGER_TOOLBAR_CLICKE" +
      "D\020\020\022#\n\037SDK_MANAGER_STANDALONE_LAUNCHED\020\021" +
      "\022\026\n\022SDK_MANAGER_LOADED\020\022\022\023\n\017TEMPLATE_REN" +
      "DER\020\023\022\025\n\021THEME_EDITOR_OPEN\020\024\022\"\n\036APP_INDE" +
      "XING_DEEP_LINK_CREATED\020\025\022!\n\035APP_INDEXING" +
      "_API_CODE_CREATED\020\026\022#\n\037APP_INDEXING_DEEP" +
      "_LINK_LAUNCHED\020\027\022!\n\035APP_INDEXING_TRIGGER" +
      "_QUICKFIX\020\030\022!\n\035APP_INDEXING_SHOW_FEAG_DI" +
      "ALOG\020\031\022 \n\034APP_INDEXING_START_FEAG_TASK\020\032" +
      "\022\021\n\rLLDB_LAUNCHED\020\033\022\030\n\024LLDB_SESSION_STAR",
      "TED\020\034\022\027\n\023LLDB_SESSION_FAILED\020\035\022\032\n\026LLDB_S" +
      "ESSION_COMPLETED\020\036\022\030\n\024LLDB_INSTALL_START" +
      "ED\020\037\022\027\n\023LLDB_INSTALL_FAILED\020 \022\032\n\026LLDB_IN" +
      "STALL_COMPLETED\020!\022!\n\035LLDB_SESSION_USED_W" +
      "ATCHPOINTS\020\"\022(\n$CLOUD_TESTING_CONFIGURE_" +
      "CLOUD_DEVICE\020#\022\"\n\036CLOUD_TESTING_CONFIGUR" +
      "E_MATRIX\020$\022%\n!CLOUD_TESTING_LAUNCH_CLOUD" +
      "_DEVICE\020%\022!\n\035CLOUD_TESTING_RUN_TEST_MATR" +
      "IX\020&\022\037\n\033CLOUD_TESTING_BACKEND_ERROR\020\'\022$\n" +
      " CLOUD_TESTING_DEBUG_FROM_RESULTS\020(\022,\n(C",
      "LOUD_TESTING_COMPARE_SCREENSHOTS_OPENED\020" +
      ")\022\020\n\014STUDIO_CRASH\020*\022\030\n\024GRADLE_BUILD_DETA" +
      "ILS\020,\022\017\n\013INSTANT_RUN\020-\022\017\n\013STUDIO_PING\020.\022" +
      "\021\n\rEMULATOR_PING\020/\022\020\n\014META_METRICS\0200\022\014\n\010" +
      "TEST_RUN\0202\022\025\n\021EMULATOR_UI_EVENT\0203\022\016\n\nHYP" +
      "ERVISOR\0204\022\021\n\rEMULATOR_HOST\0205\022!\n\035PROJECT_" +
      "STRUCTURE_DIALOG_OPEN\0206\022!\n\035PROJECT_STRUC" +
      "TURE_DIALOG_SAVE\0207\022*\n&PROJECT_STRUCTURE_" +
      "DIALOG_TOP_TAB_CLICK\0208\022)\n%PROJECT_STRUCT" +
      "URE_DIALOG_TOP_TAB_SAVE\0209\022+\n\'PROJECT_STR",
      "UCTURE_DIALOG_LEFT_NAV_CLICK\020:\022*\n&PROJEC" +
      "T_STRUCTURE_DIALOG_LEFT_NAV_SAVE\020;\022\030\n\024GR" +
      "ADLE_BUILD_PROFILE\020<\022\030\n\024LLDB_FRONTEND_EX" +
      "ITED\020=\022&\n\"FIREBASE_ASSISTANT_PROJECT_CRE" +
      "ATED\020>\022,\n(FIREBASE_ASSISTANT_PROJECT_CRE" +
      "ATE_FAILED\020?\022\'\n#FIREBASE_ASSISTANT_PROJE" +
      "CT_UPGRADED\020@\022-\n)FIREBASE_ASSISTANT_PROJ" +
      "ECT_UPGRADE_FAILED\020B\0223\n/FIREBASE_ASSISTA" +
      "NT_PROJECT_CONFIG_CREATE_FAILED\020C\022&\n\"FIR" +
      "EBASE_ASSISTANT_PROJECT_UPDATED\020D\022,\n(FIR",
      "EBASE_ASSISTANT_PROJECT_UPDATE_FAILED\020E\022" +
      "2\n.FIREBASE_ASSISTANT_PROJECT_CONFIG_WRI" +
      "TE_FAILED\020F\022!\n\035FIREBASE_ASSISTANT_TOS_FA" +
      "ILED\020G\022$\n FIREBASE_ASSISTANT_ATTEMPT_LOG" +
      "IN\020H\022$\n FIREBASE_ASSISTANT_LOGIN_SUCCESS" +
      "\020I\022,\n(FIREBASE_ASSISTANT_RECONNECT_DIALO" +
      "G_SYNC\020J\022(\n$FIREBASE_ASSISTANT_CONNECT_R" +
      "EQUESTED\020K\022\033\n\027FIREBASE_ASSISTANT_OPEN\020L\022" +
      ",\n(FIREBASE_ASSISTANT_CONNECT_DIALOG_OPE" +
      "NED\020M\022*\n&FIREBASE_ASSISTANT_CONNECT_DIAL",
      "OG_SYNC\020N\022&\n\"FIREBASE_ASSISTANT_ERROR_PR" +
      "ESENTED\020O\022#\n\037FIREBASE_ASSISTANT_SILENT_E" +
      "RROR\020P\022.\n*FIREBASE_ASSISTANT_RECONNECT_D" +
      "IALOG_OPENED\020Q\022\030\n\024GFX_TRACE_INIT_ERROR\020R" +
      "\022\024\n\020GFX_TRACE_CLOSED\020S\022\036\n\032GFX_TRACE_PARA" +
      "METER_EDITED\020T\022\033\n\027GFX_TRACE_TRACE_STARTE" +
      "D\020U\022\033\n\027GFX_TRACE_TRACE_STOPPED\020V\022\036\n\032GFX_" +
      "TRACE_COMMAND_SELECTED\020W\022\032\n\026GFX_TRACE_LI" +
      "NK_CLICKED\020X\022\033\n\027GFX_TRACE_MEMORY_VIEWED\020" +
      "Y\022\034\n\030GFX_TRACE_TEXTURE_VIEWED\020Z\022\037\n\033LEGAC",
      "Y_IDEA_ANDROID_PROJECT\020[\022%\n!TEST_RECORDE" +
      "R_GENERATE_TEST_CLASS\020\\\022/\n+TEST_RECORDER" +
      "_MISSING_ESPRESSO_DEPENDENCIES\020]\0225\n1TEST" +
      "_RECORDER_MISSING_INSTRUMENTATION_TEST_F" +
      "OLDER\020^\022\030\n\024TEST_RECORDER_LAUNCH\020_\022\022\n\016GFX" +
      "_TRACE_OPEN\020`\022\032\n\026STUDIO_UI_ACTION_STATS\020" +
      "a\022\030\n\024STUDIO_PROCESS_STATS\020b\022\034\n\030STUDIO_PE" +
      "RFORMANCE_STATS\020c\022\032\n\026LLDB_PERFORMANCE_ST" +
      "ATS\020d\022\031\n\025STUDIO_PROJECT_OPENED\020e\022\031\n\025STUD" +
      "IO_PROJECT_CLOSED\020f\"R\n\013MonitorType\022\030\n\024UN",
      "KNOWN_MONITOR_TYPE\020\000\022\007\n\003CPU\020\001\022\007\n\003GPU\020\002\022\n" +
      "\n\006MEMORY\020\003\022\013\n\007NETWORK\020\004\"\321\001\n\023ProfilerCapt" +
      "ureType\022!\n\035UNKNOWN_PROFILER_CAPTURE_TYPE" +
      "\020\000\022\016\n\nALLOCATION\020\001\022\010\n\004FILE\020\002\022\r\n\tGFX_TRAC" +
      "E\020\003\022\010\n\004HEAP\020\004\022\017\n\013SYSTEM_INFO\020\005\022\014\n\010VM_TRA" +
      "CE\020\006\022\022\n\016METHOD_TRACING\020\007\022\035\n\031LAYOUT_INSPE" +
      "CTOR_SNAPSHOT\020\010\022\022\n\016HIERARCHY_VIEW\020\t\"m\n\024R" +
      "unConfigurationType\022\"\n\036UNKNOWN_RUN_CONFI" +
      "GURATION_TYPE\020\000\022\013\n\007ANDROID\020\001\022\022\n\016ANDROID_" +
      "NATIVE\020\002\022\020\n\014ANDROID_TEST\020\003\"K\n\014DebuggerTy",
      "pe\022\031\n\025UNKNOWN_DEBUGGER_TYPE\020\000\022\010\n\004JAVA\020\001\022" +
      "\n\n\006HYBRID\020\002\022\n\n\006NATIVE\020\003\"\261\002\n\024DeveloperSer" +
      "viceKind\022\"\n\036UNKNOWN_DEVELOPER_SERVICE_KI" +
      "ND\020\000\022\032\n\026GOOGLE_CLOUD_MESSAGING\020\001\022\n\n\006AD_M" +
      "OB\020\002\022\022\n\016GOOGLE_SIGN_IN\020\003\022\024\n\020GOOGLE_ANALY" +
      "TICS\020\004\022\014\n\010FIREBASE\020\005\022\025\n\021REALTIME_DATABAS" +
      "E\020\006\022\022\n\016AUTHENTICATION\020\007\022\023\n\017CRASH_REPORTI" +
      "NG\020\010\022\021\n\rNOTIFICATIONS\020\t\022\021\n\rREMOTE_CONFIG" +
      "\020\n\022\013\n\007STORAGE\020\013\022\017\n\013APP_INVITES\020\014\022\021\n\rDYNA" +
      "MIC_LINKS\020\r\"\247\006\n\020TemplateRenderer\022\035\n\031UNKN",
      "OWN_TEMPLATE_RENDERER\020\000\022\034\n\030CUSTOM_TEMPLA" +
      "TE_RENDERER\020\001\022\022\n\016ANDROID_MODULE\020\002\022\023\n\017AND" +
      "ROID_PROJECT\020\003\022\022\n\016EMPTY_ACTIVITY\020\004\022\022\n\016BL" +
      "ANK_ACTIVITY\020\005\022\023\n\017LAYOUT_XML_FILE\020\006\022\022\n\016F" +
      "RAGMENT_BLANK\020\007\022\036\n\032NAVIGATION_DRAWER_ACT" +
      "IVITY\020\010\022\023\n\017VALUES_XML_FILE\020\t\022\030\n\024GOOGLE_M" +
      "APS_ACTIVITY\020\n\022\022\n\016LOGIN_ACTIVITY\020\013\022\021\n\rAS" +
      "SETS_FOLDER\020\014\022\023\n\017TABBED_ACTIVITY\020\r\022\026\n\022SC" +
      "ROLLING_ACTIVITY\020\016\022\027\n\023FULLSCREEN_ACTIVIT" +
      "Y\020\017\022\013\n\007SERVICE\020\020\022\020\n\014JAVA_LIBRARY\020\021\022\025\n\021SE",
      "TTINGS_ACTIVITY\020\022\022\021\n\rFRAGMENT_LIST\020\023\022\026\n\022" +
      "MASTER_DETAIL_FLOW\020\024\022\027\n\023ANDROID_WEAR_MOD" +
      "ULE\020\025\022\026\n\022BROADCAST_RECEIVER\020\026\022\r\n\tAIDL_FI" +
      "LE\020\027\022\022\n\016INTENT_SERVICE\020\030\022\016\n\nJNI_FOLDER\020\031" +
      "\022\017\n\013JAVA_FOLDER\020\032\022\017\n\013CUSTOM_VIEW\020\033\022\025\n\021AN" +
      "DROID_TV_MODULE\020\034\022\036\n\032GOOGLE_ADMOBS_ADS_A" +
      "CTIVITY\020\035\022\033\n\027ALWAYS_ON_WEAR_ACTIVITY\020\036\022\016" +
      "\n\nRES_FOLDER\020\037\022\027\n\023ANDROID_TV_ACTIVITY\020 \022" +
      "\027\n\023BLANK_WEAR_ACTIVITY\020!\022\023\n\017BASIC_ACTIVI" +
      "TIY\020\"\022\016\n\nAPP_WIDGET\020#\"\374\002\n\021GradleSyncFail",
      "ure\022\032\n\026UNKNOWN_GRADLE_FAILURE\020\000\022\025\n\021CONNE" +
      "CTION_DENIED\020\001\022\023\n\017CLASS_NOT_FOUND\020\002\022\030\n\024D" +
      "SL_METHOD_NOT_FOUND\020\003\022\027\n\023FAILED_TO_PARSE" +
      "_SDK\020\004\022\024\n\020METHOD_NOT_FOUND\020\005\022\034\n\030MISSING_" +
      "ANDROID_PLATFORM\020\006\022 \n\034MISSING_ANDROID_SU" +
      "PPORT_REPO\020\007\022\027\n\023MISSING_BUILD_TOOLS\020\010\022\021\n" +
      "\rOUT_OF_MEMORY\020\t\022\021\n\rSDK_NOT_FOUND\020\n\022\020\n\014U" +
      "NKNOWN_HOST\020\013\022%\n!UNSUPPORTED_ANDROID_MOD" +
      "EL_VERSION\020\014\022\036\n\032UNSUPPORTED_GRADLE_VERSI" +
      "ON\020\r\"\362\004\n\016ProductDetails\022;\n\007product\030\001 \001(\016",
      "2*.android_studio.ProductDetails.Product" +
      "Kind\022\r\n\005build\030\002 \001(\t\022\017\n\007version\030\003 \001(\t\022\017\n\007" +
      "preview\030\004 \001(\010\022G\n\017os_architecture\030\005 \001(\0162." +
      ".android_studio.ProductDetails.CpuArchit" +
      "ecture\022H\n\007channel\030\006 \001(\01627.android_studio" +
      ".ProductDetails.SoftwareLifeCycleChannel" +
      "\"e\n\030SoftwareLifeCycleChannel\022\036\n\032UNKNOWN_" +
      "LIFE_CYCLE_CHANNEL\020\000\022\n\n\006CANARY\020\001\022\007\n\003DEV\020" +
      "\002\022\010\n\004BETA\020\003\022\n\n\006STABLE\020\004\"R\n\013ProductKind\022\023" +
      "\n\017UNKNOWN_PRODUCT\020\000\022\n\n\006STUDIO\020\001\022\014\n\010EMULA",
      "TOR\020\002\022\n\n\006GRADLE\020\003\022\010\n\004DDMS\020\004\"^\n\006OSKind\022\023\n" +
      "\017UNKNOWN_OS_KIND\020\000\022\014\n\010OTHER_OS\020\001\022\013\n\007WIND" +
      "OWS\020\002\022\013\n\007MAC_OSX\020\003\022\t\n\005LINUX\020\004\022\014\n\010FREE_BS" +
      "D\020\005\"D\n\017CpuArchitecture\022\034\n\030UNKNOWN_CPU_AR" +
      "CHITECTURE\020\000\022\007\n\003X86\020\001\022\n\n\006X86_64\020\002\"\217\005\n\nDe" +
      "viceInfo\022 \n\030anonymized_serial_number\030\001 \001" +
      "(\t\022\022\n\nbuild_tags\030\002 \001(\t\022\022\n\nbuild_type\030\003 \001" +
      "(\t\022\035\n\025build_version_release\030\004 \001(\t\022\027\n\017bui" +
      "ld_api_level\030\005 \001(\005\022F\n\007cpu_abi\030\006 \001(\01625.an" +
      "droid_studio.DeviceInfo.ApplicationBinar",
      "yInterface\022\024\n\014manufacturer\030\007 \001(\t\022\r\n\005mode" +
      "l\030\010 \001(\t\022:\n\013device_type\030\t \001(\0162%.android_s" +
      "tudio.DeviceInfo.DeviceType\022\034\n\024build_api" +
      "_level_full\030\n \001(\t\"\300\001\n\032ApplicationBinaryI" +
      "nterface\022\017\n\013UNKNOWN_ABI\020\000\022\020\n\014ARME_ABI_V7" +
      "A\020\001\022\013\n\007X86_ABI\020\002\022\021\n\rARM64_V8A_ABI\020\003\022\016\n\nX" +
      "86_64_ABI\020\004\022\014\n\010ARME_ABI\020\005\022\014\n\010MIPS_ABI\020\006\022" +
      "\017\n\013MIPS_R2_ABI\020\007\022\020\n\014ARME_ABI_V6L\020\010\022\020\n\014AR" +
      "ME_ABI_V6J\020\t\"u\n\nDeviceType\022\027\n\023UNKNOWN_DE" +
      "VICE_TYPE\020\000\022\022\n\016LOCAL_PHYSICAL\020\001\022\022\n\016LOCAL",
      "_EMULATOR\020\002\022\022\n\016CLOUD_EMULATOR\020\003\022\022\n\016CLOUD" +
      "_PHYSICAL\020\004\"\215\001\n\013StudioCrash\022\017\n\007actions\030\001" +
      " \001(\003\022\022\n\nexceptions\030\002 \001(\003\022\017\n\007crashes\030\003 \001(" +
      "\003\022!\n\031bundled_plugin_exceptions\030\004 \001(\003\022%\n\035" +
      "non_bundled_plugin_exceptions\030\005 \001(\003\"H\n\023E" +
      "mulatorGuestGlInfo\022\016\n\006vendor\030\001 \001(\t\022\020\n\010re" +
      "nderer\030\002 \001(\t\022\017\n\007version\030\003 \001(\t\"y\n\017Emulato" +
      "rGpuInfo\022\014\n\004make\030\001 \001(\t\022\r\n\005model\030\002 \001(\t\022\021\n" +
      "\tdevice_id\030\003 \001(\t\022\023\n\013revision_id\030\004 \001(\t\022\017\n" +
      "\007version\030\005 \001(\t\022\020\n\010renderer\030\006 \001(\t\"0\n\020Emul",
      "atorFeatures\022\013\n\003gps\030\001 \001(\010\022\017\n\007sensors\030\002 \001" +
      "(\010\"\201\n\n\017EmulatorDetails\022H\n\nguest_arch\030\001 \001" +
      "(\01624.android_studio.EmulatorDetails.Gues" +
      "tCpuArchitecture\022\023\n\013system_time\030\002 \001(\003\022\021\n" +
      "\tuser_time\030\003 \001(\003\022\017\n\007crashes\030\004 \001(\003\022\021\n\twal" +
      "l_time\030\005 \001(\003\022\024\n\014exit_started\030\006 \001(\010\022\027\n\017gu" +
      "est_api_level\030\007 \001(\003\022\031\n\021guest_gpu_enabled" +
      "\030\010 \001(\010\022\027\n\017is_opengl_alive\030\n \001(\010\022I\n\014adb_l" +
      "iveness\030\013 \001(\01623.android_studio.EmulatorD" +
      "etails.EmulatorAdbLiveness\0225\n\010guest_gl\030\014",
      " \001(\0132#.android_studio.EmulatorGuestGlInf" +
      "o\0221\n\010host_gpu\030\r \003(\0132\037.android_studio.Emu" +
      "latorGpuInfo\022K\n\rsession_phase\030\016 \001(\01624.an" +
      "droid_studio.EmulatorDetails.EmulatorSes" +
      "sionPhase\022\024\n\014core_version\030\017 \001(\t\022B\n\010rende" +
      "rer\030\020 \001(\01620.android_studio.EmulatorDetai" +
      "ls.EmulatorRenderer\0227\n\rused_features\030\021 \001" +
      "(\0132 .android_studio.EmulatorFeatures\"\224\001\n" +
      "\023EmulatorAdbLiveness\022!\n\035UNKNOWN_EMULATOR" +
      "_ADB_LIVENESS\020\000\022\022\n\016FAILURE_NO_ADB\020\001\022\016\n\nA",
      "DB_ONLINE\020\002\022\033\n\027FAILURE_ADB_SERVER_DEAD\020\003" +
      "\022\031\n\025FAILURE_EMULATOR_DEAD\020\004\"\262\001\n\024Emulator" +
      "SessionPhase\022\"\n\036UNKNOWN_EMULATOR_SESSION" +
      "_PHASE\020\000\022\014\n\010LAUNCHER\020\001\022\021\n\rPARSE_OPTIONS\020" +
      "\002\022\020\n\014INIT_GENERAL\020\003\022\014\n\010INIT_GPU\020\004\022\016\n\nINI" +
      "T_ACCEL\020\005\022\023\n\017RUNNING_GENERAL\020\006\022\020\n\014EXIT_G" +
      "ENERAL\020\007\"{\n\024GuestCpuArchitecture\022\"\n\036UNKN" +
      "OWN_GUEST_CPU_ARCHITECTURE\020\000\022\007\n\003X86\020\001\022\n\n" +
      "\006X86_64\020\002\022\007\n\003ARM\020\003\022\n\n\006ARM_64\020\004\022\010\n\004MIPS\020\005" +
      "\022\013\n\007MIPS_64\020\006\"\226\001\n\020EmulatorRenderer\022\035\n\031UN",
      "KNOWN_EMULATOR_RENDERER\020\000\022\010\n\004HOST\020\001\022\007\n\003O" +
      "FF\020\002\022\t\n\005GUEST\020\003\022\010\n\004MESA\020\004\022\017\n\013SWIFTSHADER" +
      "\020\005\022\t\n\005ANGLE\020\006\022\037\n\032ERROR_IN_EMULATOR_RENDE" +
      "RER\020\377\001\"\234\003\n\017EmulatorUiEvent\022\022\n\nelement_id" +
      "\030\001 \001(\t\022A\n\004type\030\002 \001(\01623.android_studio.Em" +
      "ulatorUiEvent.EmulatorUiEventType\022G\n\007con" +
      "text\030\003 \001(\01626.android_studio.EmulatorUiEv" +
      "ent.EmulatorUiEventContext\022\r\n\005value\030\004 \001(" +
      "\003\"\177\n\023EmulatorUiEventType\022\"\n\036UNKONWN_EMUL" +
      "ATOR_UI_EVENT_TYPE\020\000\022\020\n\014BUTTON_PRESS\020\001\022\035",
      "\n\031OPTION_SET_TO_NON_DEFAULT\020\002\022\023\n\017OPTION_" +
      "SELECTED\020\003\"Y\n\026EmulatorUiEventContext\022%\n!" +
      "UNKNOWN_EMULATOR_UI_EVENT_CONTEXT\020\000\022\030\n\024E" +
      "XTENDED_WINDOW_OPEN\020\001\"\207\003\n\022GradleBuildDet" +
      "ails\022\036\n\026android_plugin_version\030\001 \001(\t\022\026\n\016" +
      "gradle_version\030\002 \001(\t\022\027\n\017user_enabled_ir\030" +
      "\003 \001(\010\022\031\n\021model_supports_ir\030\004 \001(\010\022\033\n\023vari" +
      "ant_supports_ir\030\005 \001(\010\0220\n\tlibraries\030\006 \003(\013" +
      "2\035.android_studio.GradleLibrary\022-\n\007modul" +
      "es\030\007 \003(\0132\034.android_studio.GradleModule\022<",
      "\n\017android_modules\030\010 \003(\0132#.android_studio" +
      ".GradleAndroidModule\022I\n\026native_android_m" +
      "odules\030\t \003(\0132).android_studio.GradleNati" +
      "veAndroidModule\"K\n\rGradleLibrary\022\034\n\024jar_" +
      "dependency_count\030\001 \001(\003\022\034\n\024aar_dependency" +
      "_count\030\002 \001(\003\"^\n\014GradleModule\022\032\n\022total_mo" +
      "dule_count\030\001 \001(\003\022\030\n\020app_module_count\030\002 \001" +
      "(\003\022\030\n\020lib_module_count\030\003 \001(\003\"\266\001\n\023GradleA" +
      "ndroidModule\022\016\n\006app_id\030\001 \001(\t\022\023\n\013module_n" +
      "ame\030\002 \001(\t\022\022\n\nis_library\030\003 \001(\010\022\030\n\020build_t",
      "ype_count\030\004 \001(\003\022\024\n\014flavor_count\030\005 \001(\003\022\030\n" +
      "\020flavor_dimension\030\006 \001(\003\022\034\n\024signing_confi" +
      "g_count\030\007 \001(\003\"\240\002\n\031GradleNativeAndroidMod" +
      "ule\022\016\n\006app_id\030\001 \001(\t\022\023\n\013module_name\030\002 \001(\t" +
      "\022Z\n\021build_system_type\030\003 \001(\0162?.android_st" +
      "udio.GradleNativeAndroidModule.NativeBui" +
      "ldSystemType\"\201\001\n\025NativeBuildSystemType\022$" +
      "\n UNKNOWN_NATIVE_BUILD_SYSTEM_TYPE\020\000\022\027\n\023" +
      "GRADLE_EXPERIMENTAL\020\001\022\017\n\013NDK_COMPILE\020\002\022\r" +
      "\n\tNDK_BUILD\020\003\022\t\n\005CMAKE\020\004\"\244\013\n\nInstantRun\022",
      "L\n\017deployment_kind\030\001 \001(\01623.android_studi" +
      "o.InstantRun.InstantRunDeploymentKind\022P\n" +
      "\027instant_run_build_cause\030\003 \001(\0162/.android" +
      "_studio.InstantRun.InstantRunBuildCause\022" +
      "\022\n\nbuild_time\030\004 \001(\003\022\022\n\nsession_id\030\005 \001(\t\022" +
      "K\n\017ide_build_cause\030\006 \001(\01622.android_studi" +
      "o.InstantRun.InstantRunIdeBuildCause\022K\n\022" +
      "gradle_build_cause\030\007 \001(\0162/.android_studi" +
      "o.InstantRunStatus.VerifierStatus\"\242\001\n\030In" +
      "stantRunDeploymentKind\022\'\n#UNKNOWN_INSTAN",
      "T_RUN_DEPLOYMENT_KIND\020\000\022\n\n\006LEGACY\020\001\022\014\n\010F" +
      "ULL_APK\020\002\022\r\n\tSPLIT_APK\020\003\022\007\n\003DEX\020\004\022\014\n\010HOT" +
      "_SWAP\020\005\022\r\n\tWARM_SWAP\020\006\022\016\n\nNO_CHANGES\020\007\"\277" +
      "\003\n\024InstantRunBuildCause\022#\n\037UNKNOWN_INSTA" +
      "NT_RUN_BUILD_CAUSE\020\000\022\016\n\nCOMPATIBLE\020\001\022\023\n\017" +
      "MANIFEST_CHANGE\020\002\022\025\n\021FIELD_TYPE_CHANGE\020\003" +
      "\022\021\n\rFIELD_REMOVED\020\004\022\017\n\013FIELD_ADDED\020\005\022\022\n\016" +
      "METHOD_DELETED\020\006\022\020\n\014METHOD_ADDED\020\007\022\017\n\013CL" +
      "ASS_ADDED\020\010\022\035\n\031STATIC_INITIALIZER_CHANGE" +
      "\020\t\022\033\n\027CLASS_ANNOTATION_CHANGE\020\n\022\023\n\017RESOU",
      "RCE_CHANGE\020\013\022\037\n\033IMPLEMENTS_INTERFACE_CHA" +
      "NGE\020\014\022\022\n\016R_CLASS_CHANGE\020\r\022\027\n\023PARENT_CLAS" +
      "S_CHANGE\020\016\022\034\n\030METHOD_ANNOTATION_CHANGE\020\017" +
      "\022\031\n\025API_LEVEL_UNSUPPORTED\020\020\022\023\n\017REFLECTIO" +
      "N_USED\020\021\"\314\003\n\027InstantRunIdeBuildCause\022\'\n#" +
      "UNKNOWN_INSTANT_RUN_IDE_BUILD_CAUSE\020\000\022\r\n" +
      "\tNO_DEVICE\020\001\022\025\n\021APP_NOT_INSTALLED\020\002\022\032\n\026M" +
      "ISMATCHING_TIMESTAMPS\020\003\022\036\n\032USER_REQUESTE" +
      "D_CLEAN_BUILD\020\004\022\037\n\033API_TOO_LOW_FOR_INSTA" +
      "NT_RUN\020\005\022 \n\034FIRST_INSTALLATION_TO_DEVICE",
      "\020\006\022\035\n\031MANIFEST_RESOURCE_CHANGED\020\007\022\036\n\032FRE" +
      "EZE_SWAP_REQUIRES_API21\020\010\022\'\n#FREEZE_SWAP" +
      "_REQUIRES_WORKING_RUN_AS\020\t\022\023\n\017APP_NOT_RU" +
      "NNING\020\n\022\037\n\033APP_USES_MULTIPLE_PROCESSES\020\013" +
      "\022\025\n\021INCREMENTAL_BUILD\020\014\022\022\n\016NO_INSTANT_RU" +
      "N\020\r\022\032\n\026ANDROID_TV_UNSUPPORTED\020\016\"k\n\013MetaM" +
      "etrics\022\032\n\022failed_connections\030\001 \001(\005\022!\n\031by" +
      "tes_sent_in_last_upload\030\002 \001(\003\022\035\n\025failed_" +
      "server_replies\030\003 \001(\005\"\200\004\n\007TestRun\022H\n\024test" +
      "_invocation_type\030\001 \001(\0162*.android_studio.",
      "TestRun.TestInvocationType\022 \n\030number_of_" +
      "tests_executed\030\002 \001(\005\0223\n\ttest_kind\030\003 \001(\0162" +
      " .android_studio.TestRun.TestKind\022\017\n\007cra" +
      "shed\030\004 \001(\010\022\026\n\016gradle_version\030\005 \001(\t\022\035\n\025co" +
      "de_coverage_enabled\030\006 \001(\010\0225\n\016test_librar" +
      "ies\030\007 \001(\0132\035.android_studio.TestLibraries" +
      "\"\210\001\n\022TestInvocationType\022 \n\034UNKNOWN_TEST_" +
      "INVOCATION_TYPE\020\000\022\017\n\013GRADLE_TEST\020\001\022\027\n\023AN" +
      "DROID_STUDIO_TEST\020\002\022&\n\"ANDROID_STUDIO_TH" +
      "ROUGH_GRADLE_TEST\020\003\"J\n\010TestKind\022\025\n\021UNKNO",
      "WN_TEST_KIND\020\000\022\r\n\tUNIT_TEST\020\001\022\030\n\024INSTRUM" +
      "ENTATION_TEST\020\002\"\205\001\n\rTestLibraries\022$\n\034tes" +
      "t_support_library_version\030\001 \001(\t\022\030\n\020espre" +
      "sso_version\030\002 \001(\t\022\033\n\023robolectric_version" +
      "\030\003 \001(\t\022\027\n\017mockito_version\030\004 \001(\t\"\311\001\n\nHype" +
      "rvisor\022=\n\rhyper_v_state\030\001 \001(\0162&.android_" +
      "studio.Hypervisor.HyperVState\"|\n\013HyperVS" +
      "tate\022\030\n\024UNKNOWN_HYPERV_STATE\020\000\022\021\n\rHYPERV" +
      "_ABSENT\020\001\022\024\n\020HYPERV_INSTALLED\020\002\022\022\n\016HYPER" +
      "V_RUNNING\020\003\022\026\n\022HYPERV_CHECK_ERROR\020\004\"k\n\014E",
      "mulatorHost\022\030\n\020cpu_manufacturer\030\001 \001(\t\022\024\n" +
      "\014virt_support\030\002 \001(\010\022\025\n\rrunning_in_vm\030\003 \001" +
      "(\010\022\024\n\014os_bit_count\030\004 \001(\003\"\310\003\n\022GradleBuild" +
      "Profile\022\026\n\016gradle_version\030\002 \001(\t\022\017\n\007os_na" +
      "me\030\006 \001(\t\022\022\n\nos_version\030\007 \001(\t\022\024\n\014java_ver" +
      "sion\030\010 \001(\t\022\027\n\017java_vm_version\030\t \001(\t\022\022\n\nm" +
      "ax_memory\030\n \001(\003\022\022\n\nbuild_time\030\013 \001(\003\022\020\n\010g" +
      "c_count\030\014 \001(\003\022\017\n\007gc_time\030\r \001(\003\0223\n\007projec" +
      "t\030\016 \003(\0132\".android_studio.GradleBuildProj" +
      "ect\022>\n\rmemory_sample\030\017 \003(\0132\'.android_stu",
      "dio.GradleBuildMemorySample\0224\n\004span\030\020 \003(" +
      "\0132&.android_studio.GradleBuildProfileSpa" +
      "n\022<\n\022instant_run_status\030\021 \001(\0132 .android_" +
      "studio.InstantRunStatus\022\022\n\nproject_id\030\022 " +
      "\001(\t\"\260\004\n\022GradleBuildProject\022\n\n\002id\030\001 \001(\003\022\036" +
      "\n\026android_plugin_version\030\002 \001(\t\022E\n\016androi" +
      "d_plugin\030\003 \001(\0162-.android_studio.GradleBu" +
      "ildProject.PluginType\022N\n\021plugin_generati" +
      "on\030\004 \001(\01623.android_studio.GradleBuildPro" +
      "ject.PluginGeneration\022\033\n\023build_tools_ver",
      "sion\030\005 \001(\t\022:\n\007metrics\030\006 \001(\0132).android_st" +
      "udio.GradleBuildProjectMetrics\0223\n\007varian" +
      "t\030\007 \003(\0132\".android_studio.GradleBuildVari" +
      "ant\022\r\n\005atoms\030\010 \001(\003\"g\n\nPluginType\022\027\n\023UNKN" +
      "OWN_PLUGIN_TYPE\020\000\022\017\n\013APPLICATION\020\001\022\013\n\007LI" +
      "BRARY\020\002\022\010\n\004TEST\020\003\022\010\n\004ATOM\020\004\022\016\n\nINSTANTAP" +
      "P\020\005\"Q\n\020PluginGeneration\022\035\n\031UNKNOWN_PLUGI" +
      "N_GENERATION\020\000\022\t\n\005FIRST\020\001\022\023\n\017COMPONENT_M" +
      "ODEL\020\002\"a\n\031GradleBuildProjectMetrics\022\027\n\017m" +
      "etrics_time_ns\030\001 \001(\003\022\020\n\010apk_size\030\002 \001(\003\022\031",
      "\n\021resources_ap_size\030\003 \001(\003\"\320\002\n\022GradleBuil" +
      "dVariant\022\n\n\002id\030\001 \001(\003\022\020\n\010is_debug\030\002 \001(\010\022\020" +
      "\n\010use_jack\030\003 \001(\010\022\026\n\016minify_enabled\030\004 \001(\010" +
      "\022\024\n\014use_multidex\030\005 \001(\010\022\033\n\023use_legacy_mul" +
      "tidex\030\006 \001(\010\022D\n\014variant_type\030\007 \001(\0162..andr" +
      "oid_studio.GradleBuildVariant.VariantTyp" +
      "e\022\021\n\ttested_id\030\010 \001(\003\"f\n\013VariantType\022\017\n\013A" +
      "PPLICATION\020\000\022\013\n\007LIBRARY\020\001\022\020\n\014ANDROID_TES" +
      "T\020\002\022\r\n\tUNIT_TEST\020\003\022\010\n\004ATOM\020\004\022\016\n\nINSTANTA" +
      "PP\020\005\"\220\001\n\027GradleBuildMemorySample\022\022\n\ngc_t",
      "ime_ms\030\001 \001(\003\022\020\n\010gc_count\030\002 \001(\003\022\021\n\ttimest" +
      "amp\030\003 \001(\003\022<\n\022java_process_stats\030\004 \001(\0132 ." +
      "android_studio.JavaProcessStats\"\251$\n\026Grad" +
      "leBuildProfileSpan\022\n\n\002id\030\001 \001(\003\022\021\n\tparent" +
      "_id\030\002 \001(\003\022\030\n\020start_time_in_ms\030\003 \001(\003\022\026\n\016d" +
      "uration_in_ms\030\004 \001(\003\022B\n\004type\030\005 \001(\01624.andr" +
      "oid_studio.GradleBuildProfileSpan.Execut" +
      "ionType\022;\n\ttransform\030\006 \001(\0132(.android_stu" +
      "dio.GradleTransformExecution\0221\n\004task\030\t \001" +
      "(\0132#.android_studio.GradleTaskExecution\022",
      "\017\n\007project\030\007 \001(\003\022\017\n\007variant\030\010 \001(\003\"\347!\n\rEx" +
      "ecutionType\022\032\n\026SOME_RANDOM_PROCESSING\020\001\022" +
      "!\n\035BASE_PLUGIN_PROJECT_CONFIGURE\020\002\022/\n+BA" +
      "SE_PLUGIN_PROJECT_BASE_EXTENSION_CREATIO" +
      "N\020\003\022&\n\"BASE_PLUGIN_PROJECT_TASKS_CREATIO" +
      "N\020\004\022\036\n\032BASE_PLUGIN_BUILD_FINISHED\020\005\022\035\n\031T" +
      "ASK_MANAGER_CREATE_TASKS\020\006\022$\n BASE_PLUGI" +
      "N_CREATE_ANDROID_TASKS\020\007\022(\n$VARIANT_MANA" +
      "GER_CREATE_ANDROID_TASKS\020\010\022,\n(VARIANT_MA" +
      "NAGER_CREATE_TASKS_FOR_VARIANT\020\t\022%\n!VARI",
      "ANT_MANAGER_CREATE_LINT_TASKS\020\n\022&\n\"VARIA" +
      "NT_MANAGER_CREATE_TESTS_TASKS\020\013\022#\n\037VARIA" +
      "NT_MANAGER_CREATE_VARIANTS\020\014\022\030\n\024RESOLVE_" +
      "DEPENDENCIES\020\r\022\022\n\016TASK_EXECUTION\020\016\022\024\n\020IN" +
      "ITIAL_METADATA\020d\022\022\n\016FINAL_METADATA\020e\022\022\n\016" +
      "GENERAL_CONFIG\020f\022\022\n\016VARIANT_CONFIG\020g\0221\n-" +
      "VARIANT_MANAGER_EXTERNAL_NATIVE_CONFIG_V" +
      "ALUES\020h\022\017\n\013APK_METRICS\020i\0220\n+APP_TASK_MAN" +
      "AGER_CREATE_MERGE_MANIFEST_TASK\020\350\007\0225\n0AP" +
      "P_TASK_MANAGER_CREATE_GENERATE_RES_VALUE",
      "S_TASK\020\351\007\0225\n0APP_TASK_MANAGER_CREATE_CRE" +
      "ATE_RENDERSCRIPT_TASK\020\352\007\0221\n,APP_TASK_MAN" +
      "AGER_CREATE_MERGE_RESOURCES_TASK\020\353\007\022.\n)A" +
      "PP_TASK_MANAGER_CREATE_MERGE_ASSETS_TASK" +
      "\020\354\007\022.\n)APP_TASK_MANAGER_CREATE_BUILD_CON" +
      "FIG_TASK\020\355\007\022-\n(APP_TASK_MANAGER_CREATE_P" +
      "ROCESS_RES_TASK\020\356\007\022&\n!APP_TASK_MANAGER_C" +
      "REATE_AIDL_TASK\020\357\007\022)\n$APP_TASK_MANAGER_C" +
      "REATE_COMPILE_TASK\020\360\007\022%\n APP_TASK_MANAGE" +
      "R_CREATE_NDK_TASK\020\361\007\022\'\n\"APP_TASK_MANAGER",
      "_CREATE_SPLIT_TASK\020\362\007\022+\n&APP_TASK_MANAGE" +
      "R_CREATE_PACKAGING_TASK\020\363\007\0226\n1APP_TASK_M" +
      "ANAGER_CREATE_PREPROCESS_RESOURCES_TASK\020" +
      "\364\007\0224\n/APP_TASK_MANAGER_CREATE_BACKPORT_R" +
      "ESOURCES_TASK\020\365\007\022&\n!APP_TASK_MANAGER_CRE" +
      "ATE_LINT_TASK\020\366\007\0227\n2APP_TASK_MANAGER_CRE" +
      "ATE_MERGE_JNILIBS_FOLDERS_TASK\020\367\007\022(\n#APP" +
      "_TASK_MANAGER_CREATE_SHADER_TASK\020\370\007\0227\n2A" +
      "PP_TASK_MANAGER_CREATE_EXTERNAL_NATIVE_B" +
      "UILD_TASK\020\371\007\0226\n1APP_TASK_MANAGER_CREATE_",
      "STRIP_NATIVE_LIBRARY_TASK\020\372\007\0220\n+LIB_TASK" +
      "_MANAGER_CREATE_MERGE_MANIFEST_TASK\020\320\017\0225" +
      "\n0LIB_TASK_MANAGER_CREATE_GENERATE_RES_V" +
      "ALUES_TASK\020\321\017\0225\n0LIB_TASK_MANAGER_CREATE" +
      "_CREATE_RENDERSCRIPT_TASK\020\322\017\0221\n,LIB_TASK" +
      "_MANAGER_CREATE_MERGE_RESOURCES_TASK\020\323\017\022" +
      ".\n)LIB_TASK_MANAGER_CREATE_MERGE_ASSETS_" +
      "TASK\020\324\017\022.\n)LIB_TASK_MANAGER_CREATE_BUILD" +
      "_CONFIG_TASK\020\325\017\022-\n(LIB_TASK_MANAGER_CREA" +
      "TE_PROCESS_RES_TASK\020\326\017\022&\n!LIB_TASK_MANAG",
      "ER_CREATE_AIDL_TASK\020\327\017\022)\n$LIB_TASK_MANAG" +
      "ER_CREATE_COMPILE_TASK\020\330\017\022%\n LIB_TASK_MA" +
      "NAGER_CREATE_NDK_TASK\020\331\017\022\'\n\"LIB_TASK_MAN" +
      "AGER_CREATE_SPLIT_TASK\020\332\017\022+\n&LIB_TASK_MA" +
      "NAGER_CREATE_PACKAGING_TASK\020\333\017\0225\n0LIB_TA" +
      "SK_MANAGER_CREATE_MERGE_PROGUARD_FILE_TA" +
      "SK\020\334\017\0222\n-LIB_TASK_MANAGER_CREATE_POST_CO" +
      "MPILATION_TASK\020\335\017\022*\n%LIB_TASK_MANAGER_CR" +
      "EATE_PROGUARD_TASK\020\336\017\022.\n)LIB_TASK_MANAGE" +
      "R_CREATE_PACKAGE_LOCAL_JAR\020\337\017\0224\n/LIB_TAS",
      "K_MANAGER_CREATE_BACKPORT_RESOURCES_TASK" +
      "\020\340\017\022&\n!LIB_TASK_MANAGER_CREATE_LINT_TASK" +
      "\020\341\017\022(\n#LIB_TASK_MANAGER_CREATE_SHADER_TA" +
      "SK\020\342\017\0227\n2LIB_TASK_MANAGER_CREATE_EXTERNA" +
      "L_NATIVE_BUILD_TASK\020\343\017\022\033\n\026GENERIC_TASK_E" +
      "XECUTION\020\270\027\022\026\n\021TASK_AIDL_COMPILE\020\271\027\022\020\n\013T" +
      "ASK_DELETE\020\272\027\022\030\n\023TASK_CHECK_MANIFEST\020\273\027\022" +
      "#\n\036TASK_PREPARE_DEPENDENCIES_TASK\020\274\027\022\036\n\031" +
      "TASK_RENDERSCRIPT_COMPILE\020\275\027\022\037\n\032TASK_GEN" +
      "ERATE_BUILD_CONFIG\020\276\027\022\026\n\021TASK_MERGE_ASSE",
      "TS\020\277\027\022\035\n\030TASK_GENERATE_RES_VALUES\020\300\027\022\031\n\024" +
      "TASK_MERGE_RESOURCES\020\301\027\022\031\n\024TASK_MERGE_MA" +
      "NIFESTS\020\302\027\022#\n\036TASK_PROCESS_ANDROID_RESOU" +
      "RCES\020\303\027\022\026\n\021TASK_JAVA_COMPILE\020\304\027\022\025\n\020TASK_" +
      "NDK_COMPILE\020\305\027\022\021\n\014TASK_PRE_DEX\020\306\027\022\r\n\010TAS" +
      "K_DEX\020\307\027\022\033\n\026TASK_PACKAGE_SPLIT_RES\020\310\027\022\033\n" +
      "\026TASK_PROCESS_RESOURCES\020\311\027\022\037\n\032TASK_VALID" +
      "ATE_SIGNING_TASK\020\312\027\022\035\n\030TASK_PACKAGE_APPL" +
      "ICATION\020\313\027\022\031\n\024TASK_SPLIT_ZIP_ALIGN\020\314\027\022\023\n" +
      "\016TASK_ZIP_ALIGN\020\315\027\022\016\n\tTASK_COPY\020\316\027\022\016\n\tTA",
      "SK_LINT\020\317\027\022\033\n\026TASK_FILE_VERIFICATION\020\322\027\022" +
      "=\n8TASK_EXTERNAL_NATIVE_BUILD_GENERATE_J" +
      "SON_PROCESS_PER_ABI\020\323\027\0225\n0TASK_EXTERNAL_" +
      "NATIVE_BUILD_GENERATE_JSON_PROCESS\020\324\027\022\037\n" +
      "\032TASK_TRANSFORM_PREPARATION\020\320\027\022\023\n\016TASK_T" +
      "RANSFORM\020\321\027\0221\n,ATOM_TASK_MANAGER_CREATE_" +
      "MERGE_MANIFEST_TASK\020\240\037\0226\n1ATOM_TASK_MANA" +
      "GER_CREATE_GENERATE_RES_VALUES_TASK\020\241\037\0226" +
      "\n1ATOM_TASK_MANAGER_CREATE_CREATE_RENDER" +
      "SCRIPT_TASK\020\242\037\0222\n-ATOM_TASK_MANAGER_CREA",
      "TE_MERGE_RESOURCES_TASK\020\243\037\022/\n*ATOM_TASK_" +
      "MANAGER_CREATE_MERGE_ASSETS_TASK\020\244\037\022/\n*A" +
      "TOM_TASK_MANAGER_CREATE_BUILD_CONFIG_TAS" +
      "K\020\245\037\022.\n)ATOM_TASK_MANAGER_CREATE_PROCESS" +
      "_RES_TASK\020\246\037\022\'\n\"ATOM_TASK_MANAGER_CREATE" +
      "_AIDL_TASK\020\247\037\022)\n$ATOM_TASK_MANAGER_CREAT" +
      "E_SHADER_TASK\020\250\037\022&\n!ATOM_TASK_MANAGER_CR" +
      "EATE_NDK_TASK\020\251\037\0228\n3ATOM_TASK_MANAGER_CR" +
      "EATE_EXTERNAL_NATIVE_BUILD_TASK\020\252\037\0228\n3AT" +
      "OM_TASK_MANAGER_CREATE_MERGE_JNILIBS_FOL",
      "DERS_TASK\020\253\037\022*\n%ATOM_TASK_MANAGER_CREATE" +
      "_COMPILE_TASK\020\254\037\022+\n&ATOM_TASK_MANAGER_CR" +
      "EATE_BUNDLING_TASK\020\255\037\022\'\n\"ATOM_TASK_MANAG" +
      "ER_CREATE_LINT_TASK\020\256\037\0227\n2INSTANTAPP_TAS" +
      "K_MANAGER_CREATE_MERGE_MANIFEST_TASK\020\210\'\022" +
      "8\n3INSTANTAPP_TASK_MANAGER_CREATE_ATOM_P" +
      "ACKAGING_TASKS\020\211\'\0224\n/INSTANTAPP_TASK_MAN" +
      "AGER_CREATE_PROCESS_RES_TASK\020\212\'\0222\n-INSTA" +
      "NTAPP_TASK_MANAGER_CREATE_PACKAGING_TASK" +
      "\020\213\'\"\320\020\n\023GradleTaskExecution\0226\n\004type\030\001 \001(",
      "\0162(.android_studio.GradleTaskExecution.T" +
      "ype\022\020\n\010did_work\030\002 \001(\010\022\017\n\007skipped\030\003 \001(\010\022\022" +
      "\n\nup_to_date\030\004 \001(\010\022\016\n\006failed\030\005 \001(\010\"\271\017\n\004T" +
      "ype\022\025\n\021UNKNOWN_TASK_TYPE\020\000\022\020\n\014AIDL_COMPI" +
      "LE\020\001\022\017\n\013ANDROID_JAR\020\002\022\030\n\024ANDROID_JAVA_CO" +
      "MPILE\020\003\022\022\n\016ANDROID_REPORT\020\004\022\025\n\021ANDROID_U" +
      "NIT_TEST\020\005\022\022\n\016BUILD_EMULATOR\020\006\022\025\n\021BUILD_" +
      "INFO_LOADER\020\007\022\022\n\016CHECK_MANIFEST\020\010\022\037\n\033COM" +
      "PATIBLE_SCREENS_MANIFEST\020\t\022\035\n\031CREATE_MAN" +
      "IFEST_KEEP_LIST\020\n\022\"\n\036DATA_BINDING_EXPORT",
      "_BUILD_INFO\020\013\022 \n\034DATA_BINDING_PROCESS_LA" +
      "YOUTS\020\014\022\025\n\021DEPENDENCY_REPORT\020\r\022#\n\037DEVICE" +
      "_PROVIDER_INSTRUMENT_TEST\020\016\022\031\n\025EXTERNAL_" +
      "BUILD_ANCHOR\020\017\022\036\n\032EXTERNAL_NATIVE_BUILD_" +
      "JSON\020\020\022\031\n\025EXTERNAL_NATIVE_BUILD\020\021\022\027\n\023EXT" +
      "RACT_ANNOTATIONS\020\022\022\032\n\026EXTRACT_JAVA_RESOU" +
      "RCES\020\023\022\032\n\026EXTRACT_PROGUARD_FILES\020\024\022!\n\035FA" +
      "ST_DEPLOY_RUNTIME_EXTRACTOR\020\025\022\025\n\021FILTERE" +
      "D_JAR_COPY\020\026\022\025\n\021GENERATE_APK_DATA\020\027\022\031\n\025G" +
      "ENERATE_BUILD_CONFIG\020\030\022!\n\035GENERATE_INSTA",
      "NT_RUN_APP_INFO\020\031\022\027\n\023GENERATE_RES_VALUES" +
      "\020\032\022\032\n\026GENERATE_SPLIT_ABI_RES\020\033\022\023\n\017GOOGLE" +
      "_SERVICES\020\034\022\031\n\025INCREMENTAL_SAFEGUARD\020\035\022\023" +
      "\n\017INSTALL_VARIANT\020\036\022!\n\035INSTANT_RUN_SPLIT" +
      "_APK_BUILDER\020\037\022\027\n\023INSTANT_RUN_WRAPPER\020 \022" +
      "\032\n\026INVOKE_MANIFEST_MERGER\020!\022\026\n\022JACK_JACO" +
      "CO_REPORT\020\"\022\021\n\rJACOCO_REPORT\020#\022\010\n\004LINT\020$" +
      "\022\020\n\014LINT_COMPILE\020%\022\016\n\nMERGE_FILE\020&\022\023\n\017ME" +
      "RGE_MANIFESTS\020\'\022\023\n\017MERGE_RESOURCES\020(\022\034\n\030" +
      "MERGE_SOURCE_SET_FOLDERS\020)\022\030\n\024MOCKABLE_A",
      "NDROID_JAR\020*\022\017\n\013NDK_COMPILE\020+\022\007\n\003NDK\020,\022\027" +
      "\n\023PACKAGE_APPLICATION\020-\022\025\n\021PACKAGE_SPLIT" +
      "_ABI\020.\022\025\n\021PACKAGE_SPLIT_RES\020/\022\021\n\rPRE_COL" +
      "D_SWAP\0200\022\030\n\024PREPARE_DEPENDENCIES\0201\022\023\n\017PR" +
      "EPARE_LIBRARY\0202\022\035\n\031PROCESS_ANDROID_RESOU" +
      "RCES\0203\022\024\n\020PROCESS_MANIFEST\0204\022\031\n\025PROCESS_" +
      "TEST_MANIFEST\0205\022\030\n\024RENDERSCRIPT_COMPILE\020" +
      "6\022\022\n\016SHADER_COMPILE\0207\022\022\n\016SIGNING_REPORT\020" +
      "8\022\024\n\020SINGLE_FILE_COPY\0209\022\017\n\013SOURCE_SETS\020:" +
      "\022\023\n\017SPLIT_ZIP_ALIGN\020;\022\020\n\014STREAM_BASED\020<\022",
      "\026\n\022STRIP_DEBUG_SYMBOL\020=\022\026\n\022STRIP_DEPENDE" +
      "NCIES\020>\022\031\n\025TEST_MODULE_PRO_GUARD\020?\022\017\n\013TE" +
      "ST_SERVER\020@\022\r\n\tTRANSFORM\020A\022\r\n\tUNINSTALL\020" +
      "B\022\024\n\020VALIDATE_SIGNING\020C\022\r\n\tZIP_ALIGN\020D\022\020" +
      "\n\014JAVA_COMPILE\020E\022\025\n\021BUILD_INFO_WRITER\020F\022" +
      "\017\n\013BUNDLE_ATOM\020G\022&\n\"CHECK_MANIFEST_IN_IN" +
      "STANT_RUN_MODE\020H\022\031\n\025EXTERNAL_NATIVE_CLEA" +
      "N\020I\022\032\n\026GENERATE_ATOM_METADATA\020J\022!\n\035GENER" +
      "ATE_INSTANT_APP_METADATA\020K\022\024\n\020JAVA_PRE_C" +
      "OMPILE\020L\022\034\n\030MERGE_DEX_ATOM_RES_CLASS\020M\022\020",
      "\n\014PACKAGE_ATOM\020N\022\027\n\023PACKAGE_INSTANT_APP\020" +
      "O\022\020\n\014PREPARE_ATOM\020P\022!\n\035PROCESS_INSTANT_A" +
      "PP_RESOURCES\020Q\"\304\004\n\030GradleTransformExecut" +
      "ion\022;\n\004type\030\001 \001(\0162-.android_studio.Gradl" +
      "eTransformExecution.Type\022\026\n\016is_increment" +
      "al\030\002 \001(\010\"\322\003\n\004Type\022\032\n\026UNKNOWN_TRANSFORM_T" +
      "YPE\020\000\022\007\n\003DEX\020\001\022\020\n\014EXTRACT_JARS\020\002\022\023\n\017INST" +
      "ANT_RUN_DEX\020\003\022\026\n\022INSTANT_RUN_SLICER\020\004\022\017\n" +
      "\013INSTANT_RUN\020\005\022\027\n\023INSTANT_RUN_VERIFER\020\006\022" +
      "\020\n\014JACK_PRE_DEX\020\007\022\010\n\004JACK\020\010\022\n\n\006JACOCO\020\t\022",
      "\017\n\013JAR_MERGING\020\n\022\017\n\013LIBRARY_JAR\020\013\022\024\n\020LIB" +
      "RARY_JNI_LIBS\020\014\022\030\n\024MERGE_JAVA_RESOURCES\020" +
      "\r\022\r\n\tMULTI_DEX\020\016\022\020\n\014NEW_SHRINKER\020\017\022\027\n\023NO" +
      "_CHANGES_VERIFIER\020\020\022\r\n\tPRO_GUARD\020\021\022\024\n\020SH" +
      "RINK_RESOURCES\020\022\022 \n\034DATA_BINDING_MERGE_A" +
      "RTIFACTS\020\023\022\030\n\024INSTANT_RUN_VERIFIER\020\024\022\026\n\022" +
      "STRIP_DEBUG_SYMBOL\020\025\022\017\n\013LIBRARY_API\020\026\"\256\t" +
      "\n\020InstantRunStatus\022>\n\nbuild_mode\030\001 \001(\0162*" +
      ".android_studio.InstantRunStatus.BuildMo" +
      "de\022H\n\017patching_policy\030\002 \001(\0162/.android_st",
      "udio.InstantRunStatus.PatchingPolicy\022H\n\017" +
      "verifier_status\030\003 \001(\0162/.android_studio.I" +
      "nstantRunStatus.VerifierStatus\0224\n\010artifa" +
      "ct\030\004 \003(\0132\".android_studio.InstantRunArti" +
      "fact\"E\n\tBuildMode\022\026\n\022UNKNOWN_BUILD_MODE\020" +
      "\000\022\014\n\010HOT_WARM\020\001\022\010\n\004COLD\020\002\022\010\n\004FULL\020\003\"]\n\016P" +
      "atchingPolicy\022\033\n\027UNKNOWN_PATCHING_POLICY" +
      "\020\000\022\020\n\014PRE_LOLLIPOP\020\001\022\r\n\tMULTI_DEX\020\002\022\r\n\tM" +
      "ULTI_APK\020\003\"\351\005\n\016VerifierStatus\022\033\n\027UNKNOWN" +
      "_VERIFIER_STATUS\020\000\022\016\n\nCOMPATIBLE\020\001\022\013\n\007NO",
      "T_RUN\020\002\022\030\n\024INSTANT_RUN_DISABLED\020\003\022\027\n\023INS" +
      "TANT_RUN_FAILURE\020\004\022\017\n\013CLASS_ADDED\020\005\022\030\n\024P" +
      "ARENT_CLASS_CHANGED\020\006\022!\n\035IMPLEMENTED_INT" +
      "ERFACES_CHANGE\020\007\022\033\n\027CLASS_ANNOTATION_CHA" +
      "NGE\020\010\022\035\n\031STATIC_INITIALIZER_CHANGE\020\t\022 \n\034" +
      "CONSTRUCTOR_SIGNATURE_CHANGE\020\n\022\033\n\027METHOD" +
      "_SIGNATURE_CHANGE\020\013\022\034\n\030METHOD_ANNOTATION" +
      "_CHANGE\020\014\022\022\n\016METHOD_DELETED\020\r\022\020\n\014METHOD_" +
      "ADDED\020\016\022\017\n\013FIELD_ADDED\020\017\022\021\n\rFIELD_REMOVE" +
      "D\020\020\022\025\n\021FIELD_TYPE_CHANGE\020\021\022\022\n\016R_CLASS_CH",
      "ANGE\020\022\022\023\n\017REFLECTION_USED\020\023\022\032\n\026JAVA_RESO" +
      "URCES_CHANGED\020\024\022\026\n\022DEPENDENCY_CHANGED\020\025\022" +
      "\030\n\024MANIFEST_FILE_CHANGE\020\026\022\037\n\033BINARY_MANI" +
      "FEST_FILE_CHANGE\020\027\022\027\n\023COLD_SWAP_REQUESTE" +
      "D\020\030\022\030\n\024FULL_BUILD_REQUESTED\020\031\022\021\n\rINITIAL" +
      "_BUILD\020\032\022\016\n\nNO_CHANGES\020\033\0224\n0CHANGE_IN_SE" +
      "RIALIZABLE_CLASS_WITHOUT_VERSION_UID\020\034\"\261" +
      "\001\n\022InstantRunArtifact\0225\n\004type\030\001 \001(\0162\'.an" +
      "droid_studio.InstantRunArtifact.Type\"d\n\004" +
      "Type\022\010\n\004MAIN\020\001\022\016\n\nSPLIT_MAIN\020\002\022\016\n\nRELOAD",
      "_DEX\020\003\022\017\n\013RESTART_DEX\020\004\022\007\n\003DEX\020\005\022\t\n\005SPLI" +
      "T\020\006\022\r\n\tRESOURCES\020\007\"(\n\023LLDBFrontendDetail" +
      "s\022\021\n\texit_code\030\001 \001(\005\"-\n\024FirebaseErrorDet" +
      "ails\022\025\n\rerror_message\030\001 \001(\t\"\244\001\n\021GfxTraci" +
      "ngDetails\022\022\n\ntotal_time\030\001 \001(\003\022\017\n\007command" +
      "\030\002 \001(\t\022\025\n\rerror_message\030\003 \001(\t\022\022\n\ntrace_p" +
      "ath\030\004 \001(\t\022\024\n\014image_format\030\005 \001(\t\022\023\n\013image" +
      "_width\030\006 \001(\003\022\024\n\014image_height\030\007 \001(\003\"C\n\023Te" +
      "stRecorderDetails\022\023\n\013event_count\030\001 \001(\003\022\027" +
      "\n\017assertion_count\030\002 \001(\003\"\371\001\n\rUIActionStat",
      "s\022\031\n\021action_class_name\030\001 \001(\t\022\023\n\013invocati" +
      "ons\030\002 \001(\003\022E\n\017invocation_kind\030\003 \001(\0162,.and" +
      "roid_studio.UIActionStats.InvocationKind" +
      "\"q\n\016InvocationKind\022\033\n\027UNKNOWN_INVOCATION" +
      "_KIND\020\000\022\013\n\007TOOLBAR\020\001\022\010\n\004MENU\020\002\022\025\n\021KEYBOA" +
      "RD_SHORTCUT\020\003\022\t\n\005MACRO\020\004\022\t\n\005MOUSE\020\005\"\206\001\n\016" +
      "MachineDetails\022\021\n\ttotal_ram\030\001 \001(\003\022\022\n\ntot" +
      "al_disk\030\002 \001(\003\022/\n\007display\030\003 \003(\0132\036.android" +
      "_studio.DisplayDetails\022\034\n\024available_proc" +
      "essors\030\004 \001(\005\"q\n\016DisplayDetails\022\r\n\005width\030",
      "\001 \001(\003\022\016\n\006height\030\002 \001(\003\022 \n\030dots_per_inch_h" +
      "orizontal\030\003 \001(\005\022\036\n\026dots_per_inch_vertica" +
      "l\030\004 \001(\005\"\310\001\n\020JavaProcessStats\022\031\n\021heap_mem" +
      "ory_usage\030\001 \001(\003\022\035\n\025non_heap_memory_usage" +
      "\030\002 \001(\003\022\032\n\022loaded_class_count\030\003 \001(\005\022\024\n\014th" +
      "read_count\030\004 \001(\005\022H\n\030garbage_collection_s" +
      "tats\030\005 \003(\0132&.android_studio.GarbageColle" +
      "ctionStats\"O\n\026GarbageCollectionStats\022\014\n\004" +
      "name\030\001 \001(\t\022\026\n\016gc_collections\030\002 \001(\003\022\017\n\007gc" +
      "_time\030\003 \001(\003\"\265\003\n\nJvmDetails\022\014\n\004name\030\001 \001(\t",
      "\022\017\n\007version\030\002 \001(\t\022\016\n\006vendor\030\003 \001(\t\022\031\n\021min" +
      "imum_heap_size\030\004 \001(\003\022\031\n\021maximum_heap_siz" +
      "e\030\005 \001(\003\022$\n\034maximum_permanent_space_size\030" +
      "\006 \001(\003\022\037\n\027maximum_code_cache_size\030\007 \001(\003\022!" +
      "\n\031soft_reference_lru_policy\030\010 \001(\003\022F\n\021gar" +
      "bage_collector\030\t \001(\0162+.android_studio.Jv" +
      "mDetails.GarbageCollector\"\217\001\n\020GarbageCol" +
      "lector\022\022\n\016UNSPECIFIED_GC\020\000\022\034\n\030CONCURRENT" +
      "_MARK_SWEEP_GC\020\001\022\024\n\020GARBAGE_FIRST_GC\020\002\022\017" +
      "\n\013PARALLEL_GC\020\003\022\023\n\017PARALLEL_OLD_GC\020\004\022\r\n\t",
      "SERIAL_GC\020\005\"3\n\026StudioPerformanceStats\022\031\n" +
      "\021ui_freeze_time_ms\030\001 \001(\005\"K\n\020PercentileBu" +
      "cket\022\031\n\021target_percentile\030\001 \001(\001\022\r\n\005value" +
      "\030\002 \001(\001\022\r\n\005count\030\003 \001(\004\"[\n\023PercentileEstim" +
      "ator\022\022\n\nraw_sample\030\002 \003(\001\0220\n\006bucket\030\003 \003(\013" +
      "2 .android_studio.PercentileBucket\"\213\003\n\027L" +
      "ldbPercentileEstimator\022>\n\006metric\030\001 \001(\0162." +
      ".android_studio.LldbPercentileEstimator." +
      "Metric\0226\n\testimator\030\002 \001(\0132#.android_stud" +
      "io.PercentileEstimator\"\367\001\n\006Metric\022\026\n\022ATT",
      "ACH_TIME_MICROS\020\000\022$\n STEP_RESUME_RESPONS" +
      "E_TIME_MICROS\020\001\022\035\n\031GET_VARIABLES_TIME_MI" +
      "CROS\020\002\022+\n\'GET_VARIABLE_CHILDREN_RANGE_TI" +
      "ME_MICROS\020\003\022\032\n\026GET_FRAMES_TIME_MICROS\020\004\022" +
      "\'\n#ADD_SYMBOLIC_BREAKPOINT_TIME_MICROS\020\005" +
      "\022\036\n\032ADD_BREAKPOINT_TIME_MICROS\020\006\"R\n\024Lldb" +
      "PerformanceStats\022:\n\testimator\030\001 \003(\0132\'.an" +
      "droid_studio.LldbPercentileEstimator\",\n\023" +
      "StudioProjectChange\022\025\n\rprojects_open\030\001 \001" +
      "(\005B=\n%com.google.wireless.android.sdk.st",
      "atsB\022AndroidStudioStatsP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_android_studio_AndroidStudioEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_android_studio_AndroidStudioEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_AndroidStudioEvent_descriptor,
              new java.lang.String[] { "Category", "Kind", "StudioSessionId", "ProductDetails", "MonitorType", "MonitorPaused", "ProfilerCaptureType", "CloudTestingErrorMessage", "CloudTestingLoadedScreenshotsCount", "RunConfigurationType", "DebuggerType", "DeviceInfo", "LldbSessionFailureMessage", "DeveloperServiceKind", "GradleVersion", "GradleSyncFailure", "GradleMissingSignature", "TemplateRenderer", "StudioCrash", "GradleBuildDetails", "InstantRun", "MetaMetrics", "EmulatorDetails", "TestRun", "EmulatorUiEvent", "Hypervisor", "EmulatorHost", "GradleBuildProfile", "LldbFrontendDetails", "FirebaseErrorDetails", "ProjectId", "GfxTracingDetails", "TestRecorderDetails", "UiActionStats", "MachineDetails", "JvmDetails", "JavaProcessStats", "StudioPerformanceStats", "LldbPerformanceStats", "StudioProjectChange", });
          internal_static_android_studio_ProductDetails_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_android_studio_ProductDetails_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_ProductDetails_descriptor,
              new java.lang.String[] { "Product", "Build", "Version", "Preview", "OsArchitecture", "Channel", });
          internal_static_android_studio_DeviceInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_android_studio_DeviceInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_DeviceInfo_descriptor,
              new java.lang.String[] { "AnonymizedSerialNumber", "BuildTags", "BuildType", "BuildVersionRelease", "BuildApiLevel", "CpuAbi", "Manufacturer", "Model", "DeviceType", "BuildApiLevelFull", });
          internal_static_android_studio_StudioCrash_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_android_studio_StudioCrash_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_StudioCrash_descriptor,
              new java.lang.String[] { "Actions", "Exceptions", "Crashes", "BundledPluginExceptions", "NonBundledPluginExceptions", });
          internal_static_android_studio_EmulatorGuestGlInfo_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_android_studio_EmulatorGuestGlInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_EmulatorGuestGlInfo_descriptor,
              new java.lang.String[] { "Vendor", "Renderer", "Version", });
          internal_static_android_studio_EmulatorGpuInfo_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_android_studio_EmulatorGpuInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_EmulatorGpuInfo_descriptor,
              new java.lang.String[] { "Make", "Model", "DeviceId", "RevisionId", "Version", "Renderer", });
          internal_static_android_studio_EmulatorFeatures_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_android_studio_EmulatorFeatures_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_EmulatorFeatures_descriptor,
              new java.lang.String[] { "Gps", "Sensors", });
          internal_static_android_studio_EmulatorDetails_descriptor =
            getDescriptor().getMessageTypes().get(7);
          internal_static_android_studio_EmulatorDetails_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_EmulatorDetails_descriptor,
              new java.lang.String[] { "GuestArch", "SystemTime", "UserTime", "Crashes", "WallTime", "ExitStarted", "GuestApiLevel", "GuestGpuEnabled", "IsOpenglAlive", "AdbLiveness", "GuestGl", "HostGpu", "SessionPhase", "CoreVersion", "Renderer", "UsedFeatures", });
          internal_static_android_studio_EmulatorUiEvent_descriptor =
            getDescriptor().getMessageTypes().get(8);
          internal_static_android_studio_EmulatorUiEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_EmulatorUiEvent_descriptor,
              new java.lang.String[] { "ElementId", "Type", "Context", "Value", });
          internal_static_android_studio_GradleBuildDetails_descriptor =
            getDescriptor().getMessageTypes().get(9);
          internal_static_android_studio_GradleBuildDetails_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleBuildDetails_descriptor,
              new java.lang.String[] { "AndroidPluginVersion", "GradleVersion", "UserEnabledIr", "ModelSupportsIr", "VariantSupportsIr", "Libraries", "Modules", "AndroidModules", "NativeAndroidModules", });
          internal_static_android_studio_GradleLibrary_descriptor =
            getDescriptor().getMessageTypes().get(10);
          internal_static_android_studio_GradleLibrary_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleLibrary_descriptor,
              new java.lang.String[] { "JarDependencyCount", "AarDependencyCount", });
          internal_static_android_studio_GradleModule_descriptor =
            getDescriptor().getMessageTypes().get(11);
          internal_static_android_studio_GradleModule_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleModule_descriptor,
              new java.lang.String[] { "TotalModuleCount", "AppModuleCount", "LibModuleCount", });
          internal_static_android_studio_GradleAndroidModule_descriptor =
            getDescriptor().getMessageTypes().get(12);
          internal_static_android_studio_GradleAndroidModule_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleAndroidModule_descriptor,
              new java.lang.String[] { "AppId", "ModuleName", "IsLibrary", "BuildTypeCount", "FlavorCount", "FlavorDimension", "SigningConfigCount", });
          internal_static_android_studio_GradleNativeAndroidModule_descriptor =
            getDescriptor().getMessageTypes().get(13);
          internal_static_android_studio_GradleNativeAndroidModule_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleNativeAndroidModule_descriptor,
              new java.lang.String[] { "AppId", "ModuleName", "BuildSystemType", });
          internal_static_android_studio_InstantRun_descriptor =
            getDescriptor().getMessageTypes().get(14);
          internal_static_android_studio_InstantRun_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_InstantRun_descriptor,
              new java.lang.String[] { "DeploymentKind", "InstantRunBuildCause", "BuildTime", "SessionId", "IdeBuildCause", "GradleBuildCause", });
          internal_static_android_studio_MetaMetrics_descriptor =
            getDescriptor().getMessageTypes().get(15);
          internal_static_android_studio_MetaMetrics_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_MetaMetrics_descriptor,
              new java.lang.String[] { "FailedConnections", "BytesSentInLastUpload", "FailedServerReplies", });
          internal_static_android_studio_TestRun_descriptor =
            getDescriptor().getMessageTypes().get(16);
          internal_static_android_studio_TestRun_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_TestRun_descriptor,
              new java.lang.String[] { "TestInvocationType", "NumberOfTestsExecuted", "TestKind", "Crashed", "GradleVersion", "CodeCoverageEnabled", "TestLibraries", });
          internal_static_android_studio_TestLibraries_descriptor =
            getDescriptor().getMessageTypes().get(17);
          internal_static_android_studio_TestLibraries_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_TestLibraries_descriptor,
              new java.lang.String[] { "TestSupportLibraryVersion", "EspressoVersion", "RobolectricVersion", "MockitoVersion", });
          internal_static_android_studio_Hypervisor_descriptor =
            getDescriptor().getMessageTypes().get(18);
          internal_static_android_studio_Hypervisor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_Hypervisor_descriptor,
              new java.lang.String[] { "HyperVState", });
          internal_static_android_studio_EmulatorHost_descriptor =
            getDescriptor().getMessageTypes().get(19);
          internal_static_android_studio_EmulatorHost_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_EmulatorHost_descriptor,
              new java.lang.String[] { "CpuManufacturer", "VirtSupport", "RunningInVm", "OsBitCount", });
          internal_static_android_studio_GradleBuildProfile_descriptor =
            getDescriptor().getMessageTypes().get(20);
          internal_static_android_studio_GradleBuildProfile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleBuildProfile_descriptor,
              new java.lang.String[] { "GradleVersion", "OsName", "OsVersion", "JavaVersion", "JavaVmVersion", "MaxMemory", "BuildTime", "GcCount", "GcTime", "Project", "MemorySample", "Span", "InstantRunStatus", "ProjectId", });
          internal_static_android_studio_GradleBuildProject_descriptor =
            getDescriptor().getMessageTypes().get(21);
          internal_static_android_studio_GradleBuildProject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleBuildProject_descriptor,
              new java.lang.String[] { "Id", "AndroidPluginVersion", "AndroidPlugin", "PluginGeneration", "BuildToolsVersion", "Metrics", "Variant", "Atoms", });
          internal_static_android_studio_GradleBuildProjectMetrics_descriptor =
            getDescriptor().getMessageTypes().get(22);
          internal_static_android_studio_GradleBuildProjectMetrics_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleBuildProjectMetrics_descriptor,
              new java.lang.String[] { "MetricsTimeNs", "ApkSize", "ResourcesApSize", });
          internal_static_android_studio_GradleBuildVariant_descriptor =
            getDescriptor().getMessageTypes().get(23);
          internal_static_android_studio_GradleBuildVariant_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleBuildVariant_descriptor,
              new java.lang.String[] { "Id", "IsDebug", "UseJack", "MinifyEnabled", "UseMultidex", "UseLegacyMultidex", "VariantType", "TestedId", });
          internal_static_android_studio_GradleBuildMemorySample_descriptor =
            getDescriptor().getMessageTypes().get(24);
          internal_static_android_studio_GradleBuildMemorySample_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleBuildMemorySample_descriptor,
              new java.lang.String[] { "GcTimeMs", "GcCount", "Timestamp", "JavaProcessStats", });
          internal_static_android_studio_GradleBuildProfileSpan_descriptor =
            getDescriptor().getMessageTypes().get(25);
          internal_static_android_studio_GradleBuildProfileSpan_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleBuildProfileSpan_descriptor,
              new java.lang.String[] { "Id", "ParentId", "StartTimeInMs", "DurationInMs", "Type", "Transform", "Task", "Project", "Variant", });
          internal_static_android_studio_GradleTaskExecution_descriptor =
            getDescriptor().getMessageTypes().get(26);
          internal_static_android_studio_GradleTaskExecution_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleTaskExecution_descriptor,
              new java.lang.String[] { "Type", "DidWork", "Skipped", "UpToDate", "Failed", });
          internal_static_android_studio_GradleTransformExecution_descriptor =
            getDescriptor().getMessageTypes().get(27);
          internal_static_android_studio_GradleTransformExecution_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GradleTransformExecution_descriptor,
              new java.lang.String[] { "Type", "IsIncremental", });
          internal_static_android_studio_InstantRunStatus_descriptor =
            getDescriptor().getMessageTypes().get(28);
          internal_static_android_studio_InstantRunStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_InstantRunStatus_descriptor,
              new java.lang.String[] { "BuildMode", "PatchingPolicy", "VerifierStatus", "Artifact", });
          internal_static_android_studio_InstantRunArtifact_descriptor =
            getDescriptor().getMessageTypes().get(29);
          internal_static_android_studio_InstantRunArtifact_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_InstantRunArtifact_descriptor,
              new java.lang.String[] { "Type", });
          internal_static_android_studio_LLDBFrontendDetails_descriptor =
            getDescriptor().getMessageTypes().get(30);
          internal_static_android_studio_LLDBFrontendDetails_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_LLDBFrontendDetails_descriptor,
              new java.lang.String[] { "ExitCode", });
          internal_static_android_studio_FirebaseErrorDetails_descriptor =
            getDescriptor().getMessageTypes().get(31);
          internal_static_android_studio_FirebaseErrorDetails_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_FirebaseErrorDetails_descriptor,
              new java.lang.String[] { "ErrorMessage", });
          internal_static_android_studio_GfxTracingDetails_descriptor =
            getDescriptor().getMessageTypes().get(32);
          internal_static_android_studio_GfxTracingDetails_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GfxTracingDetails_descriptor,
              new java.lang.String[] { "TotalTime", "Command", "ErrorMessage", "TracePath", "ImageFormat", "ImageWidth", "ImageHeight", });
          internal_static_android_studio_TestRecorderDetails_descriptor =
            getDescriptor().getMessageTypes().get(33);
          internal_static_android_studio_TestRecorderDetails_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_TestRecorderDetails_descriptor,
              new java.lang.String[] { "EventCount", "AssertionCount", });
          internal_static_android_studio_UIActionStats_descriptor =
            getDescriptor().getMessageTypes().get(34);
          internal_static_android_studio_UIActionStats_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_UIActionStats_descriptor,
              new java.lang.String[] { "ActionClassName", "Invocations", "InvocationKind", });
          internal_static_android_studio_MachineDetails_descriptor =
            getDescriptor().getMessageTypes().get(35);
          internal_static_android_studio_MachineDetails_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_MachineDetails_descriptor,
              new java.lang.String[] { "TotalRam", "TotalDisk", "Display", "AvailableProcessors", });
          internal_static_android_studio_DisplayDetails_descriptor =
            getDescriptor().getMessageTypes().get(36);
          internal_static_android_studio_DisplayDetails_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_DisplayDetails_descriptor,
              new java.lang.String[] { "Width", "Height", "DotsPerInchHorizontal", "DotsPerInchVertical", });
          internal_static_android_studio_JavaProcessStats_descriptor =
            getDescriptor().getMessageTypes().get(37);
          internal_static_android_studio_JavaProcessStats_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_JavaProcessStats_descriptor,
              new java.lang.String[] { "HeapMemoryUsage", "NonHeapMemoryUsage", "LoadedClassCount", "ThreadCount", "GarbageCollectionStats", });
          internal_static_android_studio_GarbageCollectionStats_descriptor =
            getDescriptor().getMessageTypes().get(38);
          internal_static_android_studio_GarbageCollectionStats_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_GarbageCollectionStats_descriptor,
              new java.lang.String[] { "Name", "GcCollections", "GcTime", });
          internal_static_android_studio_JvmDetails_descriptor =
            getDescriptor().getMessageTypes().get(39);
          internal_static_android_studio_JvmDetails_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_JvmDetails_descriptor,
              new java.lang.String[] { "Name", "Version", "Vendor", "MinimumHeapSize", "MaximumHeapSize", "MaximumPermanentSpaceSize", "MaximumCodeCacheSize", "SoftReferenceLruPolicy", "GarbageCollector", });
          internal_static_android_studio_StudioPerformanceStats_descriptor =
            getDescriptor().getMessageTypes().get(40);
          internal_static_android_studio_StudioPerformanceStats_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_StudioPerformanceStats_descriptor,
              new java.lang.String[] { "UiFreezeTimeMs", });
          internal_static_android_studio_PercentileBucket_descriptor =
            getDescriptor().getMessageTypes().get(41);
          internal_static_android_studio_PercentileBucket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_PercentileBucket_descriptor,
              new java.lang.String[] { "TargetPercentile", "Value", "Count", });
          internal_static_android_studio_PercentileEstimator_descriptor =
            getDescriptor().getMessageTypes().get(42);
          internal_static_android_studio_PercentileEstimator_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_PercentileEstimator_descriptor,
              new java.lang.String[] { "RawSample", "Bucket", });
          internal_static_android_studio_LldbPercentileEstimator_descriptor =
            getDescriptor().getMessageTypes().get(43);
          internal_static_android_studio_LldbPercentileEstimator_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_LldbPercentileEstimator_descriptor,
              new java.lang.String[] { "Metric", "Estimator", });
          internal_static_android_studio_LldbPerformanceStats_descriptor =
            getDescriptor().getMessageTypes().get(44);
          internal_static_android_studio_LldbPerformanceStats_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_LldbPerformanceStats_descriptor,
              new java.lang.String[] { "Estimator", });
          internal_static_android_studio_StudioProjectChange_descriptor =
            getDescriptor().getMessageTypes().get(45);
          internal_static_android_studio_StudioProjectChange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_studio_StudioProjectChange_descriptor,
              new java.lang.String[] { "ProjectsOpen", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
