// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface AndroidAttributeOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string attribute_name = 1;
  /**
   * <code>optional string attribute_name = 1;</code>
   *
   * <pre>
   * Specifies an attribute name of an Android View class.
   * Only properties defined on Google View classes will be specified by name.
   * Properties defined on custom views will be left unspecified.
   * </pre>
   */
  boolean hasAttributeName();
  /**
   * <code>optional string attribute_name = 1;</code>
   *
   * <pre>
   * Specifies an attribute name of an Android View class.
   * Only properties defined on Google View classes will be specified by name.
   * Properties defined on custom views will be left unspecified.
   * </pre>
   */
  java.lang.String getAttributeName();
  /**
   * <code>optional string attribute_name = 1;</code>
   *
   * <pre>
   * Specifies an attribute name of an Android View class.
   * Only properties defined on Google View classes will be specified by name.
   * Properties defined on custom views will be left unspecified.
   * </pre>
   */
  com.google.protobuf.ByteString
      getAttributeNameBytes();

  // optional .android_studio.AndroidAttribute.AttributeNamespace attribute_namespace = 2;
  /**
   * <code>optional .android_studio.AndroidAttribute.AttributeNamespace attribute_namespace = 2;</code>
   *
   * <pre>
   * The namespace of this attribute
   * </pre>
   */
  boolean hasAttributeNamespace();
  /**
   * <code>optional .android_studio.AndroidAttribute.AttributeNamespace attribute_namespace = 2;</code>
   *
   * <pre>
   * The namespace of this attribute
   * </pre>
   */
  com.google.wireless.android.sdk.stats.AndroidAttribute.AttributeNamespace getAttributeNamespace();
}
