// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * Protobuf type {@code android_studio.CppHeadersViewEvent}
 *
 * <pre>
 * Metrics related to C++ header file view in Android Project
 * </pre>
 */
public  final class CppHeadersViewEvent extends
    com.google.protobuf.GeneratedMessage
    implements CppHeadersViewEventOrBuilder {
  // Use CppHeadersViewEvent.newBuilder() to construct.
  private CppHeadersViewEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private CppHeadersViewEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final CppHeadersViewEvent defaultInstance;
  public static CppHeadersViewEvent getDefaultInstance() {
    return defaultInstance;
  }

  public CppHeadersViewEvent getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private CppHeadersViewEvent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();
            com.google.wireless.android.sdk.stats.CppHeadersViewEvent.CppHeadersViewEventType value = com.google.wireless.android.sdk.stats.CppHeadersViewEvent.CppHeadersViewEventType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              type_ = value;
            }
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            eventDurationMs_ = input.readInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            nodeImmediateChildren_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CppHeadersViewEvent_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CppHeadersViewEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.CppHeadersViewEvent.class, com.google.wireless.android.sdk.stats.CppHeadersViewEvent.Builder.class);
  }

  public static com.google.protobuf.Parser<CppHeadersViewEvent> PARSER =
      new com.google.protobuf.AbstractParser<CppHeadersViewEvent>() {
    public CppHeadersViewEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CppHeadersViewEvent(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<CppHeadersViewEvent> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code android_studio.CppHeadersViewEvent.CppHeadersViewEventType}
   */
  public enum CppHeadersViewEventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_CPP_HEADERS_VIEW_EVENT = 0;</code>
     */
    UNKNOWN_CPP_HEADERS_VIEW_EVENT(0, 0),
    /**
     * <code>OPEN_TOP_INCLUDES_NODE = 1;</code>
     *
     * <pre>
     * Set when the user opens the top include node
     * </pre>
     */
    OPEN_TOP_INCLUDES_NODE(1, 1),
    ;

    /**
     * <code>UNKNOWN_CPP_HEADERS_VIEW_EVENT = 0;</code>
     */
    public static final int UNKNOWN_CPP_HEADERS_VIEW_EVENT_VALUE = 0;
    /**
     * <code>OPEN_TOP_INCLUDES_NODE = 1;</code>
     *
     * <pre>
     * Set when the user opens the top include node
     * </pre>
     */
    public static final int OPEN_TOP_INCLUDES_NODE_VALUE = 1;


    public final int getNumber() { return value; }

    public static CppHeadersViewEventType valueOf(int value) {
      switch (value) {
        case 0: return UNKNOWN_CPP_HEADERS_VIEW_EVENT;
        case 1: return OPEN_TOP_INCLUDES_NODE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CppHeadersViewEventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CppHeadersViewEventType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CppHeadersViewEventType>() {
            public CppHeadersViewEventType findValueByNumber(int number) {
              return CppHeadersViewEventType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.CppHeadersViewEvent.getDescriptor().getEnumTypes().get(0);
    }

    private static final CppHeadersViewEventType[] VALUES = values();

    public static CppHeadersViewEventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CppHeadersViewEventType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.CppHeadersViewEvent.CppHeadersViewEventType)
  }

  private int bitField0_;
  // optional .android_studio.CppHeadersViewEvent.CppHeadersViewEventType type = 1;
  public static final int TYPE_FIELD_NUMBER = 1;
  private com.google.wireless.android.sdk.stats.CppHeadersViewEvent.CppHeadersViewEventType type_;
  /**
   * <code>optional .android_studio.CppHeadersViewEvent.CppHeadersViewEventType type = 1;</code>
   *
   * <pre>
   * Metrics related to enhanced C++ header files view enabled by
   * under ENABLE_ENHANCED_NATIVE_HEADER_SUPPORT flag
   * </pre>
   */
  public boolean hasType() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .android_studio.CppHeadersViewEvent.CppHeadersViewEventType type = 1;</code>
   *
   * <pre>
   * Metrics related to enhanced C++ header files view enabled by
   * under ENABLE_ENHANCED_NATIVE_HEADER_SUPPORT flag
   * </pre>
   */
  public com.google.wireless.android.sdk.stats.CppHeadersViewEvent.CppHeadersViewEventType getType() {
    return type_;
  }

  // optional int64 event_duration_ms = 2;
  public static final int EVENT_DURATION_MS_FIELD_NUMBER = 2;
  private long eventDurationMs_;
  /**
   * <code>optional int64 event_duration_ms = 2;</code>
   *
   * <pre>
   * The amount of time taken for the event to complete in milliseconds.
   * </pre>
   */
  public boolean hasEventDurationMs() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int64 event_duration_ms = 2;</code>
   *
   * <pre>
   * The amount of time taken for the event to complete in milliseconds.
   * </pre>
   */
  public long getEventDurationMs() {
    return eventDurationMs_;
  }

  // optional int32 node_immediate_children = 3;
  public static final int NODE_IMMEDIATE_CHILDREN_FIELD_NUMBER = 3;
  private int nodeImmediateChildren_;
  /**
   * <code>optional int32 node_immediate_children = 3;</code>
   *
   * <pre>
   * The count of the immediate children of the node that was opened by
   * the user.
   * </pre>
   */
  public boolean hasNodeImmediateChildren() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int32 node_immediate_children = 3;</code>
   *
   * <pre>
   * The count of the immediate children of the node that was opened by
   * the user.
   * </pre>
   */
  public int getNodeImmediateChildren() {
    return nodeImmediateChildren_;
  }

  private void initFields() {
    type_ = com.google.wireless.android.sdk.stats.CppHeadersViewEvent.CppHeadersViewEventType.UNKNOWN_CPP_HEADERS_VIEW_EVENT;
    eventDurationMs_ = 0L;
    nodeImmediateChildren_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeEnum(1, type_.getNumber());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(2, eventDurationMs_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, nodeImmediateChildren_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_.getNumber());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, eventDurationMs_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, nodeImmediateChildren_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.google.wireless.android.sdk.stats.CppHeadersViewEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.CppHeadersViewEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.CppHeadersViewEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.CppHeadersViewEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.CppHeadersViewEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.CppHeadersViewEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.CppHeadersViewEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.CppHeadersViewEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.CppHeadersViewEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.CppHeadersViewEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.CppHeadersViewEvent prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code android_studio.CppHeadersViewEvent}
   *
   * <pre>
   * Metrics related to C++ header file view in Android Project
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.google.wireless.android.sdk.stats.CppHeadersViewEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CppHeadersViewEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CppHeadersViewEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.CppHeadersViewEvent.class, com.google.wireless.android.sdk.stats.CppHeadersViewEvent.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.CppHeadersViewEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      type_ = com.google.wireless.android.sdk.stats.CppHeadersViewEvent.CppHeadersViewEventType.UNKNOWN_CPP_HEADERS_VIEW_EVENT;
      bitField0_ = (bitField0_ & ~0x00000001);
      eventDurationMs_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      nodeImmediateChildren_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CppHeadersViewEvent_descriptor;
    }

    public com.google.wireless.android.sdk.stats.CppHeadersViewEvent getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.CppHeadersViewEvent.getDefaultInstance();
    }

    public com.google.wireless.android.sdk.stats.CppHeadersViewEvent build() {
      com.google.wireless.android.sdk.stats.CppHeadersViewEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.wireless.android.sdk.stats.CppHeadersViewEvent buildPartial() {
      com.google.wireless.android.sdk.stats.CppHeadersViewEvent result = new com.google.wireless.android.sdk.stats.CppHeadersViewEvent(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.eventDurationMs_ = eventDurationMs_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.nodeImmediateChildren_ = nodeImmediateChildren_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.CppHeadersViewEvent) {
        return mergeFrom((com.google.wireless.android.sdk.stats.CppHeadersViewEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.CppHeadersViewEvent other) {
      if (other == com.google.wireless.android.sdk.stats.CppHeadersViewEvent.getDefaultInstance()) return this;
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasEventDurationMs()) {
        setEventDurationMs(other.getEventDurationMs());
      }
      if (other.hasNodeImmediateChildren()) {
        setNodeImmediateChildren(other.getNodeImmediateChildren());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.wireless.android.sdk.stats.CppHeadersViewEvent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.wireless.android.sdk.stats.CppHeadersViewEvent) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional .android_studio.CppHeadersViewEvent.CppHeadersViewEventType type = 1;
    private com.google.wireless.android.sdk.stats.CppHeadersViewEvent.CppHeadersViewEventType type_ = com.google.wireless.android.sdk.stats.CppHeadersViewEvent.CppHeadersViewEventType.UNKNOWN_CPP_HEADERS_VIEW_EVENT;
    /**
     * <code>optional .android_studio.CppHeadersViewEvent.CppHeadersViewEventType type = 1;</code>
     *
     * <pre>
     * Metrics related to enhanced C++ header files view enabled by
     * under ENABLE_ENHANCED_NATIVE_HEADER_SUPPORT flag
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .android_studio.CppHeadersViewEvent.CppHeadersViewEventType type = 1;</code>
     *
     * <pre>
     * Metrics related to enhanced C++ header files view enabled by
     * under ENABLE_ENHANCED_NATIVE_HEADER_SUPPORT flag
     * </pre>
     */
    public com.google.wireless.android.sdk.stats.CppHeadersViewEvent.CppHeadersViewEventType getType() {
      return type_;
    }
    /**
     * <code>optional .android_studio.CppHeadersViewEvent.CppHeadersViewEventType type = 1;</code>
     *
     * <pre>
     * Metrics related to enhanced C++ header files view enabled by
     * under ENABLE_ENHANCED_NATIVE_HEADER_SUPPORT flag
     * </pre>
     */
    public Builder setType(com.google.wireless.android.sdk.stats.CppHeadersViewEvent.CppHeadersViewEventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.CppHeadersViewEvent.CppHeadersViewEventType type = 1;</code>
     *
     * <pre>
     * Metrics related to enhanced C++ header files view enabled by
     * under ENABLE_ENHANCED_NATIVE_HEADER_SUPPORT flag
     * </pre>
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = com.google.wireless.android.sdk.stats.CppHeadersViewEvent.CppHeadersViewEventType.UNKNOWN_CPP_HEADERS_VIEW_EVENT;
      onChanged();
      return this;
    }

    // optional int64 event_duration_ms = 2;
    private long eventDurationMs_ ;
    /**
     * <code>optional int64 event_duration_ms = 2;</code>
     *
     * <pre>
     * The amount of time taken for the event to complete in milliseconds.
     * </pre>
     */
    public boolean hasEventDurationMs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 event_duration_ms = 2;</code>
     *
     * <pre>
     * The amount of time taken for the event to complete in milliseconds.
     * </pre>
     */
    public long getEventDurationMs() {
      return eventDurationMs_;
    }
    /**
     * <code>optional int64 event_duration_ms = 2;</code>
     *
     * <pre>
     * The amount of time taken for the event to complete in milliseconds.
     * </pre>
     */
    public Builder setEventDurationMs(long value) {
      bitField0_ |= 0x00000002;
      eventDurationMs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 event_duration_ms = 2;</code>
     *
     * <pre>
     * The amount of time taken for the event to complete in milliseconds.
     * </pre>
     */
    public Builder clearEventDurationMs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      eventDurationMs_ = 0L;
      onChanged();
      return this;
    }

    // optional int32 node_immediate_children = 3;
    private int nodeImmediateChildren_ ;
    /**
     * <code>optional int32 node_immediate_children = 3;</code>
     *
     * <pre>
     * The count of the immediate children of the node that was opened by
     * the user.
     * </pre>
     */
    public boolean hasNodeImmediateChildren() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 node_immediate_children = 3;</code>
     *
     * <pre>
     * The count of the immediate children of the node that was opened by
     * the user.
     * </pre>
     */
    public int getNodeImmediateChildren() {
      return nodeImmediateChildren_;
    }
    /**
     * <code>optional int32 node_immediate_children = 3;</code>
     *
     * <pre>
     * The count of the immediate children of the node that was opened by
     * the user.
     * </pre>
     */
    public Builder setNodeImmediateChildren(int value) {
      bitField0_ |= 0x00000004;
      nodeImmediateChildren_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 node_immediate_children = 3;</code>
     *
     * <pre>
     * The count of the immediate children of the node that was opened by
     * the user.
     * </pre>
     */
    public Builder clearNodeImmediateChildren() {
      bitField0_ = (bitField0_ & ~0x00000004);
      nodeImmediateChildren_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:android_studio.CppHeadersViewEvent)
  }

  static {
    defaultInstance = new CppHeadersViewEvent(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:android_studio.CppHeadersViewEvent)
}

