// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface DeviceInfoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string anonymized_serial_number = 1;
  /**
   * <code>optional string anonymized_serial_number = 1;</code>
   *
   * <pre>
   * serial number of the device, salted &amp; sha256ed on the client.
   * </pre>
   */
  boolean hasAnonymizedSerialNumber();
  /**
   * <code>optional string anonymized_serial_number = 1;</code>
   *
   * <pre>
   * serial number of the device, salted &amp; sha256ed on the client.
   * </pre>
   */
  java.lang.String getAnonymizedSerialNumber();
  /**
   * <code>optional string anonymized_serial_number = 1;</code>
   *
   * <pre>
   * serial number of the device, salted &amp; sha256ed on the client.
   * </pre>
   */
  com.google.protobuf.ByteString
      getAnonymizedSerialNumberBytes();

  // optional string build_tags = 2;
  /**
   * <code>optional string build_tags = 2;</code>
   *
   * <pre>
   * Tags used to build the android version on this device.
   * e.g. 'release-keys' or 'test-keys' or 'A100_V001'
   * </pre>
   */
  boolean hasBuildTags();
  /**
   * <code>optional string build_tags = 2;</code>
   *
   * <pre>
   * Tags used to build the android version on this device.
   * e.g. 'release-keys' or 'test-keys' or 'A100_V001'
   * </pre>
   */
  java.lang.String getBuildTags();
  /**
   * <code>optional string build_tags = 2;</code>
   *
   * <pre>
   * Tags used to build the android version on this device.
   * e.g. 'release-keys' or 'test-keys' or 'A100_V001'
   * </pre>
   */
  com.google.protobuf.ByteString
      getBuildTagsBytes();

  // optional string build_type = 3;
  /**
   * <code>optional string build_type = 3;</code>
   *
   * <pre>
   * Type of build this device is running.
   * e.g. 'user' or 'userdebug' or 'eng' or 'alphabuild'
   * </pre>
   */
  boolean hasBuildType();
  /**
   * <code>optional string build_type = 3;</code>
   *
   * <pre>
   * Type of build this device is running.
   * e.g. 'user' or 'userdebug' or 'eng' or 'alphabuild'
   * </pre>
   */
  java.lang.String getBuildType();
  /**
   * <code>optional string build_type = 3;</code>
   *
   * <pre>
   * Type of build this device is running.
   * e.g. 'user' or 'userdebug' or 'eng' or 'alphabuild'
   * </pre>
   */
  com.google.protobuf.ByteString
      getBuildTypeBytes();

  // optional string build_version_release = 4;
  /**
   * <code>optional string build_version_release = 4;</code>
   *
   * <pre>
   * Android version e.g. '5.1.1'
   * </pre>
   */
  boolean hasBuildVersionRelease();
  /**
   * <code>optional string build_version_release = 4;</code>
   *
   * <pre>
   * Android version e.g. '5.1.1'
   * </pre>
   */
  java.lang.String getBuildVersionRelease();
  /**
   * <code>optional string build_version_release = 4;</code>
   *
   * <pre>
   * Android version e.g. '5.1.1'
   * </pre>
   */
  com.google.protobuf.ByteString
      getBuildVersionReleaseBytes();

  // optional int32 build_api_level = 5;
  /**
   * <code>optional int32 build_api_level = 5;</code>
   *
   * <pre>
   * Historic: doesn't support api levels for code names such as 'N'.
   * </pre>
   */
  boolean hasBuildApiLevel();
  /**
   * <code>optional int32 build_api_level = 5;</code>
   *
   * <pre>
   * Historic: doesn't support api levels for code names such as 'N'.
   * </pre>
   */
  int getBuildApiLevel();

  // optional .android_studio.DeviceInfo.ApplicationBinaryInterface cpu_abi = 6;
  /**
   * <code>optional .android_studio.DeviceInfo.ApplicationBinaryInterface cpu_abi = 6;</code>
   *
   * <pre>
   * ABI of the device, e.g. 'armeabi-v7a' or 'x86'
   * </pre>
   */
  boolean hasCpuAbi();
  /**
   * <code>optional .android_studio.DeviceInfo.ApplicationBinaryInterface cpu_abi = 6;</code>
   *
   * <pre>
   * ABI of the device, e.g. 'armeabi-v7a' or 'x86'
   * </pre>
   */
  com.google.wireless.android.sdk.stats.DeviceInfo.ApplicationBinaryInterface getCpuAbi();

  // optional string manufacturer = 7;
  /**
   * <code>optional string manufacturer = 7;</code>
   *
   * <pre>
   * Device manufacturer, e.g. 'Motorola' or 'Samsung'
   * </pre>
   */
  boolean hasManufacturer();
  /**
   * <code>optional string manufacturer = 7;</code>
   *
   * <pre>
   * Device manufacturer, e.g. 'Motorola' or 'Samsung'
   * </pre>
   */
  java.lang.String getManufacturer();
  /**
   * <code>optional string manufacturer = 7;</code>
   *
   * <pre>
   * Device manufacturer, e.g. 'Motorola' or 'Samsung'
   * </pre>
   */
  com.google.protobuf.ByteString
      getManufacturerBytes();

  // optional string model = 8;
  /**
   * <code>optional string model = 8;</code>
   *
   * <pre>
   * Device model, e.g. 'Nexus 5' or 'GT-I9500'.
   * </pre>
   */
  boolean hasModel();
  /**
   * <code>optional string model = 8;</code>
   *
   * <pre>
   * Device model, e.g. 'Nexus 5' or 'GT-I9500'.
   * </pre>
   */
  java.lang.String getModel();
  /**
   * <code>optional string model = 8;</code>
   *
   * <pre>
   * Device model, e.g. 'Nexus 5' or 'GT-I9500'.
   * </pre>
   */
  com.google.protobuf.ByteString
      getModelBytes();

  // optional .android_studio.DeviceInfo.DeviceType device_type = 9;
  /**
   * <code>optional .android_studio.DeviceInfo.DeviceType device_type = 9;</code>
   *
   * <pre>
   * What kind of device is this? Physicial/Emulator/Cloud etc...
   * </pre>
   */
  boolean hasDeviceType();
  /**
   * <code>optional .android_studio.DeviceInfo.DeviceType device_type = 9;</code>
   *
   * <pre>
   * What kind of device is this? Physicial/Emulator/Cloud etc...
   * </pre>
   */
  com.google.wireless.android.sdk.stats.DeviceInfo.DeviceType getDeviceType();

  // optional string build_api_level_full = 10;
  /**
   * <code>optional string build_api_level_full = 10;</code>
   *
   * <pre>
   * android api level  e.g. '23' or 'N'
   * </pre>
   */
  boolean hasBuildApiLevelFull();
  /**
   * <code>optional string build_api_level_full = 10;</code>
   *
   * <pre>
   * android api level  e.g. '23' or 'N'
   * </pre>
   */
  java.lang.String getBuildApiLevelFull();
  /**
   * <code>optional string build_api_level_full = 10;</code>
   *
   * <pre>
   * android api level  e.g. '23' or 'N'
   * </pre>
   */
  com.google.protobuf.ByteString
      getBuildApiLevelFullBytes();
}
