// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface EmulatorDetailsOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional .android_studio.EmulatorDetails.GuestCpuArchitecture guest_arch = 1;
  /**
   * <code>optional .android_studio.EmulatorDetails.GuestCpuArchitecture guest_arch = 1;</code>
   *
   * <pre>
   * Cpu architecture of the guest.
   * </pre>
   */
  boolean hasGuestArch();
  /**
   * <code>optional .android_studio.EmulatorDetails.GuestCpuArchitecture guest_arch = 1;</code>
   *
   * <pre>
   * Cpu architecture of the guest.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorDetails.GuestCpuArchitecture getGuestArch();

  // optional int64 system_time = 2;
  /**
   * <code>optional int64 system_time = 2;</code>
   *
   * <pre>
   * cpu time spent in kernel mode in milliseconds since last metrics report.
   * </pre>
   */
  boolean hasSystemTime();
  /**
   * <code>optional int64 system_time = 2;</code>
   *
   * <pre>
   * cpu time spent in kernel mode in milliseconds since last metrics report.
   * </pre>
   */
  long getSystemTime();

  // optional int64 user_time = 3;
  /**
   * <code>optional int64 user_time = 3;</code>
   *
   * <pre>
   * cpu time spent in user mode in milliseconds since last metrics report.
   * </pre>
   */
  boolean hasUserTime();
  /**
   * <code>optional int64 user_time = 3;</code>
   *
   * <pre>
   * cpu time spent in user mode in milliseconds since last metrics report.
   * </pre>
   */
  long getUserTime();

  // optional int64 crashes = 4;
  /**
   * <code>optional int64 crashes = 4;</code>
   *
   * <pre>
   * number of crashes since last metrics report.
   * </pre>
   */
  boolean hasCrashes();
  /**
   * <code>optional int64 crashes = 4;</code>
   *
   * <pre>
   * number of crashes since last metrics report.
   * </pre>
   */
  long getCrashes();

  // optional int64 wall_time = 5;
  /**
   * <code>optional int64 wall_time = 5;</code>
   *
   * <pre>
   * real time in milliseconds since last metrics report.
   * </pre>
   */
  boolean hasWallTime();
  /**
   * <code>optional int64 wall_time = 5;</code>
   *
   * <pre>
   * real time in milliseconds since last metrics report.
   * </pre>
   */
  long getWallTime();

  // optional bool exit_started = 6;
  /**
   * <code>optional bool exit_started = 6;</code>
   *
   * <pre>
   * True iff a crash occurred while process started its exit routines.
   * </pre>
   */
  boolean hasExitStarted();
  /**
   * <code>optional bool exit_started = 6;</code>
   *
   * <pre>
   * True iff a crash occurred while process started its exit routines.
   * </pre>
   */
  boolean getExitStarted();

  // optional int64 guest_api_level = 7;
  /**
   * <code>optional int64 guest_api_level = 7;</code>
   *
   * <pre>
   * The API level of the running guest image.
   * </pre>
   */
  boolean hasGuestApiLevel();
  /**
   * <code>optional int64 guest_api_level = 7;</code>
   *
   * <pre>
   * The API level of the running guest image.
   * </pre>
   */
  long getGuestApiLevel();

  // optional bool guest_gpu_enabled = 8;
  /**
   * <code>optional bool guest_gpu_enabled = 8;</code>
   *
   * <pre>
   * The value of guest gpu option (ro.kernel.qemu.gles)
   * </pre>
   */
  boolean hasGuestGpuEnabled();
  /**
   * <code>optional bool guest_gpu_enabled = 8;</code>
   *
   * <pre>
   * The value of guest gpu option (ro.kernel.qemu.gles)
   * </pre>
   */
  boolean getGuestGpuEnabled();

  // optional bool is_opengl_alive = 10;
  /**
   * <code>optional bool is_opengl_alive = 10;</code>
   *
   * <pre>
   * True if we were able to correctly initialize opengl on the host.
   * </pre>
   */
  boolean hasIsOpenglAlive();
  /**
   * <code>optional bool is_opengl_alive = 10;</code>
   *
   * <pre>
   * True if we were able to correctly initialize opengl on the host.
   * </pre>
   */
  boolean getIsOpenglAlive();

  // optional .android_studio.EmulatorDetails.EmulatorAdbLiveness adb_liveness = 11;
  /**
   * <code>optional .android_studio.EmulatorDetails.EmulatorAdbLiveness adb_liveness = 11;</code>
   *
   * <pre>
   * Connectivity from adb of the running emulator instance.
   * </pre>
   */
  boolean hasAdbLiveness();
  /**
   * <code>optional .android_studio.EmulatorDetails.EmulatorAdbLiveness adb_liveness = 11;</code>
   *
   * <pre>
   * Connectivity from adb of the running emulator instance.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorDetails.EmulatorAdbLiveness getAdbLiveness();

  // optional .android_studio.EmulatorGuestGlInfo guest_gl = 12;
  /**
   * <code>optional .android_studio.EmulatorGuestGlInfo guest_gl = 12;</code>
   *
   * <pre>
   * Information about the gl implementation in the guest image.
   * </pre>
   */
  boolean hasGuestGl();
  /**
   * <code>optional .android_studio.EmulatorGuestGlInfo guest_gl = 12;</code>
   *
   * <pre>
   * Information about the gl implementation in the guest image.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorGuestGlInfo getGuestGl();
  /**
   * <code>optional .android_studio.EmulatorGuestGlInfo guest_gl = 12;</code>
   *
   * <pre>
   * Information about the gl implementation in the guest image.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorGuestGlInfoOrBuilder getGuestGlOrBuilder();

  // repeated .android_studio.EmulatorGpuInfo host_gpu = 13;
  /**
   * <code>repeated .android_studio.EmulatorGpuInfo host_gpu = 13;</code>
   *
   * <pre>
   * Information about the host GPUs (one per GPU).
   * </pre>
   */
  java.util.List<com.google.wireless.android.sdk.stats.EmulatorGpuInfo> 
      getHostGpuList();
  /**
   * <code>repeated .android_studio.EmulatorGpuInfo host_gpu = 13;</code>
   *
   * <pre>
   * Information about the host GPUs (one per GPU).
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorGpuInfo getHostGpu(int index);
  /**
   * <code>repeated .android_studio.EmulatorGpuInfo host_gpu = 13;</code>
   *
   * <pre>
   * Information about the host GPUs (one per GPU).
   * </pre>
   */
  int getHostGpuCount();
  /**
   * <code>repeated .android_studio.EmulatorGpuInfo host_gpu = 13;</code>
   *
   * <pre>
   * Information about the host GPUs (one per GPU).
   * </pre>
   */
  java.util.List<? extends com.google.wireless.android.sdk.stats.EmulatorGpuInfoOrBuilder> 
      getHostGpuOrBuilderList();
  /**
   * <code>repeated .android_studio.EmulatorGpuInfo host_gpu = 13;</code>
   *
   * <pre>
   * Information about the host GPUs (one per GPU).
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorGpuInfoOrBuilder getHostGpuOrBuilder(
      int index);

  // optional .android_studio.EmulatorDetails.EmulatorSessionPhase session_phase = 14;
  /**
   * <code>optional .android_studio.EmulatorDetails.EmulatorSessionPhase session_phase = 14;</code>
   *
   * <pre>
   * The "phase" of an emulator session where crash happened.
   * </pre>
   */
  boolean hasSessionPhase();
  /**
   * <code>optional .android_studio.EmulatorDetails.EmulatorSessionPhase session_phase = 14;</code>
   *
   * <pre>
   * The "phase" of an emulator session where crash happened.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorDetails.EmulatorSessionPhase getSessionPhase();

  // optional string core_version = 15;
  /**
   * <code>optional string core_version = 15;</code>
   *
   * <pre>
   * The emulator core version (e.g. QEMU engine's version).
   * </pre>
   */
  boolean hasCoreVersion();
  /**
   * <code>optional string core_version = 15;</code>
   *
   * <pre>
   * The emulator core version (e.g. QEMU engine's version).
   * </pre>
   */
  java.lang.String getCoreVersion();
  /**
   * <code>optional string core_version = 15;</code>
   *
   * <pre>
   * The emulator core version (e.g. QEMU engine's version).
   * </pre>
   */
  com.google.protobuf.ByteString
      getCoreVersionBytes();

  // optional .android_studio.EmulatorDetails.EmulatorRenderer renderer = 16;
  /**
   * <code>optional .android_studio.EmulatorDetails.EmulatorRenderer renderer = 16;</code>
   *
   * <pre>
   * Renderer of the current emulator session.
   * </pre>
   */
  boolean hasRenderer();
  /**
   * <code>optional .android_studio.EmulatorDetails.EmulatorRenderer renderer = 16;</code>
   *
   * <pre>
   * Renderer of the current emulator session.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorDetails.EmulatorRenderer getRenderer();

  // optional .android_studio.EmulatorFeatures used_features = 17;
  /**
   * <code>optional .android_studio.EmulatorFeatures used_features = 17;</code>
   *
   * <pre>
   * Flags for the used UI featurs.
   * </pre>
   */
  boolean hasUsedFeatures();
  /**
   * <code>optional .android_studio.EmulatorFeatures used_features = 17;</code>
   *
   * <pre>
   * Flags for the used UI featurs.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorFeatures getUsedFeatures();
  /**
   * <code>optional .android_studio.EmulatorFeatures used_features = 17;</code>
   *
   * <pre>
   * Flags for the used UI featurs.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorFeaturesOrBuilder getUsedFeaturesOrBuilder();

  // optional .android_studio.EmulatorAvdInfo avd_info = 18;
  /**
   * <code>optional .android_studio.EmulatorAvdInfo avd_info = 18;</code>
   *
   * <pre>
   * Information about the currently loaded AVD.
   * </pre>
   */
  boolean hasAvdInfo();
  /**
   * <code>optional .android_studio.EmulatorAvdInfo avd_info = 18;</code>
   *
   * <pre>
   * Information about the currently loaded AVD.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorAvdInfo getAvdInfo();
  /**
   * <code>optional .android_studio.EmulatorAvdInfo avd_info = 18;</code>
   *
   * <pre>
   * Information about the currently loaded AVD.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorAvdInfoOrBuilder getAvdInfoOrBuilder();

  // optional .android_studio.EmulatorFeatureFlagState feature_flag_state = 19;
  /**
   * <code>optional .android_studio.EmulatorFeatureFlagState feature_flag_state = 19;</code>
   *
   * <pre>
   * State tracking emulator feature flag enable/disable.
   * </pre>
   */
  boolean hasFeatureFlagState();
  /**
   * <code>optional .android_studio.EmulatorFeatureFlagState feature_flag_state = 19;</code>
   *
   * <pre>
   * State tracking emulator feature flag enable/disable.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorFeatureFlagState getFeatureFlagState();
  /**
   * <code>optional .android_studio.EmulatorFeatureFlagState feature_flag_state = 19;</code>
   *
   * <pre>
   * State tracking emulator feature flag enable/disable.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorFeatureFlagStateOrBuilder getFeatureFlagStateOrBuilder();

  // optional .android_studio.EmulatorDetails.EmulatorHypervisor hypervisor = 20;
  /**
   * <code>optional .android_studio.EmulatorDetails.EmulatorHypervisor hypervisor = 20;</code>
   *
   * <pre>
   * Hypervisor used in current session.
   * </pre>
   */
  boolean hasHypervisor();
  /**
   * <code>optional .android_studio.EmulatorDetails.EmulatorHypervisor hypervisor = 20;</code>
   *
   * <pre>
   * Hypervisor used in current session.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorDetails.EmulatorHypervisor getHypervisor();

  // optional .android_studio.EmulatorQuickbootLoad quickboot_load = 21;
  /**
   * <code>optional .android_studio.EmulatorQuickbootLoad quickboot_load = 21;</code>
   *
   * <pre>
   * Information about quickboot status of the current session.
   * </pre>
   */
  boolean hasQuickbootLoad();
  /**
   * <code>optional .android_studio.EmulatorQuickbootLoad quickboot_load = 21;</code>
   *
   * <pre>
   * Information about quickboot status of the current session.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorQuickbootLoad getQuickbootLoad();
  /**
   * <code>optional .android_studio.EmulatorQuickbootLoad quickboot_load = 21;</code>
   *
   * <pre>
   * Information about quickboot status of the current session.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorQuickbootLoadOrBuilder getQuickbootLoadOrBuilder();

  // optional .android_studio.EmulatorQuickbootSave quickboot_save = 22;
  /**
   * <code>optional .android_studio.EmulatorQuickbootSave quickboot_save = 22;</code>
   */
  boolean hasQuickbootSave();
  /**
   * <code>optional .android_studio.EmulatorQuickbootSave quickboot_save = 22;</code>
   */
  com.google.wireless.android.sdk.stats.EmulatorQuickbootSave getQuickbootSave();
  /**
   * <code>optional .android_studio.EmulatorQuickbootSave quickboot_save = 22;</code>
   */
  com.google.wireless.android.sdk.stats.EmulatorQuickbootSaveOrBuilder getQuickbootSaveOrBuilder();

  // optional .android_studio.EmulatorGLESUsages gles_usages = 23;
  /**
   * <code>optional .android_studio.EmulatorGLESUsages gles_usages = 23;</code>
   *
   * <pre>
   * Track GLES command usages
   * </pre>
   */
  boolean hasGlesUsages();
  /**
   * <code>optional .android_studio.EmulatorGLESUsages gles_usages = 23;</code>
   *
   * <pre>
   * Track GLES command usages
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorGLESUsages getGlesUsages();
  /**
   * <code>optional .android_studio.EmulatorGLESUsages gles_usages = 23;</code>
   *
   * <pre>
   * Track GLES command usages
   * </pre>
   */
  com.google.wireless.android.sdk.stats.EmulatorGLESUsagesOrBuilder getGlesUsagesOrBuilder();
}
