// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * Protobuf type {@code android_studio.EmulatorUiEvent}
 *
 * <pre>
 * Describes a user clicking on some part of the Emulator UI.
 * </pre>
 */
public  final class EmulatorUiEvent extends
    com.google.protobuf.GeneratedMessage
    implements EmulatorUiEventOrBuilder {
  // Use EmulatorUiEvent.newBuilder() to construct.
  private EmulatorUiEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private EmulatorUiEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final EmulatorUiEvent defaultInstance;
  public static EmulatorUiEvent getDefaultInstance() {
    return defaultInstance;
  }

  public EmulatorUiEvent getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private EmulatorUiEvent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            elementId_ = input.readBytes();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventType value = com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              type_ = value;
            }
            break;
          }
          case 24: {
            int rawValue = input.readEnum();
            com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventContext value = com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventContext.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(3, rawValue);
            } else {
              bitField0_ |= 0x00000004;
              context_ = value;
            }
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            value_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorUiEvent_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorUiEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.EmulatorUiEvent.class, com.google.wireless.android.sdk.stats.EmulatorUiEvent.Builder.class);
  }

  public static com.google.protobuf.Parser<EmulatorUiEvent> PARSER =
      new com.google.protobuf.AbstractParser<EmulatorUiEvent>() {
    public EmulatorUiEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmulatorUiEvent(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<EmulatorUiEvent> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code android_studio.EmulatorUiEvent.EmulatorUiEventType}
   *
   * <pre>
   * Tracks the type of the emulator UI Event.
   * </pre>
   */
  public enum EmulatorUiEventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKONWN_EMULATOR_UI_EVENT_TYPE = 0;</code>
     */
    UNKONWN_EMULATOR_UI_EVENT_TYPE(0, 0),
    /**
     * <code>BUTTON_PRESS = 1;</code>
     */
    BUTTON_PRESS(1, 1),
    /**
     * <code>OPTION_SET_TO_NON_DEFAULT = 2;</code>
     *
     * <pre>
     * Generated when a user action changes the value of certain field from
     * its default value.
     * </pre>
     */
    OPTION_SET_TO_NON_DEFAULT(2, 2),
    /**
     * <code>OPTION_SELECTED = 3;</code>
     *
     * <pre>
     * Generated to report the index of an option selected by the user in a
     * drop-down menu / radio button etc.
     * </pre>
     */
    OPTION_SELECTED(3, 3),
    /**
     * <code>LONG_PROCESSING_TIME_US = 4;</code>
     *
     * <pre>
     * Generated on event processing end, |value| is time in microseconds.
     * Is only sent if the processing time is considered 'long' in the emulator,
     * which is determined in the emulator code itself.
     * </pre>
     */
    LONG_PROCESSING_TIME_US(4, 4),
    ;

    /**
     * <code>UNKONWN_EMULATOR_UI_EVENT_TYPE = 0;</code>
     */
    public static final int UNKONWN_EMULATOR_UI_EVENT_TYPE_VALUE = 0;
    /**
     * <code>BUTTON_PRESS = 1;</code>
     */
    public static final int BUTTON_PRESS_VALUE = 1;
    /**
     * <code>OPTION_SET_TO_NON_DEFAULT = 2;</code>
     *
     * <pre>
     * Generated when a user action changes the value of certain field from
     * its default value.
     * </pre>
     */
    public static final int OPTION_SET_TO_NON_DEFAULT_VALUE = 2;
    /**
     * <code>OPTION_SELECTED = 3;</code>
     *
     * <pre>
     * Generated to report the index of an option selected by the user in a
     * drop-down menu / radio button etc.
     * </pre>
     */
    public static final int OPTION_SELECTED_VALUE = 3;
    /**
     * <code>LONG_PROCESSING_TIME_US = 4;</code>
     *
     * <pre>
     * Generated on event processing end, |value| is time in microseconds.
     * Is only sent if the processing time is considered 'long' in the emulator,
     * which is determined in the emulator code itself.
     * </pre>
     */
    public static final int LONG_PROCESSING_TIME_US_VALUE = 4;


    public final int getNumber() { return value; }

    public static EmulatorUiEventType valueOf(int value) {
      switch (value) {
        case 0: return UNKONWN_EMULATOR_UI_EVENT_TYPE;
        case 1: return BUTTON_PRESS;
        case 2: return OPTION_SET_TO_NON_DEFAULT;
        case 3: return OPTION_SELECTED;
        case 4: return LONG_PROCESSING_TIME_US;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EmulatorUiEventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EmulatorUiEventType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EmulatorUiEventType>() {
            public EmulatorUiEventType findValueByNumber(int number) {
              return EmulatorUiEventType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.EmulatorUiEvent.getDescriptor().getEnumTypes().get(0);
    }

    private static final EmulatorUiEventType[] VALUES = values();

    public static EmulatorUiEventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EmulatorUiEventType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.EmulatorUiEvent.EmulatorUiEventType)
  }

  /**
   * Protobuf enum {@code android_studio.EmulatorUiEvent.EmulatorUiEventContext}
   *
   * <pre>
   * Tracks the context of the Emulator UI.
   * </pre>
   */
  public enum EmulatorUiEventContext
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_EMULATOR_UI_EVENT_CONTEXT = 0;</code>
     */
    UNKNOWN_EMULATOR_UI_EVENT_CONTEXT(0, 0),
    /**
     * <code>EXTENDED_WINDOW_OPEN = 1;</code>
     */
    EXTENDED_WINDOW_OPEN(1, 1),
    ;

    /**
     * <code>UNKNOWN_EMULATOR_UI_EVENT_CONTEXT = 0;</code>
     */
    public static final int UNKNOWN_EMULATOR_UI_EVENT_CONTEXT_VALUE = 0;
    /**
     * <code>EXTENDED_WINDOW_OPEN = 1;</code>
     */
    public static final int EXTENDED_WINDOW_OPEN_VALUE = 1;


    public final int getNumber() { return value; }

    public static EmulatorUiEventContext valueOf(int value) {
      switch (value) {
        case 0: return UNKNOWN_EMULATOR_UI_EVENT_CONTEXT;
        case 1: return EXTENDED_WINDOW_OPEN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EmulatorUiEventContext>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EmulatorUiEventContext>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EmulatorUiEventContext>() {
            public EmulatorUiEventContext findValueByNumber(int number) {
              return EmulatorUiEventContext.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.EmulatorUiEvent.getDescriptor().getEnumTypes().get(1);
    }

    private static final EmulatorUiEventContext[] VALUES = values();

    public static EmulatorUiEventContext valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EmulatorUiEventContext(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.EmulatorUiEvent.EmulatorUiEventContext)
  }

  private int bitField0_;
  // optional string element_id = 1;
  public static final int ELEMENT_ID_FIELD_NUMBER = 1;
  private java.lang.Object elementId_;
  /**
   * <code>optional string element_id = 1;</code>
   *
   * <pre>
   * Id of the UI element, baked in the emulator binary.
   * </pre>
   */
  public boolean hasElementId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string element_id = 1;</code>
   *
   * <pre>
   * Id of the UI element, baked in the emulator binary.
   * </pre>
   */
  public java.lang.String getElementId() {
    java.lang.Object ref = elementId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        elementId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string element_id = 1;</code>
   *
   * <pre>
   * Id of the UI element, baked in the emulator binary.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getElementIdBytes() {
    java.lang.Object ref = elementId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      elementId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional .android_studio.EmulatorUiEvent.EmulatorUiEventType type = 2;
  public static final int TYPE_FIELD_NUMBER = 2;
  private com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventType type_;
  /**
   * <code>optional .android_studio.EmulatorUiEvent.EmulatorUiEventType type = 2;</code>
   *
   * <pre>
   * The type of UI event
   * </pre>
   */
  public boolean hasType() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .android_studio.EmulatorUiEvent.EmulatorUiEventType type = 2;</code>
   *
   * <pre>
   * The type of UI event
   * </pre>
   */
  public com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventType getType() {
    return type_;
  }

  // optional .android_studio.EmulatorUiEvent.EmulatorUiEventContext context = 3;
  public static final int CONTEXT_FIELD_NUMBER = 3;
  private com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventContext context_;
  /**
   * <code>optional .android_studio.EmulatorUiEvent.EmulatorUiEventContext context = 3;</code>
   *
   * <pre>
   * The current context of the event.
   * </pre>
   */
  public boolean hasContext() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional .android_studio.EmulatorUiEvent.EmulatorUiEventContext context = 3;</code>
   *
   * <pre>
   * The current context of the event.
   * </pre>
   */
  public com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventContext getContext() {
    return context_;
  }

  // optional int64 value = 4;
  public static final int VALUE_FIELD_NUMBER = 4;
  private long value_;
  /**
   * <code>optional int64 value = 4;</code>
   *
   * <pre>
   * This value is an opaque numeric type. The exact schema of the UI metrics
   * is not specific here. e.g., |value| may represent a boolean, a "count", or
   * an index into the list of items in a drop down menu.
   * </pre>
   */
  public boolean hasValue() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int64 value = 4;</code>
   *
   * <pre>
   * This value is an opaque numeric type. The exact schema of the UI metrics
   * is not specific here. e.g., |value| may represent a boolean, a "count", or
   * an index into the list of items in a drop down menu.
   * </pre>
   */
  public long getValue() {
    return value_;
  }

  private void initFields() {
    elementId_ = "";
    type_ = com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventType.UNKONWN_EMULATOR_UI_EVENT_TYPE;
    context_ = com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventContext.UNKNOWN_EMULATOR_UI_EVENT_CONTEXT;
    value_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getElementIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeEnum(2, type_.getNumber());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeEnum(3, context_.getNumber());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt64(4, value_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getElementIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_.getNumber());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, context_.getNumber());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, value_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.google.wireless.android.sdk.stats.EmulatorUiEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorUiEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorUiEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorUiEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorUiEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorUiEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorUiEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorUiEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorUiEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorUiEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.EmulatorUiEvent prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code android_studio.EmulatorUiEvent}
   *
   * <pre>
   * Describes a user clicking on some part of the Emulator UI.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.google.wireless.android.sdk.stats.EmulatorUiEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorUiEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorUiEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.EmulatorUiEvent.class, com.google.wireless.android.sdk.stats.EmulatorUiEvent.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.EmulatorUiEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      elementId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventType.UNKONWN_EMULATOR_UI_EVENT_TYPE;
      bitField0_ = (bitField0_ & ~0x00000002);
      context_ = com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventContext.UNKNOWN_EMULATOR_UI_EVENT_CONTEXT;
      bitField0_ = (bitField0_ & ~0x00000004);
      value_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorUiEvent_descriptor;
    }

    public com.google.wireless.android.sdk.stats.EmulatorUiEvent getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.EmulatorUiEvent.getDefaultInstance();
    }

    public com.google.wireless.android.sdk.stats.EmulatorUiEvent build() {
      com.google.wireless.android.sdk.stats.EmulatorUiEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.wireless.android.sdk.stats.EmulatorUiEvent buildPartial() {
      com.google.wireless.android.sdk.stats.EmulatorUiEvent result = new com.google.wireless.android.sdk.stats.EmulatorUiEvent(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.elementId_ = elementId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.context_ = context_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.value_ = value_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.EmulatorUiEvent) {
        return mergeFrom((com.google.wireless.android.sdk.stats.EmulatorUiEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.EmulatorUiEvent other) {
      if (other == com.google.wireless.android.sdk.stats.EmulatorUiEvent.getDefaultInstance()) return this;
      if (other.hasElementId()) {
        bitField0_ |= 0x00000001;
        elementId_ = other.elementId_;
        onChanged();
      }
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasContext()) {
        setContext(other.getContext());
      }
      if (other.hasValue()) {
        setValue(other.getValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.wireless.android.sdk.stats.EmulatorUiEvent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.wireless.android.sdk.stats.EmulatorUiEvent) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string element_id = 1;
    private java.lang.Object elementId_ = "";
    /**
     * <code>optional string element_id = 1;</code>
     *
     * <pre>
     * Id of the UI element, baked in the emulator binary.
     * </pre>
     */
    public boolean hasElementId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string element_id = 1;</code>
     *
     * <pre>
     * Id of the UI element, baked in the emulator binary.
     * </pre>
     */
    public java.lang.String getElementId() {
      java.lang.Object ref = elementId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        elementId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string element_id = 1;</code>
     *
     * <pre>
     * Id of the UI element, baked in the emulator binary.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getElementIdBytes() {
      java.lang.Object ref = elementId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        elementId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string element_id = 1;</code>
     *
     * <pre>
     * Id of the UI element, baked in the emulator binary.
     * </pre>
     */
    public Builder setElementId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      elementId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string element_id = 1;</code>
     *
     * <pre>
     * Id of the UI element, baked in the emulator binary.
     * </pre>
     */
    public Builder clearElementId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      elementId_ = getDefaultInstance().getElementId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string element_id = 1;</code>
     *
     * <pre>
     * Id of the UI element, baked in the emulator binary.
     * </pre>
     */
    public Builder setElementIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      elementId_ = value;
      onChanged();
      return this;
    }

    // optional .android_studio.EmulatorUiEvent.EmulatorUiEventType type = 2;
    private com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventType type_ = com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventType.UNKONWN_EMULATOR_UI_EVENT_TYPE;
    /**
     * <code>optional .android_studio.EmulatorUiEvent.EmulatorUiEventType type = 2;</code>
     *
     * <pre>
     * The type of UI event
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .android_studio.EmulatorUiEvent.EmulatorUiEventType type = 2;</code>
     *
     * <pre>
     * The type of UI event
     * </pre>
     */
    public com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventType getType() {
      return type_;
    }
    /**
     * <code>optional .android_studio.EmulatorUiEvent.EmulatorUiEventType type = 2;</code>
     *
     * <pre>
     * The type of UI event
     * </pre>
     */
    public Builder setType(com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.EmulatorUiEvent.EmulatorUiEventType type = 2;</code>
     *
     * <pre>
     * The type of UI event
     * </pre>
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventType.UNKONWN_EMULATOR_UI_EVENT_TYPE;
      onChanged();
      return this;
    }

    // optional .android_studio.EmulatorUiEvent.EmulatorUiEventContext context = 3;
    private com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventContext context_ = com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventContext.UNKNOWN_EMULATOR_UI_EVENT_CONTEXT;
    /**
     * <code>optional .android_studio.EmulatorUiEvent.EmulatorUiEventContext context = 3;</code>
     *
     * <pre>
     * The current context of the event.
     * </pre>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .android_studio.EmulatorUiEvent.EmulatorUiEventContext context = 3;</code>
     *
     * <pre>
     * The current context of the event.
     * </pre>
     */
    public com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventContext getContext() {
      return context_;
    }
    /**
     * <code>optional .android_studio.EmulatorUiEvent.EmulatorUiEventContext context = 3;</code>
     *
     * <pre>
     * The current context of the event.
     * </pre>
     */
    public Builder setContext(com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventContext value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      context_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.EmulatorUiEvent.EmulatorUiEventContext context = 3;</code>
     *
     * <pre>
     * The current context of the event.
     * </pre>
     */
    public Builder clearContext() {
      bitField0_ = (bitField0_ & ~0x00000004);
      context_ = com.google.wireless.android.sdk.stats.EmulatorUiEvent.EmulatorUiEventContext.UNKNOWN_EMULATOR_UI_EVENT_CONTEXT;
      onChanged();
      return this;
    }

    // optional int64 value = 4;
    private long value_ ;
    /**
     * <code>optional int64 value = 4;</code>
     *
     * <pre>
     * This value is an opaque numeric type. The exact schema of the UI metrics
     * is not specific here. e.g., |value| may represent a boolean, a "count", or
     * an index into the list of items in a drop down menu.
     * </pre>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 value = 4;</code>
     *
     * <pre>
     * This value is an opaque numeric type. The exact schema of the UI metrics
     * is not specific here. e.g., |value| may represent a boolean, a "count", or
     * an index into the list of items in a drop down menu.
     * </pre>
     */
    public long getValue() {
      return value_;
    }
    /**
     * <code>optional int64 value = 4;</code>
     *
     * <pre>
     * This value is an opaque numeric type. The exact schema of the UI metrics
     * is not specific here. e.g., |value| may represent a boolean, a "count", or
     * an index into the list of items in a drop down menu.
     * </pre>
     */
    public Builder setValue(long value) {
      bitField0_ |= 0x00000008;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 value = 4;</code>
     *
     * <pre>
     * This value is an opaque numeric type. The exact schema of the UI metrics
     * is not specific here. e.g., |value| may represent a boolean, a "count", or
     * an index into the list of items in a drop down menu.
     * </pre>
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000008);
      value_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:android_studio.EmulatorUiEvent)
  }

  static {
    defaultInstance = new EmulatorUiEvent(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:android_studio.EmulatorUiEvent)
}

