// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * Protobuf type {@code android_studio.EmulatorGpuInfo}
 *
 * <pre>
 * Emulator: Host GPU info.
 * </pre>
 */
public  final class EmulatorGpuInfo extends
    com.google.protobuf.GeneratedMessage
    implements EmulatorGpuInfoOrBuilder {
  // Use EmulatorGpuInfo.newBuilder() to construct.
  private EmulatorGpuInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private EmulatorGpuInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final EmulatorGpuInfo defaultInstance;
  public static EmulatorGpuInfo getDefaultInstance() {
    return defaultInstance;
  }

  public EmulatorGpuInfo getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private EmulatorGpuInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            make_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            model_ = input.readBytes();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            deviceId_ = input.readBytes();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            revisionId_ = input.readBytes();
            break;
          }
          case 42: {
            bitField0_ |= 0x00000010;
            version_ = input.readBytes();
            break;
          }
          case 50: {
            bitField0_ |= 0x00000020;
            renderer_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorGpuInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorGpuInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.EmulatorGpuInfo.class, com.google.wireless.android.sdk.stats.EmulatorGpuInfo.Builder.class);
  }

  public static com.google.protobuf.Parser<EmulatorGpuInfo> PARSER =
      new com.google.protobuf.AbstractParser<EmulatorGpuInfo>() {
    public EmulatorGpuInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmulatorGpuInfo(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<EmulatorGpuInfo> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional string make = 1;
  public static final int MAKE_FIELD_NUMBER = 1;
  private java.lang.Object make_;
  /**
   * <code>optional string make = 1;</code>
   *
   * <pre>
   * Make of the Graphics card.
   * </pre>
   */
  public boolean hasMake() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string make = 1;</code>
   *
   * <pre>
   * Make of the Graphics card.
   * </pre>
   */
  public java.lang.String getMake() {
    java.lang.Object ref = make_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        make_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string make = 1;</code>
   *
   * <pre>
   * Make of the Graphics card.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getMakeBytes() {
    java.lang.Object ref = make_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      make_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string model = 2;
  public static final int MODEL_FIELD_NUMBER = 2;
  private java.lang.Object model_;
  /**
   * <code>optional string model = 2;</code>
   *
   * <pre>
   * Model of the Graphics card.
   * </pre>
   */
  public boolean hasModel() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string model = 2;</code>
   *
   * <pre>
   * Model of the Graphics card.
   * </pre>
   */
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        model_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string model = 2;</code>
   *
   * <pre>
   * Model of the Graphics card.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string device_id = 3;
  public static final int DEVICE_ID_FIELD_NUMBER = 3;
  private java.lang.Object deviceId_;
  /**
   * <code>optional string device_id = 3;</code>
   *
   * <pre>
   * Device id of the Graphics card.
   * </pre>
   */
  public boolean hasDeviceId() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string device_id = 3;</code>
   *
   * <pre>
   * Device id of the Graphics card.
   * </pre>
   */
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        deviceId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string device_id = 3;</code>
   *
   * <pre>
   * Device id of the Graphics card.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string revision_id = 4;
  public static final int REVISION_ID_FIELD_NUMBER = 4;
  private java.lang.Object revisionId_;
  /**
   * <code>optional string revision_id = 4;</code>
   *
   * <pre>
   * Revision of the graphics card.
   * </pre>
   */
  public boolean hasRevisionId() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string revision_id = 4;</code>
   *
   * <pre>
   * Revision of the graphics card.
   * </pre>
   */
  public java.lang.String getRevisionId() {
    java.lang.Object ref = revisionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        revisionId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string revision_id = 4;</code>
   *
   * <pre>
   * Revision of the graphics card.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getRevisionIdBytes() {
    java.lang.Object ref = revisionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      revisionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string version = 5;
  public static final int VERSION_FIELD_NUMBER = 5;
  private java.lang.Object version_;
  /**
   * <code>optional string version = 5;</code>
   *
   * <pre>
   * Version of the graphics card driver.
   * </pre>
   */
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string version = 5;</code>
   *
   * <pre>
   * Version of the graphics card driver.
   * </pre>
   */
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        version_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string version = 5;</code>
   *
   * <pre>
   * Version of the graphics card driver.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string renderer = 6;
  public static final int RENDERER_FIELD_NUMBER = 6;
  private java.lang.Object renderer_;
  /**
   * <code>optional string renderer = 6;</code>
   *
   * <pre>
   * Name of the graphics card driver.
   * </pre>
   */
  public boolean hasRenderer() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string renderer = 6;</code>
   *
   * <pre>
   * Name of the graphics card driver.
   * </pre>
   */
  public java.lang.String getRenderer() {
    java.lang.Object ref = renderer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        renderer_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string renderer = 6;</code>
   *
   * <pre>
   * Name of the graphics card driver.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getRendererBytes() {
    java.lang.Object ref = renderer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      renderer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    make_ = "";
    model_ = "";
    deviceId_ = "";
    revisionId_ = "";
    version_ = "";
    renderer_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getMakeBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getModelBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getDeviceIdBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(4, getRevisionIdBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getVersionBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeBytes(6, getRendererBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getMakeBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getModelBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getDeviceIdBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getRevisionIdBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getVersionBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, getRendererBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.google.wireless.android.sdk.stats.EmulatorGpuInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorGpuInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorGpuInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorGpuInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorGpuInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorGpuInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorGpuInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorGpuInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorGpuInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorGpuInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.EmulatorGpuInfo prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code android_studio.EmulatorGpuInfo}
   *
   * <pre>
   * Emulator: Host GPU info.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.google.wireless.android.sdk.stats.EmulatorGpuInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorGpuInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorGpuInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.EmulatorGpuInfo.class, com.google.wireless.android.sdk.stats.EmulatorGpuInfo.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.EmulatorGpuInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      make_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      model_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      deviceId_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      revisionId_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      version_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      renderer_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorGpuInfo_descriptor;
    }

    public com.google.wireless.android.sdk.stats.EmulatorGpuInfo getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.EmulatorGpuInfo.getDefaultInstance();
    }

    public com.google.wireless.android.sdk.stats.EmulatorGpuInfo build() {
      com.google.wireless.android.sdk.stats.EmulatorGpuInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.wireless.android.sdk.stats.EmulatorGpuInfo buildPartial() {
      com.google.wireless.android.sdk.stats.EmulatorGpuInfo result = new com.google.wireless.android.sdk.stats.EmulatorGpuInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.make_ = make_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.model_ = model_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.deviceId_ = deviceId_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.revisionId_ = revisionId_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.version_ = version_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.renderer_ = renderer_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.EmulatorGpuInfo) {
        return mergeFrom((com.google.wireless.android.sdk.stats.EmulatorGpuInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.EmulatorGpuInfo other) {
      if (other == com.google.wireless.android.sdk.stats.EmulatorGpuInfo.getDefaultInstance()) return this;
      if (other.hasMake()) {
        bitField0_ |= 0x00000001;
        make_ = other.make_;
        onChanged();
      }
      if (other.hasModel()) {
        bitField0_ |= 0x00000002;
        model_ = other.model_;
        onChanged();
      }
      if (other.hasDeviceId()) {
        bitField0_ |= 0x00000004;
        deviceId_ = other.deviceId_;
        onChanged();
      }
      if (other.hasRevisionId()) {
        bitField0_ |= 0x00000008;
        revisionId_ = other.revisionId_;
        onChanged();
      }
      if (other.hasVersion()) {
        bitField0_ |= 0x00000010;
        version_ = other.version_;
        onChanged();
      }
      if (other.hasRenderer()) {
        bitField0_ |= 0x00000020;
        renderer_ = other.renderer_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.wireless.android.sdk.stats.EmulatorGpuInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.wireless.android.sdk.stats.EmulatorGpuInfo) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string make = 1;
    private java.lang.Object make_ = "";
    /**
     * <code>optional string make = 1;</code>
     *
     * <pre>
     * Make of the Graphics card.
     * </pre>
     */
    public boolean hasMake() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string make = 1;</code>
     *
     * <pre>
     * Make of the Graphics card.
     * </pre>
     */
    public java.lang.String getMake() {
      java.lang.Object ref = make_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        make_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string make = 1;</code>
     *
     * <pre>
     * Make of the Graphics card.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMakeBytes() {
      java.lang.Object ref = make_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        make_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string make = 1;</code>
     *
     * <pre>
     * Make of the Graphics card.
     * </pre>
     */
    public Builder setMake(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      make_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string make = 1;</code>
     *
     * <pre>
     * Make of the Graphics card.
     * </pre>
     */
    public Builder clearMake() {
      bitField0_ = (bitField0_ & ~0x00000001);
      make_ = getDefaultInstance().getMake();
      onChanged();
      return this;
    }
    /**
     * <code>optional string make = 1;</code>
     *
     * <pre>
     * Make of the Graphics card.
     * </pre>
     */
    public Builder setMakeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      make_ = value;
      onChanged();
      return this;
    }

    // optional string model = 2;
    private java.lang.Object model_ = "";
    /**
     * <code>optional string model = 2;</code>
     *
     * <pre>
     * Model of the Graphics card.
     * </pre>
     */
    public boolean hasModel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string model = 2;</code>
     *
     * <pre>
     * Model of the Graphics card.
     * </pre>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string model = 2;</code>
     *
     * <pre>
     * Model of the Graphics card.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string model = 2;</code>
     *
     * <pre>
     * Model of the Graphics card.
     * </pre>
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      model_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string model = 2;</code>
     *
     * <pre>
     * Model of the Graphics card.
     * </pre>
     */
    public Builder clearModel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      model_ = getDefaultInstance().getModel();
      onChanged();
      return this;
    }
    /**
     * <code>optional string model = 2;</code>
     *
     * <pre>
     * Model of the Graphics card.
     * </pre>
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      model_ = value;
      onChanged();
      return this;
    }

    // optional string device_id = 3;
    private java.lang.Object deviceId_ = "";
    /**
     * <code>optional string device_id = 3;</code>
     *
     * <pre>
     * Device id of the Graphics card.
     * </pre>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string device_id = 3;</code>
     *
     * <pre>
     * Device id of the Graphics card.
     * </pre>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string device_id = 3;</code>
     *
     * <pre>
     * Device id of the Graphics card.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string device_id = 3;</code>
     *
     * <pre>
     * Device id of the Graphics card.
     * </pre>
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string device_id = 3;</code>
     *
     * <pre>
     * Device id of the Graphics card.
     * </pre>
     */
    public Builder clearDeviceId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string device_id = 3;</code>
     *
     * <pre>
     * Device id of the Graphics card.
     * </pre>
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      deviceId_ = value;
      onChanged();
      return this;
    }

    // optional string revision_id = 4;
    private java.lang.Object revisionId_ = "";
    /**
     * <code>optional string revision_id = 4;</code>
     *
     * <pre>
     * Revision of the graphics card.
     * </pre>
     */
    public boolean hasRevisionId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string revision_id = 4;</code>
     *
     * <pre>
     * Revision of the graphics card.
     * </pre>
     */
    public java.lang.String getRevisionId() {
      java.lang.Object ref = revisionId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        revisionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string revision_id = 4;</code>
     *
     * <pre>
     * Revision of the graphics card.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRevisionIdBytes() {
      java.lang.Object ref = revisionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        revisionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string revision_id = 4;</code>
     *
     * <pre>
     * Revision of the graphics card.
     * </pre>
     */
    public Builder setRevisionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      revisionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string revision_id = 4;</code>
     *
     * <pre>
     * Revision of the graphics card.
     * </pre>
     */
    public Builder clearRevisionId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      revisionId_ = getDefaultInstance().getRevisionId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string revision_id = 4;</code>
     *
     * <pre>
     * Revision of the graphics card.
     * </pre>
     */
    public Builder setRevisionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      revisionId_ = value;
      onChanged();
      return this;
    }

    // optional string version = 5;
    private java.lang.Object version_ = "";
    /**
     * <code>optional string version = 5;</code>
     *
     * <pre>
     * Version of the graphics card driver.
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string version = 5;</code>
     *
     * <pre>
     * Version of the graphics card driver.
     * </pre>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string version = 5;</code>
     *
     * <pre>
     * Version of the graphics card driver.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string version = 5;</code>
     *
     * <pre>
     * Version of the graphics card driver.
     * </pre>
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string version = 5;</code>
     *
     * <pre>
     * Version of the graphics card driver.
     * </pre>
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000010);
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>optional string version = 5;</code>
     *
     * <pre>
     * Version of the graphics card driver.
     * </pre>
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      version_ = value;
      onChanged();
      return this;
    }

    // optional string renderer = 6;
    private java.lang.Object renderer_ = "";
    /**
     * <code>optional string renderer = 6;</code>
     *
     * <pre>
     * Name of the graphics card driver.
     * </pre>
     */
    public boolean hasRenderer() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string renderer = 6;</code>
     *
     * <pre>
     * Name of the graphics card driver.
     * </pre>
     */
    public java.lang.String getRenderer() {
      java.lang.Object ref = renderer_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        renderer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string renderer = 6;</code>
     *
     * <pre>
     * Name of the graphics card driver.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRendererBytes() {
      java.lang.Object ref = renderer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        renderer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string renderer = 6;</code>
     *
     * <pre>
     * Name of the graphics card driver.
     * </pre>
     */
    public Builder setRenderer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      renderer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string renderer = 6;</code>
     *
     * <pre>
     * Name of the graphics card driver.
     * </pre>
     */
    public Builder clearRenderer() {
      bitField0_ = (bitField0_ & ~0x00000020);
      renderer_ = getDefaultInstance().getRenderer();
      onChanged();
      return this;
    }
    /**
     * <code>optional string renderer = 6;</code>
     *
     * <pre>
     * Name of the graphics card driver.
     * </pre>
     */
    public Builder setRendererBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      renderer_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:android_studio.EmulatorGpuInfo)
  }

  static {
    defaultInstance = new EmulatorGpuInfo(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:android_studio.EmulatorGpuInfo)
}

