// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface EmulatorFeaturesOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional bool gps = 1;
  /**
   * <code>optional bool gps = 1;</code>
   */
  boolean hasGps();
  /**
   * <code>optional bool gps = 1;</code>
   */
  boolean getGps();

  // optional bool sensors = 2;
  /**
   * <code>optional bool sensors = 2;</code>
   */
  boolean hasSensors();
  /**
   * <code>optional bool sensors = 2;</code>
   */
  boolean getSensors();
}
