// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface EmulatorGLESv30UsagesOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional bool is_used = 1;
  /**
   * <code>optional bool is_used = 1;</code>
   *
   * <pre>
   * Has the client create any GLES3 contexts
   * </pre>
   */
  boolean hasIsUsed();
  /**
   * <code>optional bool is_used = 1;</code>
   *
   * <pre>
   * Has the client create any GLES3 contexts
   * </pre>
   */
  boolean getIsUsed();

  // optional bool fence_sync = 2;
  /**
   * <code>optional bool fence_sync = 2;</code>
   *
   * <pre>
   * Track glFenceSync command calls
   * </pre>
   */
  boolean hasFenceSync();
  /**
   * <code>optional bool fence_sync = 2;</code>
   *
   * <pre>
   * Track glFenceSync command calls
   * </pre>
   */
  boolean getFenceSync();

  // optional bool framebuffer_texture_layer = 3;
  /**
   * <code>optional bool framebuffer_texture_layer = 3;</code>
   *
   * <pre>
   * Track glFramebufferTextureLayer command calls
   * </pre>
   */
  boolean hasFramebufferTextureLayer();
  /**
   * <code>optional bool framebuffer_texture_layer = 3;</code>
   *
   * <pre>
   * Track glFramebufferTextureLayer command calls
   * </pre>
   */
  boolean getFramebufferTextureLayer();

  // optional bool renderbuffer_storage_multisample = 4;
  /**
   * <code>optional bool renderbuffer_storage_multisample = 4;</code>
   *
   * <pre>
   * Track glRenderbufferStorageMultisample command calls
   * </pre>
   */
  boolean hasRenderbufferStorageMultisample();
  /**
   * <code>optional bool renderbuffer_storage_multisample = 4;</code>
   *
   * <pre>
   * Track glRenderbufferStorageMultisample command calls
   * </pre>
   */
  boolean getRenderbufferStorageMultisample();

  // optional bool gen_transform_feedbacks = 5;
  /**
   * <code>optional bool gen_transform_feedbacks = 5;</code>
   *
   * <pre>
   * Track glGenTransformFeedbacks command calls
   * </pre>
   */
  boolean hasGenTransformFeedbacks();
  /**
   * <code>optional bool gen_transform_feedbacks = 5;</code>
   *
   * <pre>
   * Track glGenTransformFeedbacks command calls
   * </pre>
   */
  boolean getGenTransformFeedbacks();

  // optional bool begin_query = 6;
  /**
   * <code>optional bool begin_query = 6;</code>
   *
   * <pre>
   * Track glBeginQuery command calls
   * </pre>
   */
  boolean hasBeginQuery();
  /**
   * <code>optional bool begin_query = 6;</code>
   *
   * <pre>
   * Track glBeginQuery command calls
   * </pre>
   */
  boolean getBeginQuery();
}
