// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * Protobuf type {@code android_studio.FirebaseContextDetails}
 *
 * <pre>
 * Contextual details for Firebase Assistant events. This message acts as a
 * generic container for all events rather than having different messages for
 * each event type. While some fields will be knowingly blank/irrelevant for
 * some event types, frequency of logging is expected to be low enough that
 * this does not represent request/storage bloat.
 * </pre>
 */
public  final class FirebaseContextDetails extends
    com.google.protobuf.GeneratedMessage
    implements FirebaseContextDetailsOrBuilder {
  // Use FirebaseContextDetails.newBuilder() to construct.
  private FirebaseContextDetails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private FirebaseContextDetails(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final FirebaseContextDetails defaultInstance;
  public static FirebaseContextDetails getDefaultInstance() {
    return defaultInstance;
  }

  public FirebaseContextDetails getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private FirebaseContextDetails(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            projectId_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            projectNumber_ = input.readBytes();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            loggedIn_ = input.readBool();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();
            com.google.wireless.android.sdk.stats.FirebaseContextDetails.ConnectStatus value = com.google.wireless.android.sdk.stats.FirebaseContextDetails.ConnectStatus.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(4, rawValue);
            } else {
              bitField0_ |= 0x00000008;
              connectStatus_ = value;
            }
            break;
          }
          case 42: {
            bitField0_ |= 0x00000010;
            performedOn_ = input.readBytes();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            duration_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_FirebaseContextDetails_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_FirebaseContextDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.FirebaseContextDetails.class, com.google.wireless.android.sdk.stats.FirebaseContextDetails.Builder.class);
  }

  public static com.google.protobuf.Parser<FirebaseContextDetails> PARSER =
      new com.google.protobuf.AbstractParser<FirebaseContextDetails>() {
    public FirebaseContextDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FirebaseContextDetails(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<FirebaseContextDetails> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code android_studio.FirebaseContextDetails.ConnectStatus}
   */
  public enum ConnectStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_CONNECT_STATUS = 1;</code>
     *
     * <pre>
     * Unable to determine connection status.
     * </pre>
     */
    UNKNOWN_CONNECT_STATUS(0, 1),
    /**
     * <code>NOT_CONNECTED = 2;</code>
     *
     * <pre>
     * No modules connected.
     * </pre>
     */
    NOT_CONNECTED(1, 2),
    /**
     * <code>PARTIALLY_CONNECTED = 3;</code>
     *
     * <pre>
     * 1 to N-1 modules were connected in a project with N modules.
     * </pre>
     */
    PARTIALLY_CONNECTED(2, 3),
    /**
     * <code>CONNECTED = 4;</code>
     *
     * <pre>
     * All modules connected.
     * </pre>
     */
    CONNECTED(3, 4),
    ;

    /**
     * <code>UNKNOWN_CONNECT_STATUS = 1;</code>
     *
     * <pre>
     * Unable to determine connection status.
     * </pre>
     */
    public static final int UNKNOWN_CONNECT_STATUS_VALUE = 1;
    /**
     * <code>NOT_CONNECTED = 2;</code>
     *
     * <pre>
     * No modules connected.
     * </pre>
     */
    public static final int NOT_CONNECTED_VALUE = 2;
    /**
     * <code>PARTIALLY_CONNECTED = 3;</code>
     *
     * <pre>
     * 1 to N-1 modules were connected in a project with N modules.
     * </pre>
     */
    public static final int PARTIALLY_CONNECTED_VALUE = 3;
    /**
     * <code>CONNECTED = 4;</code>
     *
     * <pre>
     * All modules connected.
     * </pre>
     */
    public static final int CONNECTED_VALUE = 4;


    public final int getNumber() { return value; }

    public static ConnectStatus valueOf(int value) {
      switch (value) {
        case 1: return UNKNOWN_CONNECT_STATUS;
        case 2: return NOT_CONNECTED;
        case 3: return PARTIALLY_CONNECTED;
        case 4: return CONNECTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ConnectStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ConnectStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ConnectStatus>() {
            public ConnectStatus findValueByNumber(int number) {
              return ConnectStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.FirebaseContextDetails.getDescriptor().getEnumTypes().get(0);
    }

    private static final ConnectStatus[] VALUES = values();

    public static ConnectStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ConnectStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.FirebaseContextDetails.ConnectStatus)
  }

  private int bitField0_;
  // optional string project_id = 1;
  public static final int PROJECT_ID_FIELD_NUMBER = 1;
  private java.lang.Object projectId_;
  /**
   * <code>optional string project_id = 1;</code>
   *
   * <pre>
   * Public project id, used for attributing project growth to the plugin.
   * </pre>
   */
  public boolean hasProjectId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string project_id = 1;</code>
   *
   * <pre>
   * Public project id, used for attributing project growth to the plugin.
   * </pre>
   */
  public java.lang.String getProjectId() {
    java.lang.Object ref = projectId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        projectId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string project_id = 1;</code>
   *
   * <pre>
   * Public project id, used for attributing project growth to the plugin.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getProjectIdBytes() {
    java.lang.Object ref = projectId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string project_number = 2;
  public static final int PROJECT_NUMBER_FIELD_NUMBER = 2;
  private java.lang.Object projectNumber_;
  /**
   * <code>optional string project_number = 2;</code>
   *
   * <pre>
   * Secondary identifier for the project, also stored for more flexibility with
   * joining the data with other sets.
   * </pre>
   */
  public boolean hasProjectNumber() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string project_number = 2;</code>
   *
   * <pre>
   * Secondary identifier for the project, also stored for more flexibility with
   * joining the data with other sets.
   * </pre>
   */
  public java.lang.String getProjectNumber() {
    java.lang.Object ref = projectNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        projectNumber_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string project_number = 2;</code>
   *
   * <pre>
   * Secondary identifier for the project, also stored for more flexibility with
   * joining the data with other sets.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getProjectNumberBytes() {
    java.lang.Object ref = projectNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional bool logged_in = 3;
  public static final int LOGGED_IN_FIELD_NUMBER = 3;
  private boolean loggedIn_;
  /**
   * <code>optional bool logged_in = 3;</code>
   *
   * <pre>
   * Whether the action was performed while the user was logged in.
   * </pre>
   */
  public boolean hasLoggedIn() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional bool logged_in = 3;</code>
   *
   * <pre>
   * Whether the action was performed while the user was logged in.
   * </pre>
   */
  public boolean getLoggedIn() {
    return loggedIn_;
  }

  // optional .android_studio.FirebaseContextDetails.ConnectStatus connect_status = 4;
  public static final int CONNECT_STATUS_FIELD_NUMBER = 4;
  private com.google.wireless.android.sdk.stats.FirebaseContextDetails.ConnectStatus connectStatus_;
  /**
   * <code>optional .android_studio.FirebaseContextDetails.ConnectStatus connect_status = 4;</code>
   *
   * <pre>
   * Whether the action was performed on while the related Studio project's
   * modules were connected to a Firebase project.
   * </pre>
   */
  public boolean hasConnectStatus() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .android_studio.FirebaseContextDetails.ConnectStatus connect_status = 4;</code>
   *
   * <pre>
   * Whether the action was performed on while the related Studio project's
   * modules were connected to a Firebase project.
   * </pre>
   */
  public com.google.wireless.android.sdk.stats.FirebaseContextDetails.ConnectStatus getConnectStatus() {
    return connectStatus_;
  }

  // optional string performed_on = 5;
  public static final int PERFORMED_ON_FIELD_NUMBER = 5;
  private java.lang.Object performedOn_;
  /**
   * <code>optional string performed_on = 5;</code>
   *
   * <pre>
   * Tutorial resource event relates to. Restricted to non PII such as the id
   * of the tutorial that was opened.
   * </pre>
   */
  public boolean hasPerformedOn() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string performed_on = 5;</code>
   *
   * <pre>
   * Tutorial resource event relates to. Restricted to non PII such as the id
   * of the tutorial that was opened.
   * </pre>
   */
  public java.lang.String getPerformedOn() {
    java.lang.Object ref = performedOn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        performedOn_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string performed_on = 5;</code>
   *
   * <pre>
   * Tutorial resource event relates to. Restricted to non PII such as the id
   * of the tutorial that was opened.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getPerformedOnBytes() {
    java.lang.Object ref = performedOn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      performedOn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int64 duration = 6;
  public static final int DURATION_FIELD_NUMBER = 6;
  private long duration_;
  /**
   * <code>optional int64 duration = 6;</code>
   *
   * <pre>
   * Time that an action took to be performed. A primary example is how long
   * a tutorial was open before navigating away.
   * </pre>
   */
  public boolean hasDuration() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional int64 duration = 6;</code>
   *
   * <pre>
   * Time that an action took to be performed. A primary example is how long
   * a tutorial was open before navigating away.
   * </pre>
   */
  public long getDuration() {
    return duration_;
  }

  private void initFields() {
    projectId_ = "";
    projectNumber_ = "";
    loggedIn_ = false;
    connectStatus_ = com.google.wireless.android.sdk.stats.FirebaseContextDetails.ConnectStatus.UNKNOWN_CONNECT_STATUS;
    performedOn_ = "";
    duration_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getProjectIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getProjectNumberBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBool(3, loggedIn_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeEnum(4, connectStatus_.getNumber());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getPerformedOnBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeInt64(6, duration_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getProjectIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getProjectNumberBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, loggedIn_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, connectStatus_.getNumber());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getPerformedOnBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, duration_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.google.wireless.android.sdk.stats.FirebaseContextDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.FirebaseContextDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.FirebaseContextDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.FirebaseContextDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.FirebaseContextDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.FirebaseContextDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.FirebaseContextDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.FirebaseContextDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.FirebaseContextDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.FirebaseContextDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.FirebaseContextDetails prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code android_studio.FirebaseContextDetails}
   *
   * <pre>
   * Contextual details for Firebase Assistant events. This message acts as a
   * generic container for all events rather than having different messages for
   * each event type. While some fields will be knowingly blank/irrelevant for
   * some event types, frequency of logging is expected to be low enough that
   * this does not represent request/storage bloat.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.google.wireless.android.sdk.stats.FirebaseContextDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_FirebaseContextDetails_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_FirebaseContextDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.FirebaseContextDetails.class, com.google.wireless.android.sdk.stats.FirebaseContextDetails.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.FirebaseContextDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      projectId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      projectNumber_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      loggedIn_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      connectStatus_ = com.google.wireless.android.sdk.stats.FirebaseContextDetails.ConnectStatus.UNKNOWN_CONNECT_STATUS;
      bitField0_ = (bitField0_ & ~0x00000008);
      performedOn_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      duration_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_FirebaseContextDetails_descriptor;
    }

    public com.google.wireless.android.sdk.stats.FirebaseContextDetails getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.FirebaseContextDetails.getDefaultInstance();
    }

    public com.google.wireless.android.sdk.stats.FirebaseContextDetails build() {
      com.google.wireless.android.sdk.stats.FirebaseContextDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.wireless.android.sdk.stats.FirebaseContextDetails buildPartial() {
      com.google.wireless.android.sdk.stats.FirebaseContextDetails result = new com.google.wireless.android.sdk.stats.FirebaseContextDetails(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.projectId_ = projectId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.projectNumber_ = projectNumber_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.loggedIn_ = loggedIn_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.connectStatus_ = connectStatus_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.performedOn_ = performedOn_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.duration_ = duration_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.FirebaseContextDetails) {
        return mergeFrom((com.google.wireless.android.sdk.stats.FirebaseContextDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.FirebaseContextDetails other) {
      if (other == com.google.wireless.android.sdk.stats.FirebaseContextDetails.getDefaultInstance()) return this;
      if (other.hasProjectId()) {
        bitField0_ |= 0x00000001;
        projectId_ = other.projectId_;
        onChanged();
      }
      if (other.hasProjectNumber()) {
        bitField0_ |= 0x00000002;
        projectNumber_ = other.projectNumber_;
        onChanged();
      }
      if (other.hasLoggedIn()) {
        setLoggedIn(other.getLoggedIn());
      }
      if (other.hasConnectStatus()) {
        setConnectStatus(other.getConnectStatus());
      }
      if (other.hasPerformedOn()) {
        bitField0_ |= 0x00000010;
        performedOn_ = other.performedOn_;
        onChanged();
      }
      if (other.hasDuration()) {
        setDuration(other.getDuration());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.wireless.android.sdk.stats.FirebaseContextDetails parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.wireless.android.sdk.stats.FirebaseContextDetails) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string project_id = 1;
    private java.lang.Object projectId_ = "";
    /**
     * <code>optional string project_id = 1;</code>
     *
     * <pre>
     * Public project id, used for attributing project growth to the plugin.
     * </pre>
     */
    public boolean hasProjectId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string project_id = 1;</code>
     *
     * <pre>
     * Public project id, used for attributing project growth to the plugin.
     * </pre>
     */
    public java.lang.String getProjectId() {
      java.lang.Object ref = projectId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        projectId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string project_id = 1;</code>
     *
     * <pre>
     * Public project id, used for attributing project growth to the plugin.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getProjectIdBytes() {
      java.lang.Object ref = projectId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string project_id = 1;</code>
     *
     * <pre>
     * Public project id, used for attributing project growth to the plugin.
     * </pre>
     */
    public Builder setProjectId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      projectId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string project_id = 1;</code>
     *
     * <pre>
     * Public project id, used for attributing project growth to the plugin.
     * </pre>
     */
    public Builder clearProjectId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      projectId_ = getDefaultInstance().getProjectId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string project_id = 1;</code>
     *
     * <pre>
     * Public project id, used for attributing project growth to the plugin.
     * </pre>
     */
    public Builder setProjectIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      projectId_ = value;
      onChanged();
      return this;
    }

    // optional string project_number = 2;
    private java.lang.Object projectNumber_ = "";
    /**
     * <code>optional string project_number = 2;</code>
     *
     * <pre>
     * Secondary identifier for the project, also stored for more flexibility with
     * joining the data with other sets.
     * </pre>
     */
    public boolean hasProjectNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string project_number = 2;</code>
     *
     * <pre>
     * Secondary identifier for the project, also stored for more flexibility with
     * joining the data with other sets.
     * </pre>
     */
    public java.lang.String getProjectNumber() {
      java.lang.Object ref = projectNumber_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        projectNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string project_number = 2;</code>
     *
     * <pre>
     * Secondary identifier for the project, also stored for more flexibility with
     * joining the data with other sets.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getProjectNumberBytes() {
      java.lang.Object ref = projectNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string project_number = 2;</code>
     *
     * <pre>
     * Secondary identifier for the project, also stored for more flexibility with
     * joining the data with other sets.
     * </pre>
     */
    public Builder setProjectNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      projectNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string project_number = 2;</code>
     *
     * <pre>
     * Secondary identifier for the project, also stored for more flexibility with
     * joining the data with other sets.
     * </pre>
     */
    public Builder clearProjectNumber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      projectNumber_ = getDefaultInstance().getProjectNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional string project_number = 2;</code>
     *
     * <pre>
     * Secondary identifier for the project, also stored for more flexibility with
     * joining the data with other sets.
     * </pre>
     */
    public Builder setProjectNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      projectNumber_ = value;
      onChanged();
      return this;
    }

    // optional bool logged_in = 3;
    private boolean loggedIn_ ;
    /**
     * <code>optional bool logged_in = 3;</code>
     *
     * <pre>
     * Whether the action was performed while the user was logged in.
     * </pre>
     */
    public boolean hasLoggedIn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool logged_in = 3;</code>
     *
     * <pre>
     * Whether the action was performed while the user was logged in.
     * </pre>
     */
    public boolean getLoggedIn() {
      return loggedIn_;
    }
    /**
     * <code>optional bool logged_in = 3;</code>
     *
     * <pre>
     * Whether the action was performed while the user was logged in.
     * </pre>
     */
    public Builder setLoggedIn(boolean value) {
      bitField0_ |= 0x00000004;
      loggedIn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool logged_in = 3;</code>
     *
     * <pre>
     * Whether the action was performed while the user was logged in.
     * </pre>
     */
    public Builder clearLoggedIn() {
      bitField0_ = (bitField0_ & ~0x00000004);
      loggedIn_ = false;
      onChanged();
      return this;
    }

    // optional .android_studio.FirebaseContextDetails.ConnectStatus connect_status = 4;
    private com.google.wireless.android.sdk.stats.FirebaseContextDetails.ConnectStatus connectStatus_ = com.google.wireless.android.sdk.stats.FirebaseContextDetails.ConnectStatus.UNKNOWN_CONNECT_STATUS;
    /**
     * <code>optional .android_studio.FirebaseContextDetails.ConnectStatus connect_status = 4;</code>
     *
     * <pre>
     * Whether the action was performed on while the related Studio project's
     * modules were connected to a Firebase project.
     * </pre>
     */
    public boolean hasConnectStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .android_studio.FirebaseContextDetails.ConnectStatus connect_status = 4;</code>
     *
     * <pre>
     * Whether the action was performed on while the related Studio project's
     * modules were connected to a Firebase project.
     * </pre>
     */
    public com.google.wireless.android.sdk.stats.FirebaseContextDetails.ConnectStatus getConnectStatus() {
      return connectStatus_;
    }
    /**
     * <code>optional .android_studio.FirebaseContextDetails.ConnectStatus connect_status = 4;</code>
     *
     * <pre>
     * Whether the action was performed on while the related Studio project's
     * modules were connected to a Firebase project.
     * </pre>
     */
    public Builder setConnectStatus(com.google.wireless.android.sdk.stats.FirebaseContextDetails.ConnectStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      connectStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.FirebaseContextDetails.ConnectStatus connect_status = 4;</code>
     *
     * <pre>
     * Whether the action was performed on while the related Studio project's
     * modules were connected to a Firebase project.
     * </pre>
     */
    public Builder clearConnectStatus() {
      bitField0_ = (bitField0_ & ~0x00000008);
      connectStatus_ = com.google.wireless.android.sdk.stats.FirebaseContextDetails.ConnectStatus.UNKNOWN_CONNECT_STATUS;
      onChanged();
      return this;
    }

    // optional string performed_on = 5;
    private java.lang.Object performedOn_ = "";
    /**
     * <code>optional string performed_on = 5;</code>
     *
     * <pre>
     * Tutorial resource event relates to. Restricted to non PII such as the id
     * of the tutorial that was opened.
     * </pre>
     */
    public boolean hasPerformedOn() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string performed_on = 5;</code>
     *
     * <pre>
     * Tutorial resource event relates to. Restricted to non PII such as the id
     * of the tutorial that was opened.
     * </pre>
     */
    public java.lang.String getPerformedOn() {
      java.lang.Object ref = performedOn_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        performedOn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string performed_on = 5;</code>
     *
     * <pre>
     * Tutorial resource event relates to. Restricted to non PII such as the id
     * of the tutorial that was opened.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPerformedOnBytes() {
      java.lang.Object ref = performedOn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        performedOn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string performed_on = 5;</code>
     *
     * <pre>
     * Tutorial resource event relates to. Restricted to non PII such as the id
     * of the tutorial that was opened.
     * </pre>
     */
    public Builder setPerformedOn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      performedOn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string performed_on = 5;</code>
     *
     * <pre>
     * Tutorial resource event relates to. Restricted to non PII such as the id
     * of the tutorial that was opened.
     * </pre>
     */
    public Builder clearPerformedOn() {
      bitField0_ = (bitField0_ & ~0x00000010);
      performedOn_ = getDefaultInstance().getPerformedOn();
      onChanged();
      return this;
    }
    /**
     * <code>optional string performed_on = 5;</code>
     *
     * <pre>
     * Tutorial resource event relates to. Restricted to non PII such as the id
     * of the tutorial that was opened.
     * </pre>
     */
    public Builder setPerformedOnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      performedOn_ = value;
      onChanged();
      return this;
    }

    // optional int64 duration = 6;
    private long duration_ ;
    /**
     * <code>optional int64 duration = 6;</code>
     *
     * <pre>
     * Time that an action took to be performed. A primary example is how long
     * a tutorial was open before navigating away.
     * </pre>
     */
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 duration = 6;</code>
     *
     * <pre>
     * Time that an action took to be performed. A primary example is how long
     * a tutorial was open before navigating away.
     * </pre>
     */
    public long getDuration() {
      return duration_;
    }
    /**
     * <code>optional int64 duration = 6;</code>
     *
     * <pre>
     * Time that an action took to be performed. A primary example is how long
     * a tutorial was open before navigating away.
     * </pre>
     */
    public Builder setDuration(long value) {
      bitField0_ |= 0x00000020;
      duration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 duration = 6;</code>
     *
     * <pre>
     * Time that an action took to be performed. A primary example is how long
     * a tutorial was open before navigating away.
     * </pre>
     */
    public Builder clearDuration() {
      bitField0_ = (bitField0_ & ~0x00000020);
      duration_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:android_studio.FirebaseContextDetails)
  }

  static {
    defaultInstance = new FirebaseContextDetails(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:android_studio.FirebaseContextDetails)
}

