// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface GradleBuildProjectOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int64 id = 1;
  /**
   * <code>optional int64 id = 1;</code>
   *
   * <pre>
   * Identifier, local to the containing AndroidStudioEvent, for the project.
   * Can be used to correlate spans (GradleBuildProfileSpan) with this
   * project for this build only. Is created by sequentially
   * numbering projects as they are encountered.
   * Is not stable across build invocations.
   * </pre>
   */
  boolean hasId();
  /**
   * <code>optional int64 id = 1;</code>
   *
   * <pre>
   * Identifier, local to the containing AndroidStudioEvent, for the project.
   * Can be used to correlate spans (GradleBuildProfileSpan) with this
   * project for this build only. Is created by sequentially
   * numbering projects as they are encountered.
   * Is not stable across build invocations.
   * </pre>
   */
  long getId();

  // optional string android_plugin_version = 2;
  /**
   * <code>optional string android_plugin_version = 2;</code>
   *
   * <pre>
   * Version of our Android Gradle plugin supporting android builds.
   * e.g. '2.0-beta1'
   * For the experimental plugin this is the gradle-core version.
   * </pre>
   */
  boolean hasAndroidPluginVersion();
  /**
   * <code>optional string android_plugin_version = 2;</code>
   *
   * <pre>
   * Version of our Android Gradle plugin supporting android builds.
   * e.g. '2.0-beta1'
   * For the experimental plugin this is the gradle-core version.
   * </pre>
   */
  java.lang.String getAndroidPluginVersion();
  /**
   * <code>optional string android_plugin_version = 2;</code>
   *
   * <pre>
   * Version of our Android Gradle plugin supporting android builds.
   * e.g. '2.0-beta1'
   * For the experimental plugin this is the gradle-core version.
   * </pre>
   */
  com.google.protobuf.ByteString
      getAndroidPluginVersionBytes();

  // optional .android_studio.GradleBuildProject.PluginType android_plugin = 3;
  /**
   * <code>optional .android_studio.GradleBuildProject.PluginType android_plugin = 3;</code>
   *
   * <pre>
   * Which Android Gradle plugin is used.
   * </pre>
   */
  boolean hasAndroidPlugin();
  /**
   * <code>optional .android_studio.GradleBuildProject.PluginType android_plugin = 3;</code>
   *
   * <pre>
   * Which Android Gradle plugin is used.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.GradleBuildProject.PluginType getAndroidPlugin();

  // optional .android_studio.GradleBuildProject.PluginGeneration plugin_generation = 4;
  /**
   * <code>optional .android_studio.GradleBuildProject.PluginGeneration plugin_generation = 4;</code>
   *
   * <pre>
   * Which plugin generation is used.
   * </pre>
   */
  boolean hasPluginGeneration();
  /**
   * <code>optional .android_studio.GradleBuildProject.PluginGeneration plugin_generation = 4;</code>
   *
   * <pre>
   * Which plugin generation is used.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.GradleBuildProject.PluginGeneration getPluginGeneration();

  // optional string build_tools_version = 5;
  /**
   * <code>optional string build_tools_version = 5;</code>
   *
   * <pre>
   * The build tools version used, e.g. '24.0.0 rc2'
   * </pre>
   */
  boolean hasBuildToolsVersion();
  /**
   * <code>optional string build_tools_version = 5;</code>
   *
   * <pre>
   * The build tools version used, e.g. '24.0.0 rc2'
   * </pre>
   */
  java.lang.String getBuildToolsVersion();
  /**
   * <code>optional string build_tools_version = 5;</code>
   *
   * <pre>
   * The build tools version used, e.g. '24.0.0 rc2'
   * </pre>
   */
  com.google.protobuf.ByteString
      getBuildToolsVersionBytes();

  // optional .android_studio.GradleBuildProjectMetrics metrics = 6;
  /**
   * <code>optional .android_studio.GradleBuildProjectMetrics metrics = 6;</code>
   *
   * <pre>
   * Statistics about the project build.
   * Will be used to characterize and bucket projects for subgroup analysis.
   * </pre>
   */
  boolean hasMetrics();
  /**
   * <code>optional .android_studio.GradleBuildProjectMetrics metrics = 6;</code>
   *
   * <pre>
   * Statistics about the project build.
   * Will be used to characterize and bucket projects for subgroup analysis.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics getMetrics();
  /**
   * <code>optional .android_studio.GradleBuildProjectMetrics metrics = 6;</code>
   *
   * <pre>
   * Statistics about the project build.
   * Will be used to characterize and bucket projects for subgroup analysis.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.GradleBuildProjectMetricsOrBuilder getMetricsOrBuilder();

  // repeated .android_studio.GradleBuildVariant variant = 7;
  /**
   * <code>repeated .android_studio.GradleBuildVariant variant = 7;</code>
   *
   * <pre>
   * The variants in this project
   * </pre>
   */
  java.util.List<com.google.wireless.android.sdk.stats.GradleBuildVariant> 
      getVariantList();
  /**
   * <code>repeated .android_studio.GradleBuildVariant variant = 7;</code>
   *
   * <pre>
   * The variants in this project
   * </pre>
   */
  com.google.wireless.android.sdk.stats.GradleBuildVariant getVariant(int index);
  /**
   * <code>repeated .android_studio.GradleBuildVariant variant = 7;</code>
   *
   * <pre>
   * The variants in this project
   * </pre>
   */
  int getVariantCount();
  /**
   * <code>repeated .android_studio.GradleBuildVariant variant = 7;</code>
   *
   * <pre>
   * The variants in this project
   * </pre>
   */
  java.util.List<? extends com.google.wireless.android.sdk.stats.GradleBuildVariantOrBuilder> 
      getVariantOrBuilderList();
  /**
   * <code>repeated .android_studio.GradleBuildVariant variant = 7;</code>
   *
   * <pre>
   * The variants in this project
   * </pre>
   */
  com.google.wireless.android.sdk.stats.GradleBuildVariantOrBuilder getVariantOrBuilder(
      int index);

  // optional int64 atoms = 8;
  /**
   * <code>optional int64 atoms = 8;</code>
   *
   * <pre>
   * For instantApps, the number of dependent atoms.
   * </pre>
   */
  boolean hasAtoms();
  /**
   * <code>optional int64 atoms = 8;</code>
   *
   * <pre>
   * For instantApps, the number of dependent atoms.
   * </pre>
   */
  long getAtoms();
}
