// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * Protobuf type {@code android_studio.GradleBuildProjectMetrics}
 */
public  final class GradleBuildProjectMetrics extends
    com.google.protobuf.GeneratedMessage
    implements GradleBuildProjectMetricsOrBuilder {
  // Use GradleBuildProjectMetrics.newBuilder() to construct.
  private GradleBuildProjectMetrics(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private GradleBuildProjectMetrics(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final GradleBuildProjectMetrics defaultInstance;
  public static GradleBuildProjectMetrics getDefaultInstance() {
    return defaultInstance;
  }

  public GradleBuildProjectMetrics getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private GradleBuildProjectMetrics(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            metricsTimeNs_ = input.readInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            apkSize_ = input.readInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            resourcesApSize_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleBuildProjectMetrics_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleBuildProjectMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics.class, com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics.Builder.class);
  }

  public static com.google.protobuf.Parser<GradleBuildProjectMetrics> PARSER =
      new com.google.protobuf.AbstractParser<GradleBuildProjectMetrics>() {
    public GradleBuildProjectMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GradleBuildProjectMetrics(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<GradleBuildProjectMetrics> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional int64 metrics_time_ns = 1;
  public static final int METRICS_TIME_NS_FIELD_NUMBER = 1;
  private long metricsTimeNs_;
  /**
   * <code>optional int64 metrics_time_ns = 1;</code>
   *
   * <pre>
   * The time taken to collect these metrics
   * </pre>
   */
  public boolean hasMetricsTimeNs() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int64 metrics_time_ns = 1;</code>
   *
   * <pre>
   * The time taken to collect these metrics
   * </pre>
   */
  public long getMetricsTimeNs() {
    return metricsTimeNs_;
  }

  // optional int64 apk_size = 2;
  public static final int APK_SIZE_FIELD_NUMBER = 2;
  private long apkSize_;
  /**
   * <code>optional int64 apk_size = 2;</code>
   *
   * <pre>
   * The size of the APK built, if relevant.
   * </pre>
   */
  public boolean hasApkSize() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int64 apk_size = 2;</code>
   *
   * <pre>
   * The size of the APK built, if relevant.
   * </pre>
   */
  public long getApkSize() {
    return apkSize_;
  }

  // optional int64 resources_ap_size = 3;
  public static final int RESOURCES_AP_SIZE_FIELD_NUMBER = 3;
  private long resourcesApSize_;
  /**
   * <code>optional int64 resources_ap_size = 3;</code>
   *
   * <pre>
   * The size of the resources_ap included in that apk.
   * </pre>
   */
  public boolean hasResourcesApSize() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int64 resources_ap_size = 3;</code>
   *
   * <pre>
   * The size of the resources_ap included in that apk.
   * </pre>
   */
  public long getResourcesApSize() {
    return resourcesApSize_;
  }

  private void initFields() {
    metricsTimeNs_ = 0L;
    apkSize_ = 0L;
    resourcesApSize_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, metricsTimeNs_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(2, apkSize_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt64(3, resourcesApSize_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, metricsTimeNs_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, apkSize_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, resourcesApSize_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code android_studio.GradleBuildProjectMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.google.wireless.android.sdk.stats.GradleBuildProjectMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleBuildProjectMetrics_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleBuildProjectMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics.class, com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      metricsTimeNs_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      apkSize_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      resourcesApSize_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleBuildProjectMetrics_descriptor;
    }

    public com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics.getDefaultInstance();
    }

    public com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics build() {
      com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics buildPartial() {
      com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics result = new com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.metricsTimeNs_ = metricsTimeNs_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.apkSize_ = apkSize_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.resourcesApSize_ = resourcesApSize_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics) {
        return mergeFrom((com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics other) {
      if (other == com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics.getDefaultInstance()) return this;
      if (other.hasMetricsTimeNs()) {
        setMetricsTimeNs(other.getMetricsTimeNs());
      }
      if (other.hasApkSize()) {
        setApkSize(other.getApkSize());
      }
      if (other.hasResourcesApSize()) {
        setResourcesApSize(other.getResourcesApSize());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.wireless.android.sdk.stats.GradleBuildProjectMetrics) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional int64 metrics_time_ns = 1;
    private long metricsTimeNs_ ;
    /**
     * <code>optional int64 metrics_time_ns = 1;</code>
     *
     * <pre>
     * The time taken to collect these metrics
     * </pre>
     */
    public boolean hasMetricsTimeNs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 metrics_time_ns = 1;</code>
     *
     * <pre>
     * The time taken to collect these metrics
     * </pre>
     */
    public long getMetricsTimeNs() {
      return metricsTimeNs_;
    }
    /**
     * <code>optional int64 metrics_time_ns = 1;</code>
     *
     * <pre>
     * The time taken to collect these metrics
     * </pre>
     */
    public Builder setMetricsTimeNs(long value) {
      bitField0_ |= 0x00000001;
      metricsTimeNs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 metrics_time_ns = 1;</code>
     *
     * <pre>
     * The time taken to collect these metrics
     * </pre>
     */
    public Builder clearMetricsTimeNs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      metricsTimeNs_ = 0L;
      onChanged();
      return this;
    }

    // optional int64 apk_size = 2;
    private long apkSize_ ;
    /**
     * <code>optional int64 apk_size = 2;</code>
     *
     * <pre>
     * The size of the APK built, if relevant.
     * </pre>
     */
    public boolean hasApkSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 apk_size = 2;</code>
     *
     * <pre>
     * The size of the APK built, if relevant.
     * </pre>
     */
    public long getApkSize() {
      return apkSize_;
    }
    /**
     * <code>optional int64 apk_size = 2;</code>
     *
     * <pre>
     * The size of the APK built, if relevant.
     * </pre>
     */
    public Builder setApkSize(long value) {
      bitField0_ |= 0x00000002;
      apkSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 apk_size = 2;</code>
     *
     * <pre>
     * The size of the APK built, if relevant.
     * </pre>
     */
    public Builder clearApkSize() {
      bitField0_ = (bitField0_ & ~0x00000002);
      apkSize_ = 0L;
      onChanged();
      return this;
    }

    // optional int64 resources_ap_size = 3;
    private long resourcesApSize_ ;
    /**
     * <code>optional int64 resources_ap_size = 3;</code>
     *
     * <pre>
     * The size of the resources_ap included in that apk.
     * </pre>
     */
    public boolean hasResourcesApSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 resources_ap_size = 3;</code>
     *
     * <pre>
     * The size of the resources_ap included in that apk.
     * </pre>
     */
    public long getResourcesApSize() {
      return resourcesApSize_;
    }
    /**
     * <code>optional int64 resources_ap_size = 3;</code>
     *
     * <pre>
     * The size of the resources_ap included in that apk.
     * </pre>
     */
    public Builder setResourcesApSize(long value) {
      bitField0_ |= 0x00000004;
      resourcesApSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 resources_ap_size = 3;</code>
     *
     * <pre>
     * The size of the resources_ap included in that apk.
     * </pre>
     */
    public Builder clearResourcesApSize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      resourcesApSize_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:android_studio.GradleBuildProjectMetrics)
  }

  static {
    defaultInstance = new GradleBuildProjectMetrics(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:android_studio.GradleBuildProjectMetrics)
}

