// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * Protobuf type {@code android_studio.GradleNativeAndroidModule}
 *
 * <pre>
 * per "native" (C++) android module Gradle metrics.
 * </pre>
 */
public  final class GradleNativeAndroidModule extends
    com.google.protobuf.GeneratedMessage
    implements GradleNativeAndroidModuleOrBuilder {
  // Use GradleNativeAndroidModule.newBuilder() to construct.
  private GradleNativeAndroidModule(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private GradleNativeAndroidModule(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final GradleNativeAndroidModule defaultInstance;
  public static GradleNativeAndroidModule getDefaultInstance() {
    return defaultInstance;
  }

  public GradleNativeAndroidModule getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private GradleNativeAndroidModule(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            appId_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            moduleName_ = input.readBytes();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();
            com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.NativeBuildSystemType value = com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.NativeBuildSystemType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(3, rawValue);
            } else {
              bitField0_ |= 0x00000004;
              buildSystemType_ = value;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleNativeAndroidModule_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleNativeAndroidModule_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.class, com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.Builder.class);
  }

  public static com.google.protobuf.Parser<GradleNativeAndroidModule> PARSER =
      new com.google.protobuf.AbstractParser<GradleNativeAndroidModule>() {
    public GradleNativeAndroidModule parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GradleNativeAndroidModule(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<GradleNativeAndroidModule> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code android_studio.GradleNativeAndroidModule.NativeBuildSystemType}
   *
   * <pre>
   * The various native build systems we support to be used from Gradle.
   * </pre>
   */
  public enum NativeBuildSystemType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_NATIVE_BUILD_SYSTEM_TYPE = 0;</code>
     */
    UNKNOWN_NATIVE_BUILD_SYSTEM_TYPE(0, 0),
    /**
     * <code>GRADLE_EXPERIMENTAL = 1;</code>
     *
     * <pre>
     * The Gradle epxerimental plugin
     * </pre>
     */
    GRADLE_EXPERIMENTAL(1, 1),
    /**
     * <code>NDK_COMPILE = 2;</code>
     *
     * <pre>
     * The compilation part of NDK builds (Android's native build system).
     * </pre>
     */
    NDK_COMPILE(2, 2),
    /**
     * <code>NDK_BUILD = 3;</code>
     *
     * <pre>
     * full NDK builds (Android's native build system).
     * </pre>
     */
    NDK_BUILD(3, 3),
    /**
     * <code>CMAKE = 4;</code>
     *
     * <pre>
     * CMake is a very common C++ build system.
     * </pre>
     */
    CMAKE(4, 4),
    ;

    /**
     * <code>UNKNOWN_NATIVE_BUILD_SYSTEM_TYPE = 0;</code>
     */
    public static final int UNKNOWN_NATIVE_BUILD_SYSTEM_TYPE_VALUE = 0;
    /**
     * <code>GRADLE_EXPERIMENTAL = 1;</code>
     *
     * <pre>
     * The Gradle epxerimental plugin
     * </pre>
     */
    public static final int GRADLE_EXPERIMENTAL_VALUE = 1;
    /**
     * <code>NDK_COMPILE = 2;</code>
     *
     * <pre>
     * The compilation part of NDK builds (Android's native build system).
     * </pre>
     */
    public static final int NDK_COMPILE_VALUE = 2;
    /**
     * <code>NDK_BUILD = 3;</code>
     *
     * <pre>
     * full NDK builds (Android's native build system).
     * </pre>
     */
    public static final int NDK_BUILD_VALUE = 3;
    /**
     * <code>CMAKE = 4;</code>
     *
     * <pre>
     * CMake is a very common C++ build system.
     * </pre>
     */
    public static final int CMAKE_VALUE = 4;


    public final int getNumber() { return value; }

    public static NativeBuildSystemType valueOf(int value) {
      switch (value) {
        case 0: return UNKNOWN_NATIVE_BUILD_SYSTEM_TYPE;
        case 1: return GRADLE_EXPERIMENTAL;
        case 2: return NDK_COMPILE;
        case 3: return NDK_BUILD;
        case 4: return CMAKE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NativeBuildSystemType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<NativeBuildSystemType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NativeBuildSystemType>() {
            public NativeBuildSystemType findValueByNumber(int number) {
              return NativeBuildSystemType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.getDescriptor().getEnumTypes().get(0);
    }

    private static final NativeBuildSystemType[] VALUES = values();

    public static NativeBuildSystemType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private NativeBuildSystemType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.GradleNativeAndroidModule.NativeBuildSystemType)
  }

  private int bitField0_;
  // optional string app_id = 1;
  public static final int APP_ID_FIELD_NUMBER = 1;
  private java.lang.Object appId_;
  /**
   * <code>optional string app_id = 1;</code>
   *
   * <pre>
   * Client-side salted, sha256 of the application id
   * the app_id is the id for the user's android app
   * which we salt with a client unique salt and then sha256
   * so it is anonymized and is unique per user, but has a 1-N relation.
   * </pre>
   */
  public boolean hasAppId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string app_id = 1;</code>
   *
   * <pre>
   * Client-side salted, sha256 of the application id
   * the app_id is the id for the user's android app
   * which we salt with a client unique salt and then sha256
   * so it is anonymized and is unique per user, but has a 1-N relation.
   * </pre>
   */
  public java.lang.String getAppId() {
    java.lang.Object ref = appId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        appId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string app_id = 1;</code>
   *
   * <pre>
   * Client-side salted, sha256 of the application id
   * the app_id is the id for the user's android app
   * which we salt with a client unique salt and then sha256
   * so it is anonymized and is unique per user, but has a 1-N relation.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getAppIdBytes() {
    java.lang.Object ref = appId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string module_name = 2;
  public static final int MODULE_NAME_FIELD_NUMBER = 2;
  private java.lang.Object moduleName_;
  /**
   * <code>optional string module_name = 2;</code>
   *
   * <pre>
   * Client-side salted, sha256 of the module name.
   * </pre>
   */
  public boolean hasModuleName() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string module_name = 2;</code>
   *
   * <pre>
   * Client-side salted, sha256 of the module name.
   * </pre>
   */
  public java.lang.String getModuleName() {
    java.lang.Object ref = moduleName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        moduleName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string module_name = 2;</code>
   *
   * <pre>
   * Client-side salted, sha256 of the module name.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getModuleNameBytes() {
    java.lang.Object ref = moduleName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      moduleName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional .android_studio.GradleNativeAndroidModule.NativeBuildSystemType build_system_type = 3;
  public static final int BUILD_SYSTEM_TYPE_FIELD_NUMBER = 3;
  private com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.NativeBuildSystemType buildSystemType_;
  /**
   * <code>optional .android_studio.GradleNativeAndroidModule.NativeBuildSystemType build_system_type = 3;</code>
   *
   * <pre>
   * True if this module is a library.
   * </pre>
   */
  public boolean hasBuildSystemType() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional .android_studio.GradleNativeAndroidModule.NativeBuildSystemType build_system_type = 3;</code>
   *
   * <pre>
   * True if this module is a library.
   * </pre>
   */
  public com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.NativeBuildSystemType getBuildSystemType() {
    return buildSystemType_;
  }

  private void initFields() {
    appId_ = "";
    moduleName_ = "";
    buildSystemType_ = com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.NativeBuildSystemType.UNKNOWN_NATIVE_BUILD_SYSTEM_TYPE;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getAppIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getModuleNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeEnum(3, buildSystemType_.getNumber());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getAppIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getModuleNameBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, buildSystemType_.getNumber());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.google.wireless.android.sdk.stats.GradleNativeAndroidModule parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.GradleNativeAndroidModule parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleNativeAndroidModule parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.GradleNativeAndroidModule parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleNativeAndroidModule parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.GradleNativeAndroidModule parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleNativeAndroidModule parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.GradleNativeAndroidModule parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleNativeAndroidModule parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.wireless.android.sdk.stats.GradleNativeAndroidModule parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.GradleNativeAndroidModule prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code android_studio.GradleNativeAndroidModule}
   *
   * <pre>
   * per "native" (C++) android module Gradle metrics.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.google.wireless.android.sdk.stats.GradleNativeAndroidModuleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleNativeAndroidModule_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleNativeAndroidModule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.class, com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      appId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      moduleName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      buildSystemType_ = com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.NativeBuildSystemType.UNKNOWN_NATIVE_BUILD_SYSTEM_TYPE;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleNativeAndroidModule_descriptor;
    }

    public com.google.wireless.android.sdk.stats.GradleNativeAndroidModule getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.getDefaultInstance();
    }

    public com.google.wireless.android.sdk.stats.GradleNativeAndroidModule build() {
      com.google.wireless.android.sdk.stats.GradleNativeAndroidModule result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.wireless.android.sdk.stats.GradleNativeAndroidModule buildPartial() {
      com.google.wireless.android.sdk.stats.GradleNativeAndroidModule result = new com.google.wireless.android.sdk.stats.GradleNativeAndroidModule(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.appId_ = appId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.moduleName_ = moduleName_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.buildSystemType_ = buildSystemType_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.GradleNativeAndroidModule) {
        return mergeFrom((com.google.wireless.android.sdk.stats.GradleNativeAndroidModule)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.GradleNativeAndroidModule other) {
      if (other == com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.getDefaultInstance()) return this;
      if (other.hasAppId()) {
        bitField0_ |= 0x00000001;
        appId_ = other.appId_;
        onChanged();
      }
      if (other.hasModuleName()) {
        bitField0_ |= 0x00000002;
        moduleName_ = other.moduleName_;
        onChanged();
      }
      if (other.hasBuildSystemType()) {
        setBuildSystemType(other.getBuildSystemType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.wireless.android.sdk.stats.GradleNativeAndroidModule parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.wireless.android.sdk.stats.GradleNativeAndroidModule) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string app_id = 1;
    private java.lang.Object appId_ = "";
    /**
     * <code>optional string app_id = 1;</code>
     *
     * <pre>
     * Client-side salted, sha256 of the application id
     * the app_id is the id for the user's android app
     * which we salt with a client unique salt and then sha256
     * so it is anonymized and is unique per user, but has a 1-N relation.
     * </pre>
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string app_id = 1;</code>
     *
     * <pre>
     * Client-side salted, sha256 of the application id
     * the app_id is the id for the user's android app
     * which we salt with a client unique salt and then sha256
     * so it is anonymized and is unique per user, but has a 1-N relation.
     * </pre>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        appId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string app_id = 1;</code>
     *
     * <pre>
     * Client-side salted, sha256 of the application id
     * the app_id is the id for the user's android app
     * which we salt with a client unique salt and then sha256
     * so it is anonymized and is unique per user, but has a 1-N relation.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string app_id = 1;</code>
     *
     * <pre>
     * Client-side salted, sha256 of the application id
     * the app_id is the id for the user's android app
     * which we salt with a client unique salt and then sha256
     * so it is anonymized and is unique per user, but has a 1-N relation.
     * </pre>
     */
    public Builder setAppId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      appId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string app_id = 1;</code>
     *
     * <pre>
     * Client-side salted, sha256 of the application id
     * the app_id is the id for the user's android app
     * which we salt with a client unique salt and then sha256
     * so it is anonymized and is unique per user, but has a 1-N relation.
     * </pre>
     */
    public Builder clearAppId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      appId_ = getDefaultInstance().getAppId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string app_id = 1;</code>
     *
     * <pre>
     * Client-side salted, sha256 of the application id
     * the app_id is the id for the user's android app
     * which we salt with a client unique salt and then sha256
     * so it is anonymized and is unique per user, but has a 1-N relation.
     * </pre>
     */
    public Builder setAppIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      appId_ = value;
      onChanged();
      return this;
    }

    // optional string module_name = 2;
    private java.lang.Object moduleName_ = "";
    /**
     * <code>optional string module_name = 2;</code>
     *
     * <pre>
     * Client-side salted, sha256 of the module name.
     * </pre>
     */
    public boolean hasModuleName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string module_name = 2;</code>
     *
     * <pre>
     * Client-side salted, sha256 of the module name.
     * </pre>
     */
    public java.lang.String getModuleName() {
      java.lang.Object ref = moduleName_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        moduleName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string module_name = 2;</code>
     *
     * <pre>
     * Client-side salted, sha256 of the module name.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getModuleNameBytes() {
      java.lang.Object ref = moduleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        moduleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string module_name = 2;</code>
     *
     * <pre>
     * Client-side salted, sha256 of the module name.
     * </pre>
     */
    public Builder setModuleName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      moduleName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string module_name = 2;</code>
     *
     * <pre>
     * Client-side salted, sha256 of the module name.
     * </pre>
     */
    public Builder clearModuleName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      moduleName_ = getDefaultInstance().getModuleName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string module_name = 2;</code>
     *
     * <pre>
     * Client-side salted, sha256 of the module name.
     * </pre>
     */
    public Builder setModuleNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      moduleName_ = value;
      onChanged();
      return this;
    }

    // optional .android_studio.GradleNativeAndroidModule.NativeBuildSystemType build_system_type = 3;
    private com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.NativeBuildSystemType buildSystemType_ = com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.NativeBuildSystemType.UNKNOWN_NATIVE_BUILD_SYSTEM_TYPE;
    /**
     * <code>optional .android_studio.GradleNativeAndroidModule.NativeBuildSystemType build_system_type = 3;</code>
     *
     * <pre>
     * True if this module is a library.
     * </pre>
     */
    public boolean hasBuildSystemType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .android_studio.GradleNativeAndroidModule.NativeBuildSystemType build_system_type = 3;</code>
     *
     * <pre>
     * True if this module is a library.
     * </pre>
     */
    public com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.NativeBuildSystemType getBuildSystemType() {
      return buildSystemType_;
    }
    /**
     * <code>optional .android_studio.GradleNativeAndroidModule.NativeBuildSystemType build_system_type = 3;</code>
     *
     * <pre>
     * True if this module is a library.
     * </pre>
     */
    public Builder setBuildSystemType(com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.NativeBuildSystemType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      buildSystemType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.GradleNativeAndroidModule.NativeBuildSystemType build_system_type = 3;</code>
     *
     * <pre>
     * True if this module is a library.
     * </pre>
     */
    public Builder clearBuildSystemType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      buildSystemType_ = com.google.wireless.android.sdk.stats.GradleNativeAndroidModule.NativeBuildSystemType.UNKNOWN_NATIVE_BUILD_SYSTEM_TYPE;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:android_studio.GradleNativeAndroidModule)
  }

  static {
    defaultInstance = new GradleNativeAndroidModule(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:android_studio.GradleNativeAndroidModule)
}

