// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface GradleBuildProfileSpanOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int64 id = 1;
  /**
   * <code>optional int64 id = 1;</code>
   *
   * <pre>
   * Identifier for this span, created by sequentially allocating IDs to spans
   * as they start. Used only for the parent-child relationship of spans, to
   * show execution that is part of another span.
   * Not stable or meaningful across builds.
   * </pre>
   */
  boolean hasId();
  /**
   * <code>optional int64 id = 1;</code>
   *
   * <pre>
   * Identifier for this span, created by sequentially allocating IDs to spans
   * as they start. Used only for the parent-child relationship of spans, to
   * show execution that is part of another span.
   * Not stable or meaningful across builds.
   * </pre>
   */
  long getId();

  // optional int64 parent_id = 2;
  /**
   * <code>optional int64 parent_id = 2;</code>
   *
   * <pre>
   * For nested spans: the id for containing span.
   * See GradleBuildProfileSpan.id.
   * </pre>
   */
  boolean hasParentId();
  /**
   * <code>optional int64 parent_id = 2;</code>
   *
   * <pre>
   * For nested spans: the id for containing span.
   * See GradleBuildProfileSpan.id.
   * </pre>
   */
  long getParentId();

  // optional int64 start_time_in_ms = 3;
  /**
   * <code>optional int64 start_time_in_ms = 3;</code>
   *
   * <pre>
   * The start time of this event
   * </pre>
   */
  boolean hasStartTimeInMs();
  /**
   * <code>optional int64 start_time_in_ms = 3;</code>
   *
   * <pre>
   * The start time of this event
   * </pre>
   */
  long getStartTimeInMs();

  // optional int64 duration_in_ms = 4;
  /**
   * <code>optional int64 duration_in_ms = 4;</code>
   *
   * <pre>
   * The duration of this event. May be zero.
   * </pre>
   */
  boolean hasDurationInMs();
  /**
   * <code>optional int64 duration_in_ms = 4;</code>
   *
   * <pre>
   * The duration of this event. May be zero.
   * </pre>
   */
  long getDurationInMs();

  // optional .android_studio.GradleBuildProfileSpan.ExecutionType type = 5;
  /**
   * <code>optional .android_studio.GradleBuildProfileSpan.ExecutionType type = 5;</code>
   *
   * <pre>
   * The type of event recorded
   * </pre>
   */
  boolean hasType();
  /**
   * <code>optional .android_studio.GradleBuildProfileSpan.ExecutionType type = 5;</code>
   *
   * <pre>
   * The type of event recorded
   * </pre>
   */
  com.google.wireless.android.sdk.stats.GradleBuildProfileSpan.ExecutionType getType();

  // optional .android_studio.GradleTransformExecution transform = 6;
  /**
   * <code>optional .android_studio.GradleTransformExecution transform = 6;</code>
   *
   * <pre>
   * More informations about the execution of TransformTasks.
   * Only used when executionType is TASK_TRANSFORM_PREPARATION or
   * TASK_TRANSFORM.
   * </pre>
   */
  boolean hasTransform();
  /**
   * <code>optional .android_studio.GradleTransformExecution transform = 6;</code>
   *
   * <pre>
   * More informations about the execution of TransformTasks.
   * Only used when executionType is TASK_TRANSFORM_PREPARATION or
   * TASK_TRANSFORM.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.GradleTransformExecution getTransform();
  /**
   * <code>optional .android_studio.GradleTransformExecution transform = 6;</code>
   *
   * <pre>
   * More informations about the execution of TransformTasks.
   * Only used when executionType is TASK_TRANSFORM_PREPARATION or
   * TASK_TRANSFORM.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.GradleTransformExecutionOrBuilder getTransformOrBuilder();

  // optional .android_studio.GradleTaskExecution task = 9;
  /**
   * <code>optional .android_studio.GradleTaskExecution task = 9;</code>
   *
   * <pre>
   * More informations about the execution of Tasks.
   * Only used when executionType is TASK_EXECUTION
   * </pre>
   */
  boolean hasTask();
  /**
   * <code>optional .android_studio.GradleTaskExecution task = 9;</code>
   *
   * <pre>
   * More informations about the execution of Tasks.
   * Only used when executionType is TASK_EXECUTION
   * </pre>
   */
  com.google.wireless.android.sdk.stats.GradleTaskExecution getTask();
  /**
   * <code>optional .android_studio.GradleTaskExecution task = 9;</code>
   *
   * <pre>
   * More informations about the execution of Tasks.
   * Only used when executionType is TASK_EXECUTION
   * </pre>
   */
  com.google.wireless.android.sdk.stats.GradleTaskExecutionOrBuilder getTaskOrBuilder();

  // optional int64 project = 7;
  /**
   * <code>optional int64 project = 7;</code>
   *
   * <pre>
   * Session id of the GradleBuildProject that this span is part of.
   * The ID is not stable nor meaningful over multiple GradleBuildProfile.
   * See GradleBuildProfile.id
   * </pre>
   */
  boolean hasProject();
  /**
   * <code>optional int64 project = 7;</code>
   *
   * <pre>
   * Session id of the GradleBuildProject that this span is part of.
   * The ID is not stable nor meaningful over multiple GradleBuildProfile.
   * See GradleBuildProfile.id
   * </pre>
   */
  long getProject();

  // optional int64 variant = 8;
  /**
   * <code>optional int64 variant = 8;</code>
   *
   * <pre>
   * Session id of the GradleBuildVariant that this span is part of.
   * The ID is not stable nor meaningful over multiple GradleBuildProfile.
   * See GradleBuildVariant.id
   * </pre>
   */
  boolean hasVariant();
  /**
   * <code>optional int64 variant = 8;</code>
   *
   * <pre>
   * Session id of the GradleBuildVariant that this span is part of.
   * The ID is not stable nor meaningful over multiple GradleBuildProfile.
   * See GradleBuildVariant.id
   * </pre>
   */
  long getVariant();

  // optional int64 thread_id = 10;
  /**
   * <code>optional int64 thread_id = 10;</code>
   *
   * <pre>
   * Thread that this execution occurs on.
   * Generated by sequentially numbering java threads that do work that is
   * recorded.
   * Will not be populated for async recorded events,
   * such as from the task execution listener.
   * </pre>
   */
  boolean hasThreadId();
  /**
   * <code>optional int64 thread_id = 10;</code>
   *
   * <pre>
   * Thread that this execution occurs on.
   * Generated by sequentially numbering java threads that do work that is
   * recorded.
   * Will not be populated for async recorded events,
   * such as from the task execution listener.
   * </pre>
   */
  long getThreadId();
}
