// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface LayoutInspectorEventOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional .android_studio.LayoutInspectorEvent.LayoutInspectorEventType type = 1;
  /**
   * <code>optional .android_studio.LayoutInspectorEvent.LayoutInspectorEventType type = 1;</code>
   *
   * <pre>
   * Type of event
   * </pre>
   */
  boolean hasType();
  /**
   * <code>optional .android_studio.LayoutInspectorEvent.LayoutInspectorEventType type = 1;</code>
   *
   * <pre>
   * Type of event
   * </pre>
   */
  com.google.wireless.android.sdk.stats.LayoutInspectorEvent.LayoutInspectorEventType getType();

  // optional int64 duration_in_ms = 2;
  /**
   * <code>optional int64 duration_in_ms = 2;</code>
   *
   * <pre>
   * defined if LayoutInspectorEventType = CAPTURE, CAPTURE_TIME_OUT
   * </pre>
   */
  boolean hasDurationInMs();
  /**
   * <code>optional int64 duration_in_ms = 2;</code>
   *
   * <pre>
   * defined if LayoutInspectorEventType = CAPTURE, CAPTURE_TIME_OUT
   * </pre>
   */
  long getDurationInMs();

  // optional int64 data_size = 3;
  /**
   * <code>optional int64 data_size = 3;</code>
   *
   * <pre>
   * defined if LayoutInspectorEventType = CAPTURE
   * size of the captured view data in bytes
   * </pre>
   */
  boolean hasDataSize();
  /**
   * <code>optional int64 data_size = 3;</code>
   *
   * <pre>
   * defined if LayoutInspectorEventType = CAPTURE
   * size of the captured view data in bytes
   * </pre>
   */
  long getDataSize();
}
