// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface LintPerformanceOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int64 analysis_time_ms = 1;
  /**
   * <code>optional int64 analysis_time_ms = 1;</code>
   *
   * <pre>
   * time to run lint in micro seconds
   * </pre>
   */
  boolean hasAnalysisTimeMs();
  /**
   * <code>optional int64 analysis_time_ms = 1;</code>
   *
   * <pre>
   * time to run lint in micro seconds
   * </pre>
   */
  long getAnalysisTimeMs();

  // optional int64 file_count = 2;
  /**
   * <code>optional int64 file_count = 2;</code>
   *
   * <pre>
   * number of files in project
   * </pre>
   */
  boolean hasFileCount();
  /**
   * <code>optional int64 file_count = 2;</code>
   *
   * <pre>
   * number of files in project
   * </pre>
   */
  long getFileCount();

  // optional int64 module_count = 3;
  /**
   * <code>optional int64 module_count = 3;</code>
   *
   * <pre>
   * number of gradle projects in session
   * </pre>
   */
  boolean hasModuleCount();
  /**
   * <code>optional int64 module_count = 3;</code>
   *
   * <pre>
   * number of gradle projects in session
   * </pre>
   */
  long getModuleCount();
}
