// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface ProductDetailsOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional .android_studio.ProductDetails.ProductKind product = 1;
  /**
   * <code>optional .android_studio.ProductDetails.ProductKind product = 1;</code>
   *
   * <pre>
   * The product this event relates to.
   * </pre>
   */
  boolean hasProduct();
  /**
   * <code>optional .android_studio.ProductDetails.ProductKind product = 1;</code>
   *
   * <pre>
   * The product this event relates to.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.ProductDetails.ProductKind getProduct();

  // optional string build = 2;
  /**
   * <code>optional string build = 2;</code>
   *
   * <pre>
   * The build ID of Android Studio.
   * </pre>
   */
  boolean hasBuild();
  /**
   * <code>optional string build = 2;</code>
   *
   * <pre>
   * The build ID of Android Studio.
   * </pre>
   */
  java.lang.String getBuild();
  /**
   * <code>optional string build = 2;</code>
   *
   * <pre>
   * The build ID of Android Studio.
   * </pre>
   */
  com.google.protobuf.ByteString
      getBuildBytes();

  // optional string version = 3;
  /**
   * <code>optional string version = 3;</code>
   *
   * <pre>
   * The version of the product.
   * </pre>
   */
  boolean hasVersion();
  /**
   * <code>optional string version = 3;</code>
   *
   * <pre>
   * The version of the product.
   * </pre>
   */
  java.lang.String getVersion();
  /**
   * <code>optional string version = 3;</code>
   *
   * <pre>
   * The version of the product.
   * </pre>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  // optional bool preview = 4;
  /**
   * <code>optional bool preview = 4;</code>
   *
   * <pre>
   * Historical: never used as it was not providing enough info. Use channel
   * instead as it distinguishes between different kinds of preview releases.
   * </pre>
   */
  boolean hasPreview();
  /**
   * <code>optional bool preview = 4;</code>
   *
   * <pre>
   * Historical: never used as it was not providing enough info. Use channel
   * instead as it distinguishes between different kinds of preview releases.
   * </pre>
   */
  boolean getPreview();

  // optional .android_studio.ProductDetails.CpuArchitecture os_architecture = 5;
  /**
   * <code>optional .android_studio.ProductDetails.CpuArchitecture os_architecture = 5;</code>
   *
   * <pre>
   * The CPU archtecture the product is running on.
   * </pre>
   */
  boolean hasOsArchitecture();
  /**
   * <code>optional .android_studio.ProductDetails.CpuArchitecture os_architecture = 5;</code>
   *
   * <pre>
   * The CPU archtecture the product is running on.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.ProductDetails.CpuArchitecture getOsArchitecture();

  // optional .android_studio.ProductDetails.SoftwareLifeCycleChannel channel = 6;
  /**
   * <code>optional .android_studio.ProductDetails.SoftwareLifeCycleChannel channel = 6;</code>
   *
   * <pre>
   * The state in the software lifecycle of this product.
   * </pre>
   */
  boolean hasChannel();
  /**
   * <code>optional .android_studio.ProductDetails.SoftwareLifeCycleChannel channel = 6;</code>
   *
   * <pre>
   * The state in the software lifecycle of this product.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.ProductDetails.SoftwareLifeCycleChannel getChannel();
}
