// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface ProfilerSessionCreationMetaDataOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional .android_studio.ProfilerSessionCreationMetaData.SessionType created_type = 1;
  /**
   * <code>optional .android_studio.ProfilerSessionCreationMetaData.SessionType created_type = 1;</code>
   *
   * <pre>
   * The type of session created
   * </pre>
   */
  boolean hasCreatedType();
  /**
   * <code>optional .android_studio.ProfilerSessionCreationMetaData.SessionType created_type = 1;</code>
   *
   * <pre>
   * The type of session created
   * </pre>
   */
  com.google.wireless.android.sdk.stats.ProfilerSessionCreationMetaData.SessionType getCreatedType();

  // optional .android_studio.ProfilerSessionCreationMetaData.CreationSource creation_source = 2;
  /**
   * <code>optional .android_studio.ProfilerSessionCreationMetaData.CreationSource creation_source = 2;</code>
   *
   * <pre>
   * How the session is created.
   * </pre>
   */
  boolean hasCreationSource();
  /**
   * <code>optional .android_studio.ProfilerSessionCreationMetaData.CreationSource creation_source = 2;</code>
   *
   * <pre>
   * How the session is created.
   * </pre>
   */
  com.google.wireless.android.sdk.stats.ProfilerSessionCreationMetaData.CreationSource getCreationSource();
}
