apply plugin: 'java'
apply plugin: 'jacoco-tools-base'

dependencies {
    compile project(':base:annotations')
    compile project(':base:common')
    compile project(':analytics-library:protos')
    compile project(':analytics-library:shared')
    compile libs.protobuf
    compile libs.guava

    testCompile project(':base:testutils')
    testCompile libs.junit
    testCompile libs.truth
    testCompile project(':analytics-library:tracker')
}

group = 'com.android.tools.analytics-library'
archivesBaseName = 'publisher'
version = rootProject.ext.baseVersion

project.ext.pomName = 'Android Tools Analytics Publisher'
project.ext.pomDesc = 'Library for publishing usage analytics.'

apply from: "$rootDir/buildSrc/base/publish.gradle"
apply from: "$rootDir/buildSrc/base/bintray.gradle"
apply from: "$rootDir/buildSrc/base/javadoc.gradle"
