apply plugin: 'com.android.tools.java-library'
apply plugin: 'com.android.tools.publish'
apply plugin: 'com.android.tools.kotlin'

dependencies {
    implementation libs.com.android.tools.annotations
    implementation project(':base:common')
    implementation project(':analytics-library:protos')
    implementation project(':analytics-library:shared')
    implementation libs.protobuf
    implementation libs.guava

    testImplementation project(':base:testutils')
    testImplementation libs.junit
    testImplementation libs.truth
    testImplementation project(':analytics-library:tracker')
}

group = 'com.android.tools.analytics-library'
archivesBaseName = 'publisher'
version = rootProject.ext.baseVersion

project.ext.pomName = 'Android Tools Analytics Publisher'
project.ext.pomDesc = 'Library for publishing usage analytics.'
