apply plugin: 'java'

// Apply the Jacoco plugin only if we are not on Windows, as there is currently a bug relating to
// long file paths (https://github.com/gradle/gradle/issues/949) that prevents our tools Windows
// build bot from passing.
if (!System.getProperty("os.name").toLowerCase().startsWith("windows")) {
    apply plugin: 'jacoco'
}

dependencies {
    compile project(':base:annotations')
    compile project(':base:common')
    compile project(':analytics-library:protos')
    compile project(':analytics-library:shared')
    compile libs.protobuf
    compile libs.guava

    testCompile project(':base:testutils')
    testCompile libs.junit
    testCompile libs.truth
    testCompile project(':analytics-library:tracker')
}

group = 'com.android.tools.analytics-library'
archivesBaseName = 'publisher'
version = rootProject.ext.baseVersion

project.ext.pomName = 'Android Tools Analytics Publisher'
project.ext.pomDesc = 'Library for publishing usage analytics.'

apply from: "$rootDir/buildSrc/base/publish.gradle"
apply from: "$rootDir/buildSrc/base/bintray.gradle"
apply from: "$rootDir/buildSrc/base/javadoc.gradle"
