apply plugin: 'java'
apply plugin: 'jacoco-tools-base'

dependencies {
    compile project(':analytics-library:protos')
    compile project(':base:annotations')
    compile project(':base:common')
    compile libs.guava
    compile libs.gson

    testCompile libs.junit
    testCompile libs.truth
    testCompile project(':base:testutils')
}

group = 'com.android.tools.analytics-library'
archivesBaseName = 'shared'
version = rootProject.ext.baseVersion

project.ext.pomName = 'Android Tools Analytics Shared Library'
project.ext.pomDesc = 'Helper Library for tracking usage analytics.'

apply from: "$rootDir/buildSrc/base/publish.gradle"
apply from: "$rootDir/buildSrc/base/bintray.gradle"
apply from: "$rootDir/buildSrc/base/javadoc.gradle"
