/*
 * Copyright (C) 2018 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
apply plugin: 'com.android.tools.java-library'
apply plugin: 'com.android.tools.kotlin'
apply plugin: 'com.android.tools.publish'
apply plugin: 'jacoco-tools-base'
apply plugin: 'sdk-java-lib'

dependencies {
    compile project(':analytics-library:protos')
    compile project(':base:annotations')
    compile project(':base:common')
    compile libs.guava
    compile libs.gson
    compile libs.kotlin_stdlib
    compile libs.jna_platform

    testCompile libs.junit
    testCompile libs.truth
    testCompile project(':base:testutils')
}

group = 'com.android.tools.analytics-library'
archivesBaseName = 'shared'
version = rootProject.ext.baseVersion

project.ext.pomName = 'Android Tools Analytics Shared Library'
project.ext.pomDesc = 'Helper Library for tracking usage analytics.'
