apply plugin: 'java'
apply plugin: 'jacoco-tools-base'
apply plugin: 'application'

dependencies {
    compile project(':base:annotations')
    compile project(':analytics-library:protos')
    compile project(':analytics-library:shared')
    compile libs.protobuf
    compile libs.guava
    compile libs.gson

    testCompile project(':base:testutils')
    testCompile libs.junit
    testCompile libs.truth
}

group = 'com.android.tools.analytics-library'
archivesBaseName = 'inspector'
version = rootProject.ext.baseVersion

mainClassName = "com.android.tools.analytics.AnalyticsInspector"
applicationDefaultJvmArgs = ["-ea", "-Xms2g", "-Xmx4g"]

project.ext.pomName = 'Android Tools Analytics Inspector'
project.ext.pomDesc = 'Tool for debugging usage analytics spool files.'

apply from: "$rootDir/buildSrc/base/publish.gradle"
apply from: "$rootDir/buildSrc/base/javadoc.gradle"
